

<div class="page-title">
    <h1 class="fleft">Remediation Plan for <?php echo (!$this->isPdf) ? '<br/>' : '' ?><?php echo $this->rpObj->_client_name ?></h1>
    <?php if (!$this->isPdf): ?>
        <a href="/remediationplan/edit/<?php echo $rpObj->rp_id ?>/type/pdf" class="button" title="Download as PDF"><i class="fa fa-download"></i> PDF</a>
        <a href="/remediationplan/edit/<?php echo $rpObj->rp_id ?>/type/csv" class="button" title="Download as CSV"><i class="fa fa-download"></i> CSV</a>
    <?php endif; ?>
    <div class="cboth"></div>
</div>

<p></p>
<div class="cboth"></div>

<div class="col6" style="float: left;">
    <p><strong>STATUS:</strong><br /><span class="label selected"><?php echo \Assessment\Model\Remediationplan::$statusesNames[$rpObj->rp_status]  ?></span></p>
</div>
<div class="col5"  style="float: left;">
    <p>
        <strong>PERFORMED BY:</strong><br />
        <?php if ($this->isPdf): ?>
            <?php echo $this->rpObj->_performed_name ?>
        <?php else: ?>
            <?php if ($this->writable): ?>
                <span id="toggle-edit-show-1">
                    <?php echo $this->rpObj->_performed_name ?> &nbsp;<a href="" title="Edit"><i class="fa fa-pencil"></i></a>
                </span>
                <span id="toggle-edit-1">
                    <select id="rp_performed_u_id" id="" class="w175">
                        <option value="">Please Select</option>
                        <option value="">---</option>
                        <?php foreach ($this->contacts as $uId => $contact): ?>
                            <option <?php echo ($uId == $this->rpObj->rp_performed_u_id) ? ' SELECTED ' : '' ?> value="<?php echo $uId ?>"><?php echo $contact ?></option>
                        <?php endforeach; ?>
                    </select>
                </span>
            <?php else: ?>
                <?php echo $this->rpObj->_performed_name ?>
            <?php endif; ?>
        <?php endif; ?>
    </p>
</div>
<div class="col5"  style="float: left;">
    <p>
        <strong>APPROVED BY:</strong><br />
        <?php if ($this->isPdf): ?>
            <?php echo $this->rpObj->_approver_name ?>
        <?php else: ?>
            <?php if ($this->writable): ?>
                <span id="toggle-edit-show-4">
                    <?php echo $this->rpObj->_approver_name ?> &nbsp;<a href="" title="Edit"><i class="fa fa-pencil"></i></a>
                </span>
                <span id="toggle-edit-4">
                    <select id="rp_approver_u_id" id="" class="w175">
                        <option value="">Please Select</option>
                        <option value="">---</option>
                        <?php foreach ($this->contactsApr as $uId => $contact): ?>
                            <option <?php echo ($uId == $this->rpObj->rp_approver_u_id) ? ' SELECTED ' : '' ?> value="<?php echo $uId ?>"><?php echo $contact ?></option>
                        <?php endforeach; ?>
                    </select>
                </span>
            <?php else: ?>
                <?php echo $this->rpObj->_approver_name ?>
            <?php endif; ?>
        <?php endif; ?>
    </p>
</div>
<div class="col5"  style="float: left;">
    <p><strong>ASSESSMENT DATE:</strong><br />
        <?php if ($this->writable): ?>
            <span id="toggle-edit-show-2">
                <?php echo ($this->rpObj->rp_incident_date != '0000-00-00') ? $this->rpObj->_rp_incident_date_formatted : '' ?> &nbsp;<a href="" title="Edit"><i class="fa fa-pencil"></i></a>
            </span>
            <span id="toggle-edit-2">
                <input type="text" id="rp_incident_date" class="w175" value="<?php echo ($this->rpObj->rp_incident_date != '0000-00-00') ? $this->rpObj->_rp_incident_date_formatted : '' ?>" />
            </span>
        <?php else: ?>
            <?php echo ($this->rpObj->rp_incident_date != '0000-00-00') ? $this->rpObj->_rp_incident_date_formatted : '' ?>
        <?php endif; ?>
    </p>
</div>
<div class="col4 last" style="float: left;">
    <p><strong>REMEDIATION PLAN DATE:</strong><br />
        <?php if ($this->writable): ?>
            <span id="toggle-edit-show-3">
            <?php echo ($this->rpObj->rp_remediation_date != '0000-00-00') ? $this->rpObj->_rp_remediation_date_formatted : '' ?> &nbsp;<a href="" title="Edit"><i class="fa fa-pencil"></i></a>
        </span>
            <span id="toggle-edit-3">
            <input type="text" id="rp_remediation_date" class="w175" value="<?php echo ($this->rpObj->rp_remediation_date != '0000-00-00') ? $this->rpObj->_rp_remediation_date_formatted : '' ?>" />
        </span>
        <?php else: ?>
            <?php echo ($this->rpObj->rp_remediation_date != '0000-00-00') ? $this->rpObj->_rp_remediation_date_formatted : '' ?>
        <?php endif; ?>
</div>
<div class="cboth"></div>

<p></p>

<table cellpadding="0" cellspacing="0">
    <thead>
        <tr>
            <th>Risk score</th>
            <th>Threat</th>
            <th>Action plan</th>
            <?php if ($this->isPdf): ?>
                <th>Policy number</th>
            <?php endif; ?>
            <th>Status <i class="fa fa-unsorted"></i></th>
            <th>Assignee <i class="fa fa-unsorted"></i></th>
            <th>Approver <i class="fa fa-unsorted"></i></th>
            <th>Target Date <i class="fa fa-unsorted"></i></th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
    <?php $adrId = 0; $adrChange = false; ?>
    <?php foreach ($this->actions as $rpa): ?>
        <?php if ($adrId != $rpa->rpa_adr_id):
            $adrChange = true;
            $adrId = $rpa->rpa_adr_id;
        else:
            $adrChange = false;
        endif; ?>

        <?php if ($adrChange): ?>
            <tr>
                <td colspan="20">
                    <h2><?php if ($this->isPdf): ?><span style="font-size: 13px; font-weight: normal">Location:<?php endif; ?></span><br/><?php echo $rpa->_location_name ?></h2>
                </td>
            </tr>
        <?php endif; ?>
        <?php $notesTaskAtt = $this->noteTable->getNotes($rpa->rpa_id, \Note\Model\Note::NOTE_RPA); ?>
        <?php $notesTaskAssessments = $this->noteTable->getNotesForRemedTask($rpa->rpa_id, $adrId); ?>

        <tr>
            <td class="tdSmall"><?php echo \Assessment\Model\Remediationplanaction::$levelsNames[$rpa->rpa_risk_level] ?></td>
            <td class="tdSmall">
                <?php $rpaThreat = str_replace('Â', '', $rpa->rpa_threat); ?>
                <?php echo str_replace('Â', '', $rpaThreat); ?>
            </td>
            <td class="tdSmall"><?php echo $rpa->rpa_action_plan ?></td>
            <?php if ($this->isPdf): ?>
                <td class="tdSmall"><?php echo $rpa->rpa_policy ?></td>
            <?php endif; ?>
            <td class="acenter"><?php echo \Assessment\Model\Remediationplanaction::$statusesNames[$rpa->rpa_status] ?></td>
            <td><?php echo $rpa->_contact_name ?></td>
            <td><?php echo $rpa->_approver_name ?></td>
            <td><?php echo ($rpa->rpa_target_date != '0000-00-00') ? $rpa->_rpa_target_date_formatted : '' ?></td>
            <td class="aright nowrap">
                <a href="/remediationplan/edittask/<?php echo $rpa->rpa_id ?>/rpId/<?php echo $rpObj->rp_id ?>" class="fancybox" title="Edit"><i class="fa fa-pencil"></i></a> &nbsp;
                <?php /* <a href="/remediationplan/planemail/<?php echo $rpa->rpa_id ?>/rpId/<?php echo $rpObj->rp_id ?>" class="fancybox" title="Email Assignee"><i class="fa fa-envelope"></i></a> &nbsp; */ ?>
                <?php if ($this->writable): ?>
                    <a href="/remediationplan/deletetask/<?php echo $rpa->rpa_id ?>/rpId/<?php echo $rpObj->rp_id ?>" class="i-delete" title="Delete"><i class="fa fa-trash-o"></i></a>
                <?php endif; ?>
                <?php if ($notesTaskAtt->count() || $notesTaskAssessments->count()): ?>
                    <a style="margin-left: 10px;" href="" class="attachments" rel="<?php echo $rpa->rpa_id ?>" title="View Attachments"><i class="fa fa-paperclip"></i></a>
                <?php endif; ?>
            </td>
        </tr>

        <?php //if (!$this->writable): ?>

            <tr class="expandable" id="attachments<?php echo $rpa->rpa_id ?>">
                <td>&nbsp;</td>
                    <?php $colspan = 2; ?>
                    <?php foreach (array('Task attachments' => $notesTaskAtt, 'Questions attachments' => $notesTaskAssessments) as $keyAtt => $notesTask): ?>
                        <td colspan="<?php echo $colspan ?>">
                            <?php if (is_object($notesTask) && ($notesTask->count())): ?>
                                <div>
                                    <div><strong><?php echo $keyAtt ?>:</strong></div>
                                    <div>
                                        <?php foreach ($notesTask as $note): ?>
                                            <?php if (($note->_files != '') || ($note->note_text != '')): ?>
                                                <?php
                                                $_files = explode(',', $note->_files);
                                                ?>
                                                <?php foreach ($_files as $_file): ?>
                                                    <?php
                                                    $_file = explode('::', $_file);
                                                    $_fileName = $_file[0];
                                                    $_fileId = $_file[1];
                                                    ?>
                                                    <?php if (!$this->isPdf): ?>
                                                        <?php if ($note->_files != ''): ?>
                                                            <span style="float: left; margin-right: 5px;" class="<?php echo $this->renderPictoIcon($_fileName); ?>"></span><a href="http://<?php echo $_SERVER['HTTP_HOST'] ?>/files/get/note/<?php echo $note->note_id ?>/<?php echo $_fileId ?>" class="" target="_blank"><?php echo $_fileName ?></a><br/>
                                                        <?php endif; ?>
                                                        <div><?php echo $note->note_text ?></div>
                                                    <?php endif; ?>
                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    </div>
                                </div>
                            <?php endif; ?>
                        </td>
                        <?php $colspan = 5; ?>
                    <?php endforeach; ?>
            </tr>
        <?php //endif; ?>
    <?php endforeach; ?>
    </tbody>
</table>

<?php if ($this->writable && !$this->isPdf): ?>
    <p><a href="/remediationplan/edittask/0/rpId/<?php echo $rpObj->rp_id ?>" class="fancybox button fright"><i class="fa fa-plus-circle"></i> Add</a></p>
<?php endif; ?>

<form action="/remediationplan/edit/<?php echo $this->id ?>" name="" style="width: 600px;" id="formNote" method="POST" enctype="multipart/form-data" class="col2" >
    <input id="rp_performed_u_id_hidden" name="rp_performed_u_id" type="hidden" value="<?php echo $this->rpObj->rp_performed_u_id ?>" />
    <input id="rp_approver_u_id_hidden" name="rp_approver_u_id" type="hidden" value="<?php echo $this->rpObj->rp_approver_u_id ?>" />
    <input id="rp_incident_date_hidden" name="rp_incident_date" type="hidden" value="<?php echo ($this->rpObj->rp_incident_date != '0000-00-00') ? $this->rpObj->_rp_incident_date_formatted : '' ?>" />
    <input id="rp_remediation_date_hidden" name="rp_remediation_date" type="hidden" value="<?php echo ($this->rpObj->rp_remediation_date != '0000-00-00') ? $this->rpObj->_rp_remediation_date_formatted : '' ?>" />

    <?php if ($this->writable && !$this->isPdf): ?>
        <input id="signedoff" type="hidden" name="signedoff" value="0" />
        <input id="requestreview" type="hidden" name="requestreview" value="0" />
        <input type="hidden" name="noteform" value="1" />
        <?php
        $fn = $formNote->get('note_id');
        echo $this->formHidden($fn);
        ?>
        <?php
        $fn = $formNote->get('note_item_type');
        $fn->setValue(4);
        echo $this->formHidden($fn);
        ?>
        <?php
        $fn = $formNote->get('note_item_id');
        $fn->setValue($this->id);
        echo $this->formHidden($fn);
        ?>

        <p style="border: 0;">
            <strong style="line-height: 30px;">Notes</strong><br />
            <?php
            $fn = $formNote->get('note_text');
            echo $this->formTextarea($fn->setAttributes(array('style' => 'width: 570px;')));
            echo $this->formElementErrors($fn);
            ?>

        </p>
        <?php if (!$this->isPdf): ?>
            <p style="border: 0;">
                <strong style="line-height: 30px;">Additional Attachments</strong><br />
                <a id="browseFile" href="javascript:" class="button"><i class="fa fa-plus-circle"></i> Browse Files...</a>
                <br /><br /><br />
            </p>
        <?php endif; ?>

        <div class="cboth"></div>
        <div id="filesToUploadBox">

        </div>
    <?php endif; ?>

    <?php if ($this->id && is_object($notes) && ($notes->count())): ?>
        <?php foreach ($notes as $note): ?>
            <div class="note">
                <strong><?php echo $note->_username ?></strong> <small> on <?php echo $note->_note_create_date_format ?></small><br />
                <p>
                    <?php echo $note->note_text ?><br />
                    <?php if ($note->_files != ''): ?>
                        <?php
                        $_files = explode(',', $note->_files);
                        ?>
                        <strong>Attachments:</strong><br />
                        <?php foreach ($_files as $_file): ?>
                            <?php
                            $_file = explode('::', $_file);
                            $_fileName = $_file[0];
                            $_fileId = $_file[1];
                            ?>
                            <span style="float: left; margin-right: 5px;" class="<?php echo !$this->isPdf ? $this->renderPictoIcon($_fileName) : ''; ?>"></span><a href="/files/get/note/<?php echo $note->note_id ?>/<?php echo $_fileId ?>" class="" target="_blank"><?php echo $_fileName ?></a><br/>

                        <?php endforeach; ?>
                    <?php endif; ?>
                </p>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>

    <div class="cboth"></div>

    <p style="border: 0;"><strong>Reviewed and approved by <?php echo $this->rpObj->_approver_name ?><!-- on March 10th, 2014 --></strong></p>
    <?php if ($this->writable): ?>
        <p style="border: 0;">
            <label>Initials</label>
            <input type="text" name="rp_initials_approver" id="rp_initials_approver" value="<?php echo $this->rpObj->rp_initials_approver ?>" />
            <ul style="display: none" id="rp_initials_approver_val"><li>Value is required and can't be empty</li></ul>
        </p>
    <?php else: ?>
        <p style="border: 0;">
            <label>Initials: <?php echo $this->rpObj->rp_initials_approver ?></label>
        </p>
    <?php endif; ?>

    <div class="cboth"></div>

    <p style="border: 0;"><strong>Agreed to and accepted by <?php echo $this->rpObj->_client_name ?><!-- on March 10th, 2014 --></strong></p>
    <?php if ($this->writable): ?>
        <p style="border: 0;">
            <label>Initials</label>
            <input type="text" name="rp_initials" id="" value="<?php echo $this->rpObj->rp_initials ?>" />
        </p>
        </p>
    <?php else: ?>
        <p style="border: 0;">
            <label>Initials: <?php echo $this->rpObj->rp_initials ?></label>
        </p>
    <?php endif; ?>

    <div class="cboth"></div>

    <div class="form-buttons">
        <?php if ($this->writable && !$this->isPdf): ?>
            <input type="submit" value="Save" class="form-button" />
            <?php if ($rpObj->rp_approver_u_id): ?>
                <input type="button" onclick="$('#requestreview').val(1); $('#formNote').submit()" value="Request Review" class="form-button" />
            <?php endif; ?>
            <input type="button" onclick="if ($('#rp_initials_approver').val() == '') $('#rp_initials_approver_val').show(); else {  $('#signedoff').val(1); $('#formNote').submit() }" value="Sign-off and Close" class="form-button" />
            <div class="fleft">or</div>
            <a href="/remediationplan/list" class="cancel">Cancel</a>
        <?php else: ?>
            <?php if (!$this->isPdf): ?>
                <div class="cboth"></div>
                <?php if (!$this->isAdmin): ?>
                    <a href="/remediationplan/list" class="form-button">Back</a>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>

        <?php if ($this->isAdmin): ?>
            <?php $deleteUrl = '/remediationplan/reopen/' . $rpObj->rp_id; ?>
            <a href="#confirmation-box-modal" onclick="$('#confirmation-box-modal h3').html('Are you sure you want to re-open this plan ?'); $('#deleteYes').attr('href', '<?php echo $deleteUrl ?>')" class="form-button confirmation-modal">Re-Open Plan</a>
            <div class="fleft">or</div>
            <a href="/remediationplan/list" class="cancel">Cancel</a>
        <?php endif; ?>
    </div>

</form>


<div class="cboth"><br /></div>

<script type="text/javascript">

    var browseFilesCounter = 0;
    $(document).ready(function() {
        $('#browseFile').click(function() {
            $('#filesToUploadBox').append('<input type="file" name="notesFiles[]" id="file' + browseFilesCounter + '" />');

            $('#file' + browseFilesCounter).click();
            browseFilesCounter++;
        });

        $('.browseFileTask').click(function() {
            var noteId = $(this).attr('rel');
            $('#filesToUploadBox' + noteId).append('<input type="file" name="notesFiles[]" id="file' + noteId + browseFilesCounter + '" /><div class="cboth"></div>');

            $('#file' + noteId + browseFilesCounter).click();
            browseFilesCounter++;
        });

    });


</script>

<script type="text/javascript">

    jQuery(document).ready(function() {
        $('#rp_performed_u_id').change(function() {
            $('#rp_performed_u_id_hidden').val($(this).val());
        });

        $('#rp_approver_u_id').change(function() {
            $('#rp_approver_u_id_hidden').val($(this).val());
        });

        $('#rp_incident_date').change(function() {
            $('#rp_incident_date_hidden').val($(this).val());
        });

        $('#rp_remediation_date').change(function() {
            $('#rp_remediation_date_hidden').val($(this).val());
        });
        //form disclaimer slide out
        jQuery('.expandable').hide();
        jQuery('.attachments').toggle(
            function() {
                var idA = $(this).attr('rel');
                jQuery('#attachments' + idA).slideDown();
            }, function() {
                var idA = $(this).attr('rel');
                jQuery('#attachments' + idA).slideUp();
            }
        );

    });

</script>

<script type="text/javascript">
    jQuery(function(){
        jQuery("#rp_incident_date").mask("99/99/9999");
        jQuery("#rp_remediation_date").mask("99/99/9999");

        jQuery("#toggle-edit-1").hide();
        jQuery("#toggle-edit-show-1").toggle(function() {
            jQuery("#toggle-edit-1").show();
            jQuery("#toggle-edit-show-1").hide();
        }, function() {
            jQuery("#toggle-edit-show-1").show();
            jQuery("#toggle-edit-1").hide();
        });

        jQuery("#toggle-edit-4").hide();
        jQuery("#toggle-edit-show-4").toggle(function() {
            jQuery("#toggle-edit-4").show();
            jQuery("#toggle-edit-show-4").hide();
        }, function() {
            jQuery("#toggle-edit-show-4").show();
            jQuery("#toggle-edit-4").hide();
        });

        jQuery("#toggle-edit-2").hide();
        jQuery("#toggle-edit-show-2").toggle(function() {
            jQuery("#toggle-edit-2").show();
            jQuery("#toggle-edit-show-2").hide();
        }, function() {
            jQuery("#toggle-edit-show-2").show();
            jQuery("#toggle-edit-2").hide();
        });
        jQuery("#toggle-edit-3").hide();
        jQuery("#toggle-edit-show-3").toggle(function() {
            jQuery("#toggle-edit-3").show();
            jQuery("#toggle-edit-show-3").hide();
        }, function() {
            jQuery("#toggle-edit-show-3").show();
            jQuery("#toggle-edit-3").hide();
        });
    });
</script>