<?php
use Assessment\Model\Assessment;
?>
<?php if (count($this->loc_rps) > 1) : ?>
<div class="tab_nav">
    <ul class="ul_tabs">
    <?php foreach ($this->loc_rps as $rp_id => $loc_name): ?>
        <li <?php echo $this->id == $rp_id ? 'class="active_tab"' : ''; ?> >
        <a href="/remediationplan/edit/<?php echo $rp_id; ?>" class="panel-tabs"><?php echo $loc_name; ?></a>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
<div class="page-title">
    <h1 class="fleft"><?php echo $this->rpObj->rp_type == Assessment::TYPE_SECURITY_RISK ? 'Security' : 'Privacy'; ?> Remediation Plan for <?php echo (!$this->isPdf) ? '<br/>' : '' ?><?php echo $this->rpObj->_client_name ?>
    <?php foreach ($this->actions as $rpa): ?>
    <?php
        if($rpa->rpa_adr_id === null){
            echo 'Additional Tasks';
        } else {
            echo $rpa->_location_name;
        }        
        break;
    ?>
    <?php endforeach; ?>
    <?php echo !$this->rpObj->rp_a_id ? ' <span class="remediationplan_imported_edit">(imported)</span>' : ''?>
    </h1>
    <?php if (!$this->isPdf): ?>
        <a href="/remediationplan/edit/<?php echo $rpObj->rp_id ?>/type/pdf" class="button" title="Download as PDF"><i class="fa fa-download"></i> PDF</a>
        <a href="/remediationplan/edit/<?php echo $rpObj->rp_id ?>/type/csv" class="button" title="Download as CSV"><i class="fa fa-download"></i> CSV</a>
    <?php endif; ?>
    <div class="cboth"></div>
</div>

<p></p>
<div class="cboth"></div>

<div class="col6" style="float: left;">
    <p><strong>STATUS:</strong><br /><span class="label selected"><?php echo \Assessment\Model\Remediationplan::$statusesNames[$rpObj->rp_status]  ?></span></p>
</div>
<div class="col5"  style="float: left;">
    <p>
        <strong>PERFORMED BY:</strong><br />
        <?php if ($this->isPdf): ?>
            <?php echo $this->rpObj->_performed_name ?>
        <?php else: ?>
            <?php if ($this->writable): ?>
                <span id="toggle-edit-show-1">
                    <?php echo $this->rpObj->_performed_name ?> &nbsp;<a href="" title="Edit"><i class="fa fa-pencil"></i></a>
                </span>
                <span id="toggle-edit-1">
                    <select id="rp_performed_u_id" id="" class="w175">
                        <option value="">Please Select</option>
                        <option value="">---</option>
                        <?php foreach ($this->contacts as $uId => $contact): ?>
                            <option <?php echo ($uId == $this->rpObj->rp_performed_u_id) ? ' SELECTED ' : '' ?> value="<?php echo $uId ?>"><?php echo $contact ?></option>
                        <?php endforeach; ?>
                    </select>
                </span>
            <?php else: ?>
                <?php echo $this->rpObj->_performed_name ?>
            <?php endif; ?>
        <?php endif; ?>
    </p>
</div>
<div class="col5"  style="float: left;">
    <p>
        <?php if ($this->writable): ?>
            <?php if ($this->rpObj->rp_parent_rp_id): ?>
                <strong>Work Plan in Process</strong>
            <?php else: ?>
                <strong>Awaiting Approval</strong>
            <?php endif; ?>
        <?php else: ?>
            <strong>APPROVED BY:</strong><br />
            <?php echo $this->rpObj->_approver_name ?>
        <?php endif; ?>
    </p>
</div>
<div class="col5"  style="float: left;">
    <p><strong>ASSESSMENT DATE:</strong><br />
        <?php if ($this->writable): ?>
            <span id="toggle-edit-show-2">
                <?php echo $this->rpObj->rp_incident_date ? $this->rpObj->_rp_incident_date_formatted : ''; ?> &nbsp;<a href="" title="Edit"><i class="fa fa-pencil"></i></a>
            </span>
            <span id="toggle-edit-2">
                <input type="text" id="rp_incident_date" name="rp_incident_date" readonly="readonly" class="w175" value="<?php echo $this->rpObj->rp_incident_date ? $this->rpObj->_rp_incident_date_formatted : '' ?>" />
            </span>
        <?php else: ?>
            <?php echo $this->rpObj->rp_incident_date ? $this->rpObj->_rp_incident_date_formatted : '' ?>
        <?php endif; ?>
    </p>
</div>
<div class="col4 last" style="float: left;">
    <p><strong>REMEDIATION PLAN DATE:</strong><br />
        <?php if ($this->writable): ?>
            <span id="toggle-edit-show-3">
            <?php echo ($this->rpObj->rp_remediation_date != '0000-00-00') ? $this->rpObj->_rp_remediation_date_formatted : '' ?> &nbsp;<a href="" title="Edit"><i class="fa fa-pencil"></i></a>
        </span>
            <span id="toggle-edit-3">
            <input type="text" id="rp_remediation_date" name="rp_remediation_date" readonly="readonly" class="w175" value="<?php echo ($this->rpObj->rp_remediation_date != '0000-00-00') ? $this->rpObj->_rp_remediation_date_formatted : '' ?>" />
        </span>
        <?php else: ?>
            <?php echo ($this->rpObj->rp_remediation_date != '0000-00-00') ? $this->rpObj->_rp_remediation_date_formatted : '' ?>
        <?php endif; ?>
</div>
<div class="cboth"></div>

<p></p>

<table cellpadding="0" cellspacing="0">
    <thead>
        <tr>
            <th>Risk score</th>
            <th>Threat</th>
            <th>Action plan</th>
            <th>Policy number</th>
            <?php $classSort = ($order_by == 'status') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>
                <a href="<?php echo $this->url('remediationplan', array('action' => 'edit', 'id' => $this->id, 'order_by' => 'status', 'order' => $urlOrder, 'roleFilter' => $roleFilter)); ?>">
                    Status <i class="fa <?php echo $classSort ?>"></i>
                </a>
            </th>

            <?php $classSort = ($order_by == 'assignee') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>
                <a href="<?php echo $this->url('remediationplan', array('action' => 'edit', 'id' => $this->id, 'order_by' => 'assignee', 'order' => $urlOrder, 'roleFilter' => $roleFilter)); ?>">
                    Assignee <i class="fa <?php echo $classSort ?>"></i>
                </a>
            </th>
            
            <?php $classSort = ($order_by == 'approver') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>
                <a href="<?php echo $this->url('remediationplan', array('action' => 'edit', 'id' => $this->id, 'order_by' => 'approver', 'order' => $urlOrder, 'roleFilter' => $roleFilter)); ?>">
                    Approver <i class="fa <?php echo $classSort ?>"></i>
                </a>
            </th>

            <?php $classSort = ($order_by == 'date') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>
                <a href="<?php echo $this->url('remediationplan', array('action' => 'edit', 'id' => $this->id, 'order_by' => 'date', 'order' => $urlOrder, 'roleFilter' => $roleFilter)); ?>">
                    Target Date <i class="fa <?php echo $classSort ?>"></i>
                </a>
            </th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
    <?php $adrId = 0; $adrChange = false; ?>
    <?php foreach ($this->actions as $rpa): ?>
        <?php if ($adrId != $rpa->rpa_adr_id):
            $adrChange = true;
            if($rpa->rpa_adr_id === null){
                $adrId = 0;
                $rpa->_location_name = 'Additional Tasks';
            } else {
                $adrId = $rpa->rpa_adr_id;
            }
        else:
            $adrChange = false;
        endif; ?>

        <?php if ($adrChange): ?>
            <tr>
                <td colspan="20">
                    <h2><?php if ($this->isPdf): ?><span style="font-size: 13px; font-weight: normal">Location:<?php endif; ?></span><br/><?php echo $rpa->_location_name ?></h2>
                </td>
            </tr>
        <?php endif; ?>
        <?php $notesTaskAtt = $this->noteTable->getNotes($rpa->rpa_id, \Note\Model\Note::NOTE_RPA, 0, 'file'); ?>
        <?php $notesTaskAssessments = $this->noteTable->getNotesForRemedTask($rpa->rpa_id, $adrId, 'file'); ?>
        <?php $notesTaskAttText = $this->noteTable->getNotes($rpa->rpa_id, \Note\Model\Note::NOTE_RPA, 0, 'text'); ?>
        <?php $notesTaskAssessmentsText = $this->noteTable->getNotesForRemedTask($rpa->rpa_id, $adrId, 'text'); ?>

        <tr>
            <td class="tdSmall"><?php echo \Assessment\Model\Remediationplanaction::$levelsNames[$rpa->rpa_risk_level] ?></td>
            <td class="tdSmall">
                <?php $rpaThreat = str_replace('Â', '', $rpa->rpa_threat); ?>
                <?php echo str_replace('Â', '', $rpaThreat); ?>
            </td>
            <td class="tdSmall"><?php echo $rpa->rpa_action_plan ?></td>
            <td class="tdSmall"><?php echo $rpa->rpa_policy ?></td>
            <td class="acenter"><?php echo \Assessment\Model\Remediationplanaction::$statusesNames[$rpa->rpa_status] ?></td>
            <td><?php echo $rpa->_contact_name ?></td>
            <td><?php echo $rpa->_approver_name ?></td>
            <td><?php echo $rpa->_rpa_target_date_formatted ?></td>
            <td class="aright nowrap">
                <a href="/remediationplan/edittask/<?php echo $rpa->rpa_id ?>/rpId/<?php echo $rpObj->rp_id ?>" id="edittask<?php echo $rpa->rpa_id ?>" class="fancybox" title="Edit"><i class="fa fa-pencil"></i></a> &nbsp;
                <?php /* <a href="/remediationplan/planemail/<?php echo $rpa->rpa_id ?>/rpId/<?php echo $rpObj->rp_id ?>" class="fancybox" title="Email Assignee"><i class="fa fa-envelope"></i></a> &nbsp; */ ?>
                <?php if ($this->writable): ?>
                    <?php $deleteUrl = '/remediationplan/deletetask/' . $rpa->rpa_id . '/rpId/' . $rpObj->rp_id; ?>
                    <a href="#confirmation-box-modal" onclick="$('#deleteYes').attr('href', '<?php echo $deleteUrl ?>')" class="confirmation-modal i-delete" title="Delete"><i class="fa fa-trash-o"></i></a>
                <?php endif; ?>
                <?php if ($notesTaskAtt->count() || ($notesTaskAssessments && $notesTaskAssessments->count())): ?>
                    <a style="margin-left: 10px;" href="" class="attachments" rel="<?php echo $rpa->rpa_id ?>" title="View Attachments"><i class="fa fa-paperclip"></i></a>
                <?php endif; ?>
                <?php if ($notesTaskAttText->count() || ($notesTaskAssessments && $notesTaskAssessmentsText->count())): ?>
                    <a style="margin-left: 10px;" href="" class="notes" rel="<?php echo $rpa->rpa_id ?>" title="View Notes"><i class="fa fa-file-text-o fa-1"></i></a>
                <?php endif; ?>
            </td>
        </tr>

        <?php //if (!$this->writable): ?>

            <tr class="expandable" id="notes<?php echo $rpa->rpa_id ?>">
                <td>&nbsp;</td>
                    <?php $colspan = 2; ?>
                    <?php foreach (array('Task notes' => $notesTaskAttText, 'Questions notes' => $notesTaskAssessmentsText) as $keyAtt => $notesTask): ?>
                        <td colspan="<?php echo $colspan ?>">
                            <?php if (is_object($notesTask) && ($notesTask->count())): ?>
                                <div>
                                    <div><strong><?php echo $keyAtt ?>:</strong></div>
                                    <div>
                                        <?php $notesTask->buffer() ?>
                                        <?php foreach ($notesTask as $note): ?>
                                            <?php if ($note->note_text != ''): ?>
                                                <div><?php echo $note->note_text ?></div>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    </div>
                                </div>
                            <?php endif; ?>
                        </td>
                        <?php $colspan = 7; ?>
                    <?php endforeach; ?>
            </tr>
            
            <tr class="expandable" id="attachments<?php echo $rpa->rpa_id ?>">
                <td>&nbsp;</td>
                    <?php $colspan = 2; ?>
                    <?php foreach (array('Task attachments' => $notesTaskAtt, 'Questions attachments' => $notesTaskAssessments) as $keyAtt => $notesTask): ?>
                        <td colspan="<?php echo $colspan ?>">
                            <?php if (is_object($notesTask) && ($notesTask->count())): ?>
                                <div>
                                    <div><strong><?php echo $keyAtt ?>:</strong></div>
                                    <div>
                                        <?php foreach ($notesTask as $note): ?>
                                            <?php if ($note->_files != ''): ?>
                                                <?php
                                                $_files = explode(',', $note->_files);
                                                ?>
                                                <?php foreach ($_files as $_file): ?>
                                                    <?php
                                                    $_file = explode('::', $_file);
                                                    $_fileName = $_file[0];
                                                    $_fileId = $_file[1];
                                                    ?>
                                                    <?php if (!$this->isPdf): ?>
                                                        <?php if ($note->_files != ''): ?>
                                                            <span style="float: left; margin-right: 5px;" class="<?php echo $this->renderPictoIcon($_fileName); ?>"></span><a href="http://<?php echo $_SERVER['HTTP_HOST'] ?>/files/get/note/<?php echo $note->note_id ?>/<?php echo $_fileId ?>" class="" target="_blank"><?php echo $_fileName ?></a><br/>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    </div>
                                </div>
                            <?php endif; ?>
                        </td>
                        <?php $colspan = 7; ?>
                    <?php endforeach; ?>
            </tr>
        <?php //endif; ?>
    <?php endforeach; ?>
    </tbody>
</table>

<?php if ($this->writable && !$this->isPdf): ?>
    <p><a href="/remediationplan/edittask/0/rpId/<?php echo $rpObj->rp_id ?>" class="fancybox button fright"><i class="fa fa-plus-circle"></i> Add</a></p>
<?php endif; ?>

<form action="/remediationplan/edit/<?php echo $this->id ?>" name="" style="width: 600px;" id="formNote" method="POST" enctype="multipart/form-data" class="col2" >
    <input id="rp_performed_u_id_hidden" name="rp_performed_u_id" type="hidden" value="<?php echo $this->rpObj->rp_performed_u_id ?>" />
    <input id="rp_incident_date_hidden" name="rp_incident_date" type="hidden" value="<?php echo ($this->rpObj->rp_incident_date != '0000-00-00') ? $this->rpObj->_rp_incident_date_formatted : '' ?>" />
    <input id="rp_remediation_date_hidden" name="rp_remediation_date" type="hidden" value="<?php echo ($this->rpObj->rp_remediation_date != '0000-00-00') ? $this->rpObj->_rp_remediation_date_formatted : '' ?>" />

    <?php if ($this->writable && !$this->isPdf): ?>
        <input id="signedoff" type="hidden" name="signedoff" value="0" />
        <input id="requestreview" type="hidden" name="requestreview" value="0" />
        <input type="hidden" name="noteform" value="1" />
        <?php
        $fn = $formNote->get('note_id');
        echo $this->formHidden($fn);
        ?>
        <?php
        $fn = $formNote->get('note_item_type');
        $fn->setValue(\Note\Model\Note::NOTE_RP);
        echo $this->formHidden($fn);
        ?>
        <?php
        $fn = $formNote->get('note_item_id');
        $fn->setValue($this->id);
        echo $this->formHidden($fn);
        ?>

        <p style="border: 0;">
            <strong style="line-height: 30px;">Notes</strong><br />
            <?php
            $fn = $formNote->get('note_text');
            echo $this->formTextarea($fn->setAttributes(array('style' => 'width: 570px;')));
            echo $this->formElementErrors($fn);
            ?>

        </p>
        <?php if (!$this->isPdf): ?>
            <p style="border: 0;">
                <strong style="line-height: 30px;">Additional Attachments</strong><br />
                <a id="browseFile" href="javascript:" class="button"><i class="fa fa-plus-circle"></i> Browse Files...</a>
                <br /><br /><br />
            </p>
        <?php endif; ?>

        <div class="cboth"></div>
        <div id="filesToUploadBox">

        </div>
    <?php endif; ?>

    <?php if ($this->id && is_object($notes) && ($notes->count())): ?>
        <?php foreach ($notes as $note): ?>
            <div class="note">
                <strong><?php echo $note->_username ?></strong> <small> on <?php echo $note->_note_create_date_format ?></small><br />
                <p>
                    <?php echo $note->note_text ?><br />
                    <?php if ($note->_files != ''): ?>
                        <?php
                        $_files = explode(',', $note->_files);
                        ?>
                        <strong>Attachments:</strong><br />
                        <?php foreach ($_files as $_file): ?>
                            <?php
                            $_file = explode('::', $_file);
                            $_fileName = $_file[0];
                            $_fileId = $_file[1];
                            ?>
                            <span style="float: left; margin-right: 5px;" class="<?php echo !$this->isPdf ? $this->renderPictoIcon($_fileName) : ''; ?>"></span><a href="/files/get/note/<?php echo $note->note_id ?>/<?php echo $_fileId ?>" class="" target="_blank"><?php echo $_fileName ?></a><br/>

                        <?php endforeach; ?>
                    <?php endif; ?>
                </p>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>

    <div class="cboth"></div>

    <?php if ($this->writable && !$this->isPdf): ?>
        <p style="border: 0;"><label style="width:195px"><strong>Reviewed and approved by </strong></label>
            <select name="rp_approver_u_id" id="rp_approver_u_id" id="" class="w175 valid_input form-control required">
                <option value="">Please Select</option>
                <option value="">---</option>
                <?php foreach ($this->approverAccepter as $contact): ?>
                    <option <?php echo ($contact->_u_id == $this->rpObj->rp_approver_u_id || (!$this->rpObj->rp_approver_u_id && in_array(9, $contact->_ar_id))) ? ' SELECTED ' : '' ?> value="<?php echo $contact->_u_id ?>"><?php echo $contact->_u_name ?></option>
                <?php endforeach; ?>
            </select>
        </p>
        <p style="border: 0;">
            <label>Initials</label>
            <input type="text" name="rp_initials_approver" class="valid_input form-control required" id="rp_initials_approver" value="<?php echo $this->rpObj->rp_initials_approver ?>" />
        </p>
        <p style="border: 0;">
            <label>Date: </label>
            <input type="text" name="rp_approved_date" readonly="readonly" class="valid_input form-control required" id="rp_approved_date" value="<?php echo $this->rpObj->rp_approved_date ? $this->rpObj->_rp_approved_date_formatted : date('m/d/Y')?>">
        </p>
    <?php else: ?>
        <p style="border: 0;"><strong>Reviewed and approved by <?php echo $this->rpObj->_approver_name?></strong></p>
        <p style="border: 0;">
            <label>Initials: <?php echo $this->rpObj->rp_initials_approver ?></label>
        </p>
        <p style="border: 0;">
            <label>Date: <?php echo $this->rpObj->rp_approved_date ? $this->rpObj->_rp_approved_date_formatted : ''?></label>
        </p>
    <?php endif; ?>

    <div class="cboth"></div>

    <?php if ($this->writable && !$this->isPdf): ?>
        <p style="border: 0;"><label style="width:195px"><strong>Agreed to and accepted by</strong></label>
            <select name="rp_accepter_u_id" id="rp_accepter_u_id" id="" class="w175 valid_input form-control required">
                <option value="">Please Select</option>
                <option value="">---</option>
                <?php foreach ($this->approverAccepter as $contact): ?>
                    <option <?php echo ($contact->_u_id == $this->rpObj->rp_accepter_u_id || (!$this->rpObj->rp_accepter_u_id && in_array(10, $contact->_ar_id))) ? ' SELECTED ' : '' ?> value="<?php echo $contact->_u_id ?>"><?php echo $contact->_u_name ?></option>
                <?php endforeach; ?>
            </select>
        </p>
        <p style="border: 0;">
            <label>Initials</label>
            <input type="text" name="rp_initials" id="" class="valid_input form-control required" value="<?php echo $this->rpObj->rp_initials ?>" />
        </p>
        <p style="border: 0;">
            <label>Date: </label>
            <input type="text" name="rp_accepted_date" readonly="readonly" class="valid_input form-control required" id="rp_accepted_date" value="<?php echo $this->rpObj->rp_accepted_date ? $this->rpObj->_rp_accepted_date_formatted : date('m/d/Y')?>">
        </p>
    <?php else: ?>
        <p style="border: 0;"><strong>Agreed to and accepted by <?php echo $this->rpObj->_accepter_name?></strong></p>
        <p style="border: 0;">
            <label>Initials: <?php echo $this->rpObj->rp_initials ?></label>
        </p>
        <p style="border: 0;">
            <label>Date: <?php echo $this->rpObj->rp_accepted_date ? $this->rpObj->_rp_accepted_date_formatted : '' ?></label>
        </p>

    <?php endif; ?>

    <div class="cboth"></div>

    <div class="form-buttons">
        <?php if ($this->writable && !$this->isPdf): ?>
            <input type="submit" name="save_button" id="save_button" value="Save" class="form-button" />
            <input type="submit" name="save_and_copy_button" id="save_and_copy_button" value="Save & Copy" class="form-button" />
            <?php if ($rpObj->rp_approver_u_id): ?>
                <input type="button" id="requestreview_button" value="Request Review" class="form-button" />
            <?php endif; ?>
            <input type="button" id="signedoff_button" value="Sign-off and Close" class="form-button" />
            <div class="fleft">or</div>
            <a href="/remediationplan/list" class="cancel">Cancel</a>
        <?php else: ?>
            <?php if (!$this->isPdf): ?>
                <div class="cboth"></div>
                <?php if (!$this->isAdmin): ?>
                    <a href="/remediationplan/list" class="form-button">Back</a>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>

        <?php if ($this->isAdmin && $rpObj->rp_status != \Assessment\Model\Remediationplan::STATUS_OPEN): ?>
            <?php $deleteUrl = '/remediationplan/reopen/' . $rpObj->rp_id; ?>
            <a href="#confirmation-box-modal" onclick="$('#confirmation-box-modal h3').html('Are you sure you want to re-open this plan ?'); $('#deleteYes').attr('href', '<?php echo $deleteUrl ?>')" class="form-button confirmation-modal">Re-Open Plan</a>
            <div class="fleft">or</div>
            <a href="/remediationplan/list" class="cancel">Cancel</a>
        <?php endif; ?>
    </div>

</form>


<div class="cboth"><br /></div>

<script type="text/javascript">

    var browseFilesCounter = 0;
    jQuery(document).ready(function() {
        $('#browseFile').click(function() {
            $('#filesToUploadBox').append('<input type="file" name="notesFiles[]" id="file' + browseFilesCounter + '" />');

            $('#file' + browseFilesCounter).click();
            browseFilesCounter++;
        });

        $('.browseFileTask').click(function() {
            var noteId = $(this).attr('rel');
            $('#filesToUploadBox' + noteId).append('<input type="file" name="notesFiles[]" id="file' + noteId + browseFilesCounter + '" /><div class="cboth"></div>');

            $('#file' + noteId + browseFilesCounter).click();
            browseFilesCounter++;
        });
        
        openEditTask();
    });
    
    function openEditTask()
    {
        var get = parseGET();
        if(get['edittask'] != undefined)
        {
            $('#edittask' + get['edittask']).click();
        }
    }
    
    function parseGET() 
    {
      var tmp = new Array();
      var tmp2 = new Array();
      var get = new Array();
      var url = location.search;

      if(url != '') {

        tmp = (url.substr(1)).split('&');

        for(var i=0; i < tmp.length; i++) {
          tmp2 = tmp[i].split('=');
          get[tmp2[0]] = tmp2[1];
        }
      }
        return get;
    }


</script>

<script type="text/javascript">

    jQuery(document).ready(function() {
        $('#rp_performed_u_id').change(function() {
            $('#rp_performed_u_id_hidden').val($(this).val());
        });

        $('#rp_incident_date').change(function() {
            $('#rp_incident_date_hidden').val($(this).val());
        });

        $('#rp_remediation_date').change(function() {
            $('#rp_remediation_date_hidden').val($(this).val());
        });
        //form disclaimer slide out
        jQuery('.expandable').hide();
        jQuery('.attachments, .notes').click(function(e) {
            e.preventDefault();
            var $this = $(this);
            var idA = $this.attr('rel');
            if($this.hasClass('notes')) {
                if(jQuery('#notes' + idA).is(':visible')) {
                    jQuery('#notes' + idA).slideUp();
                } else {
                    jQuery('#attachments' + idA).slideUp(function(){jQuery('#notes' + idA).delay(600).slideDown();});
                }
            } else {
                if(jQuery('#attachments' + idA).is(':visible')) {
                    jQuery('#attachments' + idA).slideUp();
                } else {
                    jQuery('#notes' + idA).slideUp(function(){jQuery('#attachments' + idA).delay(600).slideDown();});
                }
            }
            
        });
        
        $('#save_button, #save_and_copy_button').click(function() {
            $('#signedoff, #requestreview').val('');
            $('.valid_input').removeClass('required');
            $('#formNote').submit();
        });
        
        $('#requestreview_button').click(function() {
            $('#signedoff').val('');
            $('#requestreview').val(1);
            $('.valid_input').removeClass('required');
            $('#formNote').submit();
        });
        
        $('#signedoff_button').click(function() {
            $('#requestreview').val('');
            $('#signedoff').val(1);
            $('.valid_input').addClass('required');
            $('#formNote').submit();
        });
        
        $('#formNote').submit(function() {
            
            var isValid = $('#formNote').valid();

            if (isValid) {
                return true;
            }
            return false;
        });
    });

</script>

<script type="text/javascript">
    jQuery(function(){
        $( "#rp_incident_date, #rp_remediation_date, #rp_approved_date, #rp_accepted_date" ).datepicker({dateFormat: 'mm/dd/yy'});
        
        jQuery("#toggle-edit-1").hide();
        jQuery("#toggle-edit-show-1").toggle(function() {
            jQuery("#toggle-edit-1").show();
            jQuery("#toggle-edit-show-1").hide();
        }, function() {
            jQuery("#toggle-edit-show-1").show();
            jQuery("#toggle-edit-1").hide();
        });

        jQuery("#toggle-edit-4").hide();
        jQuery("#toggle-edit-show-4").toggle(function() {
            jQuery("#toggle-edit-4").show();
            jQuery("#toggle-edit-show-4").hide();
        }, function() {
            jQuery("#toggle-edit-show-4").show();
            jQuery("#toggle-edit-4").hide();
        });

        jQuery("#toggle-edit-2").hide();
        jQuery("#toggle-edit-show-2").toggle(function() {
            jQuery("#toggle-edit-2").show();
            jQuery("#toggle-edit-show-2").hide();
        }, function() {
            jQuery("#toggle-edit-show-2").show();
            jQuery("#toggle-edit-2").hide();
        });
        jQuery("#toggle-edit-3").hide();
        jQuery("#toggle-edit-show-3").toggle(function() {
            jQuery("#toggle-edit-3").show();
            jQuery("#toggle-edit-show-3").hide();
        }, function() {
            jQuery("#toggle-edit-show-3").show();
            jQuery("#toggle-edit-3").hide();
        });
    });
</script>