<div class="page-title">
    <h1 class="fleft">Import Remediation Plan From CSV</h1>
    <div class="cboth"></div>
</div>

<div class="col-left">
    <form action="/remediationplan/import" name="" style="width: 600px;" id="importForm" method="POST" enctype="multipart/form-data" class="col2" >

        <p>
            <?php 
                $fn = $form->get('rp_c_id');
                echo $this->formLabel($fn);
                echo $this->formSelect($fn->setAttributes(array('id'=>'company', 'class'=>'form-control required')));
                echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <?php 
                $fn = $form->get('rp_performed_u_id');
                echo $this->formLabel($fn);
                echo $this->formSelect($fn->setAttributes(array('id' => 'rp_performed_u_id', 'class'=>'form-control required')));
                echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <?php
                $fn = $form->get('rp_remediation_date');
                echo $this->formLabel($fn);
                echo $this->formInput($fn->setAttributes(array('class'=>'form-control required', 'id' => 'rp_remediation_date', 'readonly' => 'readonly')));
                echo $this->formElementErrors($fn);
            ?>
        </p>

        <p style="border: 0;">
            <strong style="line-height: 30px;">CSV File</strong><br />
            <a id="browseFile" href="javascript:" class="button importRemediationBtn"><i class="fa fa-plus-circle"></i> Browse Files...</a>
        </p>

        <?php if($errorMsg) :?>
            <p id="errorWrap" style="padding: 0;border-top: 0;">
                <label style="padding:0" generated="true" class="error"><?php echo $errorMsg ?></label>
            </p>
        <?php endif; ?>

        <div class="cboth"></div>
        <div id="filesToUploadBox">

        </div>

        <div class="cboth"></div>

        <div class="form-buttons">
            <input type="submit" name="import" value="Import" class="form-button" />
        </div>

    <?php echo $this->form()->closeTag() ?>
</div>

<div class="cboth"><br /></div>

<script type="text/javascript">
$(document).ready(function() {
    // $('#importForm').validate();

    $( "#rp_remediation_date" ).datepicker({dateFormat: 'mm/dd/yy'});

    var browseFilesCounter = 0;
    jQuery(document).ready(function() {
        $('#browseFile').click(function() {
            $('#errorWrap').remove();
            if(browseFilesCounter == 0) {
                browseFilesCounter++;
                $('#filesToUploadBox').append('<input type="file" class="remediationCsvFile" name="files[]" id="file' + browseFilesCounter + '" />');
            }

            $('#file' + browseFilesCounter).click();
        });
    });

    $("#company").change(function(){
        getCompanyUsers();
    });

    function getCompanyUsers()
    {
        var cId = $("#company option:selected").val();
        
        if(cId != undefined && cId != '') {
            $.ajax({
                type:"GET",
                url:"/remediationplan/getcompanyusers/" + cId,
                success: function(data){
                    var html = '<option value="">Please Select</option>';
                    $.each(data, function(index, value) {
                        html += '<option value="' + value.u_id + '">' + value.u_firstname + ' ' + value.u_lastname + '</option>';
                    });
                    $('#rp_performed_u_id').html(html);
                }
            });
        }
    }

    if($("#rp_performed_u_id option:selected").val() == '') {
        // getCompanyUsers();
    }
});
</script>