<?php
$urlOrder = $order == 'ASC' ? 'DESC' : 'ASC';
$authService = new \Zend\Authentication\AuthenticationService();
$authService->setStorage(new \SanAuth\Model\MyAuthStorage('hipaa'));
$identity = $authService->getIdentity();
$isClientRole = $identity['u_role_id'] == 5 ? 1 : 0;
?>

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>


<div class="page-title">
    <h1 class="fleft">Remediation Plans</h1>

    <?php if (in_array($identity['u_role_id'], array(\Admin\Model\User::ROLE_ADMIN, \Admin\Model\User::ROLE_CONSULTANT, \Admin\Model\User::ROLE_SENIOR_CONSULTANT)) || ($identity['u_role_id'] == \Admin\Model\User::ROLE_CLIENT && $identity['u_company_id_admin'])): ?>
        <a href="/remediationplan/import" class="button"><i class="fa fa-clipboard"></i> Import Remediation Plan</a>
    <?php endif; ?>
    <div class="cboth"></div>
</div>

<p></p>

<table id="remediation-plan-list-table" cellpadding="0" cellspacing="0">
    <thead>
        <tr>
            <th>ID</th>

            <?php if (!$isClientRole): ?>
                <th>Client</th>
            <?php endif; ?>

            <th>Status</th>
            <th>Type</th>
            <th>Date</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php $postFix = ''; $isVersion = false; $counterVersion = 0; $paddingVersion = 0; $rowIdParent = ''; $isParentActive = false; $lastVersionIndex = 0;
        foreach ($this->res as $rps):
            if (count($rps) > 1) {
                $multiple = true;
            } else {
                $multiple = false;
            }
        foreach ($rps as $key => $rp): ?>
            <?php
            if (!$rp->rp_parent_rp_id):
                if ($rp->rp_type == 2):
                    $rowId = $rp->rp_security_rp_id;
                    if (!$rowId):
                        $rowId = $rp->rp_id;
                    endif;
                else:
                    $rowId = $rp->rp_id;
                endif;
                $rowIdParent = $rp->rp_id;
                if ($isVersion):
                    $counterVersion = 0;
                endif;
                $paddingVersion = 0;
                $isVersion = false;
                $isParentActive = true;
                $lastVersionIndex = $rp->rp_id;
            else:
                if ($lastVersionIndex != $rp->rp_version_index):
                    $lastVersionIndex = $rp->rp_version_index;
                    $isParentActive = false;
                endif;

                $counterVersion++;
                if (!$isParentActive):
                    $isParentActive = true;
                    $counterVersion = 0;
                    $isVersion = false;
                else:
                    $isVersion = true;
                endif;

                $paddingVersion = $counterVersion * 20;

                if ($rp->rp_type == 2):
                    $rowId = $rp->rp_security_rp_id . '-' . $rp->rp_version_index_item;
                    if (!$rp->rp_security_rp_id):
                        $rowId = $rp->rp_id . '-' . $rp->rp_version_index_item;
                    endif;
                else:
                    $rowId = $rp->rp_version_index . '-' . $rp->rp_version_index_item;
                endif;
            endif;
            $postFix = '-S';
            if ($rp->rp_type == 2):
                $postFix = '-P';
            endif;
            $classBold = '';
            if ($rp->rp_status == 10):
                $classBold = ' bold ';
            endif;
            $client_name = '';
            if ($multiple) {
                $paddingVersion += 20;
                if ($rp->_location_name) {
                    $client_name = $rp->_location_name;
                } else {
                    $client_name = $rp->_client_name;
                }                
            } else {
                $client_name = $rp->_client_name;
                if ($rp->_location_name) {
                    $client_name .= ' - ' . $rp->_location_name;
                }
            }
            ?>
            <?php if ($multiple && !$key) : ?>
            <tr>
                <td></td>
                <td style="padding-left: 0px" ><a href="javascript:void(0)" class="multiple-locs" data-ass_id="<?php echo $rp->rp_a_id ?>"><?php echo stripslashes($rp->_client_name) ?></a></td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <?php endif; ?>
            <tr <?php if ($multiple) : ?>class="assess-<?php echo $rp->rp_a_id ?>" <?php endif; ?> >
                <td><?php echo $rowId ?><?php echo $postFix ?></td>
                <?php if (!$isClientRole): ?>
                    <td class="<?php echo $classBold ?>" style="padding-left: <?php echo $paddingVersion ?>px"><?php if ($isVersion): ?><i class="fa fa-code-fork"></i> &nbsp; <?php endif ?><a href="/remediationplan/summary/<?php echo $rp->rp_id ?>"><?php echo $client_name; ?><?php echo !$rp->rp_a_id ? ' <span class="remediationplan_imported_list">(imported)</span>' : ''?></a></td>
                <?php endif; ?>
                <td class="<?php echo $classBold ?>"><?php echo \Assessment\Model\Remediationplan::$statusesNames[$rp->rp_status]  ?></td>
                <td class="<?php echo $classBold ?>"><?php echo \Assessment\Model\Assessment::$typesNames[$rp->rp_type] ?></td>
                <td class="<?php echo $classBold ?>"><?php echo $rp->rp_incident_date ? $this->formatDateA($rp->rp_incident_date) : '-'?></td>
                <td style="white-space: nowrap;" class="aright <?php echo $classBold ?>">
                    <?php if ($rp->rp_status != \Assessment\Model\Remediationplan::STATUS_CLOSED) : ?>
                    <a class="<?php echo $classBold ?>" href="/remediationplan/summary/<?php echo $rp->rp_id ?>" title="Edit"><i class="fa fa-pencil"></i></a> &nbsp;
                    <?php endif; ?>
                    <?php if (!$isClientRole): ?>
                        <?php if ($rp->rp_active): ?>
                            <?php $deleteUrl = '/remediationplan/delete/' . $rp->rp_id; ?>
                            <a href="#confirmation-box-modal" onclick="$('#deleteYes').attr('href', '<?php echo $deleteUrl ?>')" class="confirmation-modal i-delete"><i class="fa fa-trash-o"></i></a>
                        <?php elseif ($identity['u_role_id'] == \Admin\Model\User::ROLE_ADMIN): ?>
                            <a href="/remediationplan/unarchive/<?php echo $rp->rp_id ?>" class="">Unarchive</a>
                        <?php endif; ?>

                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        <?php endforeach; ?>
    </tbody>
</table>

<?php //echo $this->paginationControl(
//    $this->paginator,
//    'sliding',
//    array('partial/paginator.phtml', 'Remediationplan'),
//    array('route' => 'list', 'order_by' => $order_by, 'order' => $order, 'page' => $page, 'roleFilter' => $roleFilter, 'role' => 1, 'controller' => 'remediationplan', 'action' => 'list')
//);
//?>

<div class="cboth"><br /></div>

<script type="text/javascript">
    jQuery(document).ready(function() {
        $('.multiple-locs').click(function() {
            $(this).closest('tr').siblings('tr.assess-' + $(this).data('ass_id')).toggle();

        });
    });

    $(document).ready( function () {
        $('#remediation-plan-list-table').DataTable(
            {
                "columnDefs": [
                    { "orderable": false, "targets": 5 }
                ]
            }
        );
        $('.dataTables_filter input[type="search"]').
        css({'width':'95%','display':'inline-block'});
    } );

</script>