<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head profile="http://gmpg.org/xfn/11">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

    <title>HIPAA Suite - Application Wireframes v2.0</title>

    <script type="text/javascript" src="//use.typekit.net/znb8skn.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>

    <link rel="stylesheet" href="/css/modals.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="/css/font-awesome.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="/css/jquery-ui.min.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="/css/jquery-ui.structure.min.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="/css/jquery-ui.theme.min.css" type="text/css" media="screen" />
    <!--<link rel="stylesheet" href="css/responsive.css" type="text/css" media="screen" />-->

    <!--<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;" />-->

    <!--<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
    <script type="text/javascript" src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.10.0/jquery.validate.min.js"></script>-->
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/js/jquery.validate.min.js"></script>
    <script type="text/javascript" src="/js/jquery.fancybox.pack.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function() {

            /*jQuery('#click5-newsletter').validate({
             errorPlacement: function(error, element) {}
             });*/

        });
    </script>

</head>

<style type="text/css">
    #statuses label { width: auto; }
</style>

<body>

<?php if ($added): ?>
    <script type="text/javascript">
        window.parent.location.href = '/remediationplan/<?php echo $type ?>/<?php echo $this->rpId ?>';
        parent.jQuery.fancybox.close();
    </script>
<?php endif; ?>

<div id="modal">

    <h1><?php if (!$this->id): ?>Add<?php else: ?>Edit<?php endif; ?> Assignment</h1>

    <div id="wrap">

        <form action="/remediationplan/edittask/<?php echo $this->id ?>/rpId/<?php echo $this->rpId ?>/type/<?php echo $type ?>" name="" id="formTask" method="POST" enctype="multipart/form-data" class="col2" >
            <?php
            $fn = $formTask->get('rpa_id');
            echo $this->formHidden($fn);
            ?>

            <?php
            $fn = $formTask->get('rpa_rp_id');
            $fn->setValue($this->rpId);
            echo $this->formHidden($fn);
            ?>

            <p>
                <?php
                $fn = $formTask->get('rpa_risk_level');
                echo $this->formLabel($fn);
                echo $this->formSelect($fn);
                echo $this->formElementErrors($fn);
                ?>
            </p>


            <p>
                <?php
                $fn = $formTask->get('rpa_threat');
                echo $this->formLabel($fn);
                if ($this->writable):
                    echo $this->formTextarea($fn);
                    echo $this->formElementErrors($fn);
                else:
                    echo '<span style="width: 450px; float: left">' . ($this->rpaObj ? $this->rpaObj->rpa_threat : '') . '</span>';
                endif;
                ?>
            </p>
            <p>
                <?php
                $fn = $formTask->get('rpa_action_plan');
                echo $this->formLabel($fn);
                if ($this->writable):
                    echo $this->formTextarea($fn);
                    echo $this->formElementErrors($fn);
                else:
                    echo '<span style="width: 450px; float: left">' . ($this->rpaObj ? $this->rpaObj->rpa_action_plan : '') . '</span>';
                endif;
                ?>
            </p>

            <p>
                <?php
                $fn = $formTask->get('rpa_policy');
                echo $this->formLabel($fn);
                echo $this->formInput($fn);
                echo $this->formElementErrors($fn);
                ?>
            </p>

            <p id="statuses">
                <?php
                $fn = $formTask->get('rpa_status');
                ?>
                <label style="width: 140px">Status</label>
                <?php echo $this->formRadio($fn->setAttributes(array('class'=>'radio'))); ?>
            </p>

            <p>
                <?php $fn = $formTask->get('rpa_contact_u_id');
                echo $this->formLabel($fn);
                echo $this->formSelect($fn);
                echo $this->formElementErrors($fn);
                ?>
            </p>

            <p>
                <?php $fn = $formTask->get('rpa_approver_u_id');
                echo $this->formLabel($fn);
                echo $this->formSelect($fn);
                echo $this->formElementErrors($fn);
                ?>
            </p>

            <p>
                <?php
                $fn = $formTask->get('rpa_target_date');
                echo $this->formLabel($fn);
                echo $this->formText($fn->setAttributes(array('id' => 'rpa_target_date', 'readonly' => 'readonly', 'value' => $this->rpaObj ? $this->rpaObj->_rpa_target_date_formatted : '')));
                echo $this->formElementErrors($fn);
                ?>
            </p>


            <p style="border: 0;">
                <strong style="line-height: 30px;">Approver Notes</strong><br />
                <?php
                $fn = $formNote->get('note_text');
                echo $this->formTextarea($fn->setAttributes(array('style' => 'width: 570px;')));
                echo $this->formElementErrors($fn);
                ?>

            </p>

            <p>
                <label>Attachments</label>
                <a id="browseFileTask" href="javascript:" class="button"><i class="fa fa-plus-circle"></i> Browse Files...</a>
            </p>

            <div class="cboth"></div>
            <div id="filesToUploadBoxTask">

            </div>

            <div class="cboth"><br /></div>

            <?php if ($this->id && is_object($notes) && ($notes->count())): ?>
                <strong>Attachments:</strong><br />
                <?php foreach ($notes as $note): ?>
                    <div class="note">
                        <strong><?php echo $note->_username ?></strong> <small> on <?php echo $note->_note_create_date_format ?></small>
                        <?php if ($note->note_text != ''): ?>
                        <?php if ($note->note_active) : ?>
                            <a title="Delete" href="/files/archive/note/<?php echo $note->note_id ?>" class="ajax-delete-link"><i class="fa fa-trash-o"></i></a>
                        <?php elseif ($this->isAdmin) : ?>
                            <a href="/files/unarchive/note/<?php echo $note->note_id ?>" class="ajax-activate-link">Unarchive</a>
                        <?php endif; ?>
                        <?php endif; ?>
                        <br />
                        <p>
                            <?php if ($note->note_text != ''): ?>
                                <?php echo $note->note_text ?>                                
                                <br />
                            <?php endif; ?>
                            <?php if ($note->_files != ''): ?>
                                <?php
                                $_files = explode(',', $note->_files);
                                ?>
                                <?php foreach ($_files as $_file): ?>
                                    <?php
                                    $_file = explode('::', $_file);
                                    $_fileName = $_file[0];
                                    $_fileId = $_file[1];
                                    $_active = $_file[2];
                                    ?>
                                    <?php if ($_active || $this->isAdmin): ?>
                                    <input type="checkbox" class="attachment_checkbox" value="<?php echo $_fileId?>" checked="checked"><span style="float: left; margin-right: 5px;" class="<?php echo $this->renderPictoIcon($_fileName); ?>"></span><a href="/files/get/note/<?php echo $note->note_id ?>/<?php echo $_fileId ?>" class="" target="_blank"><?php echo $_fileName ?></a>
                                    <?php if ($_active) : ?>
                                        <span>&nbsp;</span><a title="Delete" href="/files/archive/note/<?php echo $note->note_id ?>/<?php echo $_fileId ?>" class="ajax-delete-link"><i class="fa fa-trash-o"></i></a>
                                    <?php elseif ($this->isAdmin) : ?>
                                        <span>&nbsp;</span><a href="/files/unarchive/note/<?php echo $note->note_id ?>/<?php echo $_fileId ?>" class="ajax-activate-link">Unarchive</a>
                                    <?php endif; ?>
                                    <br/>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </p>
                    </div>
                <?php endforeach; ?>
                <div class="cboth"><br /></div>

            <?php endif; ?>

            <div class="cboth"></div>
            <div class="form-buttons">
                <input type="submit" value="Save" class="form-button" />

                <a href="javascript:" class="emailClick1 form-button"><i class="fa fa-envelope"></i> Email Assignee</a>
                <a href="javascript:" class="emailClick2 form-button"><i class="fa fa-envelope"></i> Email Approver</a>

                <div class="fleft">or</div>
                <a href="javascript:void(0);" onclick="parent.jQuery.fancybox.close();" class="cancel">Cancel</a>
            </div>

        </form>

        <div class="cboth"></div>

    </div>

</div>

<script type="text/javascript">

    var browseFilesCounter = 0;
    $(document).ready(function() {
        $('#formTask').submit(function() {
            $('#formTask textarea, #formTask input').removeAttr('disabled');
        });

        $('#browseFileTask').click(function() { 
            if(browseFilesCounter > 0) {
                var prevFile = $('#file' + (browseFilesCounter - 1)).val();
                if(prevFile == undefined || prevFile == '') {
                    $('#file' + (browseFilesCounter - 1)).click();
                    return;
                }
            }
            
            $('#filesToUploadBoxTask').append('<input type="file" name="notesFiles[]" id="file' + browseFilesCounter + '" />');

            $('#file' + browseFilesCounter).click();
            browseFilesCounter++;
        });

        $('.emailClick1').click(function() {
            $.post("/remediationplan/savetask", { values: $('#formTask').serialize() }, function(data) {
                window.location.href = '/remediationplan/remediationplanemail/<?php echo $this->id ?>/rpId/<?php echo $this->rpId ?>/add_atts/' + getAttsIds();
            });
        });

        $('.emailClick2').click(function() {
            $.post("/remediationplan/savetask", { values: $('#formTask').serialize() }, function(data) {
                window.location.href = '/remediationplan/remediationplanapproveremail/<?php echo $this->id ?>/rpId/<?php echo $this->rpId ?>/add_atts/' + getAttsIds();
            });
        });
        $( "#rpa_target_date" ).datepicker({dateFormat: 'mm/dd/yy'});
        
        function getAttsIds()
        {
            var attsId = '';
            var attsIds = [];
            
            $('.attachment_checkbox:checked').each(function() {
                attsId = parseInt($(this).val());
                if(!isNaN(attsId)) attsIds.push(attsId);
            })
            
            return attsIds.join(',');
        }

        $('body').on('click', '.ajax-delete-link', function(e) {
            e.preventDefault();
            if (confirm('Are you sure you want to delete this attachment?')) {
                $.ajax({
                    type:"POST",
                    url:$(this).prop('href'),
                    success: function(data){
                        if (data == '1') {
                            window.location.reload();
                        } else {
                            alert(data);
                        }
                    }
                });
            }
            return false;
        });

        $('body').on('click', '.ajax-activate-link', function(e) {
            e.preventDefault();
            $.ajax({
                type:"POST",
                url:$(this).prop('href'),
                success: function(data){
                    if (data == '1') {
                        window.location.reload();
                    } else {
                        alert(data);
                    }
                }
            });
            return false;
        });
    });

</script>

</body>
</html>
