<?php foreach (array('Task attachments' => $this->notesTaskAtt, 'Questions attachments' => $this->notesTaskAssessments) as $keyAtt => $notesTask): ?>
    <td colspan="2">
        <?php if (is_object($notesTask) && ($notesTask->count())): ?>
            <div>
                <div><strong><?php echo $keyAtt ?>:</strong></div>
                <div>
                    <?php foreach ($notesTask as $note): ?>
                    <div class="note">
                        <?php if ($note->_files != ''): ?>
                            <?php
                            $_files = explode(',', $note->_files);
                            ?>
                            <?php foreach ($_files as $_file): ?>
                                <?php
                                $_file = explode('::', $_file);
                                $_fileName = $_file[0];
                                $_fileId = $_file[1];
                                $_active = $_file[2];
                                ?>
                                <?php if (!$this->isPdf): ?>
                                    <?php if ($_active || $this->isAdmin): ?>
                                        <span style="float: left; margin-right: 5px;" class="<?php echo $this->renderPictoIcon($_fileName); ?>"></span><a href="/files/get/note/<?php echo $note->note_id ?>/<?php echo $_fileId ?>" class="draggable" target="_blank" data-downloadurl="application/octet-stream:<?php echo $_fileName ?>:<?= empty($_SERVER['HTTPS']) ? 'http://' : 'https://' ?><?= $_SERVER['HTTP_HOST'] ?>/files/get/note/<?php echo $note->note_id ?>/<?php echo $_fileId ?>"><?php echo $_fileName ?></a>
                                        <?php if ($_active) : ?>
                                        <span>&nbsp;</span><a title="Delete" href="#del-att-box-modal" class="confirmation-modal i-delete" onclick="$('#delAttYes').attr('href', '/files/archive/note/<?php echo $note->note_id ?>/<?php echo $_fileId ?>');"><i class="fa fa-trash-o"></i></a>
                                        <?php elseif ($this->isAdmin) : ?>
                                        <span>&nbsp;</span><a href="/files/unarchive/note/<?php echo $note->note_id ?>/<?php echo $_fileId ?>" class="ajax-link">Unarchive</a>
                                        <?php endif; ?>
                                        <br/>
                                    <?php endif; ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endif; ?>
    </td>
<?php endforeach; ?>