<?php

// within a view script
$form = $this->form;
$form->prepare();

// Assuming the "contact/process" route exists...
$form->setAttribute('action', '/securityreminder/edit');

// Set the method attribute for the form
$form->setAttribute('method', 'post');

// Render the opening tag
?>


    <div class="page-title">
        <h1 class="fleft">Add New Security Reminder</h1>
        <div class="cboth"></div>
    </div>

    <p></p>

<div class="col-left">
    <form action="/securityreminder/edit/<?php echo $this->srId ?>" method="post" enctype="multipart/form-data" name="securityreminder" id="securityreminder">
        <?php
            $fn = $form->get('sr_id');
            echo $this->formHidden($fn);
        ?>
        <?php
            $fn = $form->get('sr_active');
            echo $this->formHidden($fn);
        ?>

        <?php
            $authService = new \Zend\Authentication\AuthenticationService();
            $authService->setStorage(new \SanAuth\Model\MyAuthStorage('hipaa'));
            $identity = $authService->getIdentity();
        ?>

        <p>
            <?php
            $fn = $form->get('sr_title');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <?php
            $fn = $form->get('sr_launched_date');
            if ($this->srObj):
                $fn->setValue($this->formatDateA($this->srObj->sr_launched_date, false, true));
            endif;
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required', 'id' => 'sr_launched_date', 'readonly' => 'readonly')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
                
        <p>
            <?php
            $fn = $form->get('sr_developed_by_u_id');
            echo $this->formLabel($fn);
            echo $this->formSelect($fn->setAttributes(array('class'=>'form-control', 'id'=>'sr_developed_by_u_id')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        
        <p>
            <?php $fn = $form->get('sr_dt_id');
            echo $this->formLabel($fn);
            echo $this->formSelect($fn->setAttributes(array('id'=>'type', 'class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <strong style="line-height: 30px;">Copy of Materials</strong><br />
            <a id="browseFile_materials" href="javascript:" class="button"><i class="fa fa-plus-circle"></i> Browse Files...</a>
            <br /><br /><br />
        </p>

        <div class="cboth"></div>
        <div id="filesToUploadBox_materials">

        </div>
        
        <div class="cboth"></div>

        <?php if ($this->srId && is_object($copyOfMaterials) && ($copyOfMaterials->count())): ?>
            <?php foreach ($copyOfMaterials as $note): ?>
                <div class="note">
                    <strong><?php echo $note->_username ?></strong> <small> on <?php echo $note->_note_create_date_format ?></small><br />
                    <p>
                        <?php echo $note->note_text ?><br />
                        <?php if ($note->_files != ''): ?>
                            <?php
                            $_files = explode(',', $note->_files);
                            ?>
                            <strong>Copy of Materials:</strong><br />
                            <?php foreach ($_files as $_file): ?>
                                <?php
                                $_file = explode('::', $_file);
                                $_fileName = $_file[0];
                                $_fileId = $_file[1];
                                ?>
                                <span style="float: left; margin-right: 5px;" class="''?>"></span><a href="/files/get/note/<?php echo $note->note_id ?>/<?php echo $_fileId ?>" class="" target="_blank"><?php echo $_fileName ?></a><span>&nbsp;</span><a href="/files/delete/note/<?php echo $note->note_id ?>/<?php echo $_fileId ?>" class="remove-uploaded-materials">X</a><br/>

                            <?php endforeach; ?>
                        <?php endif; ?>
                    </p>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
        <div class="cboth"></div>

        <p>
            <strong style="line-height: 30px;">Comments</strong><br />
            <?php
            $fn = $formNote->get('note_text');
            echo $this->formTextarea($fn->setAttributes(array('style' => 'width: 450px;')));
            echo $this->formElementErrors($fn);
            ?>

        </p>
        <p style="border: 0;">
            <strong style="line-height: 30px;">Upload Reports</strong><br />
            <a id="browseFile_comments" href="javascript:" class="button"><i class="fa fa-plus-circle"></i> Browse Files...</a>
            <br /><br /><br />
        </p>

        <div class="cboth"></div>
        <div id="filesToUploadBox_comments">

        </div>
        
        <div class="cboth"></div>
        
        <?php if ($this->srId && is_object($comments) && ($comments->count())): ?>
            <?php foreach ($comments as $note): ?>
                <div class="note">
                    <strong><?php echo $note->_username ?></strong> <small> on <?php echo $note->_note_create_date_format ?></small><br />
                        <?php if ($note->note_text != ''): ?>
                            <strong>Comments:</strong><br />
                            <?php echo $note->note_text ?><br />
                        <?php endif; ?>
                        <?php if ($note->_files != ''): ?>
                            <?php
                            $_files = explode(',', $note->_files);
                            ?>
                            <strong>Reports:</strong><br />
                            <?php foreach ($_files as $_file): ?>
                                <?php
                                $_file = explode('::', $_file);
                                $_fileName = $_file[0];
                                $_fileId = $_file[1];
                                ?>
                                <span style="float: left; margin-right: 5px;" class="''?>"></span><a href="/files/get/note/<?php echo $note->note_id ?>/<?php echo $_fileId ?>" class="" target="_blank"><?php echo $_fileName ?></a><span>&nbsp;</span><a href="/files/delete/note/<?php echo $note->note_id ?>/<?php echo $_fileId ?>" class="remove-uploaded-materials">X</a><br/>

                            <?php endforeach; ?>
                        <?php endif; ?>
                    </p>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
        
        <div class="cboth"></div>
        
        <div class="form-buttons">
            <input type="submit" value="Save" class="form-button" />
            <div class="fleft">or</div>
            <a href="/securityreminder/list" class="cancel">Cancel</a>
        </div>

    <?php echo $this->form()->closeTag() ?>
</div>

<div class="cboth"><br /></div>


<script type="text/javascript">
    jQuery(function() {
        $('#securityreminder').validate();

        var browseFilesCounter = {'attendees':0, 'training':0, 'comments':0};
        
        $(document).ready(function() {
            $('a[id^=browseFile_]').click(function() {
                var type  = $(this).attr('id').split('_');
                var count = 0;

                switch(type[1]) {
                    case 'materials':
                        count = browseFilesCounter.training;
                        break;
                    case 'comments':
                        count = browseFilesCounter.comments;
                        break;
                }

                if(count > 0) {
                    var prevFile = $('#file_' + type[1] + '_' + (count - 1)).val();
                    if(prevFile == undefined || prevFile == '') {
                        $('#file_' + type[1] + '_' + (count - 1)).click();
                        return;
                    }
                }

                switch(type[1]) {
                    case 'materials':
                        $('#filesToUploadBox_' + type[1]).append('<p><input type="file" name="' + type[1] + '[]" id="file_' + type[1] + '_' + count + '" /><a href="javascript:void(0)" class="remove-upload-materials">X</a></p>');
                        ++browseFilesCounter.training;
                        break;
                    case 'comments':
                        $('#filesToUploadBox_' + type[1]).append('<p><input type="file" name="' + type[1] + '[]" id="file_' + type[1] + '_' + count + '" /><a href="javascript:void(0)" class="remove-upload-comments">X</a></p>');
                        ++browseFilesCounter.comments;
                        break;
                }

                $('#file_' + type[1] + '_' + count).click();

            });
            
            $( "#sr_launched_date" ).datepicker({dateFormat: 'mm/dd/yy'});

            $('#filesToUploadBox_materials').on('click', '.remove-upload-materials', function() {
                $(this).parent().remove();
                browseFilesCounter.training--;
            });

            $('#filesToUploadBox_comments').on('click', '.remove-upload-comments', function() {
                $(this).parent().remove();
                browseFilesCounter.comments--;
            });

            $('body').on('click', '.remove-uploaded-materials', function(e) {
                e.preventDefault();
                var link = $(this);
                $.ajax({
                    type:"POST",
                    url:link.prop('href'),
                    success: function(data){
                        if (data == '1') {
                            link.prev('span').remove();
                            link.prev('a').remove();
                            link.prev('span').remove();
                            link.next('br').remove();
                            link.remove();
                        } else if (data == '0') {
                            link.closest('div.note').remove();
                        } else {
                            alert(data);
                        }
                    }
                });
            });
        });
    });
</script>
