<?php
$urlOrder = $order == 'ASC' ? 'DESC' : 'ASC';
$authService = new \Zend\Authentication\AuthenticationService();
$authService->setStorage(new \SanAuth\Model\MyAuthStorage('hipaa'));
$identity = $authService->getIdentity();
?>

<div class="page-title">
    <h1 class="fleft security_reminders">Security reminders</h1>
    <a href="<?php echo $this->url('securityreminder', array('action' => 'list', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => 0)); ?>" class="label <?php echo $roleFilter == 0 ? ' selected ' : '' ?>">All</a>
    <a href="<?php echo $this->url('securityreminder', array('action' => 'list', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => 1)); ?>" class="label <?php echo $roleFilter == 1 ? ' selected ' : '' ?>">Active</a>
    <a href="<?php echo $this->url('securityreminder', array('action' => 'list', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => 2)); ?>" class="label <?php echo $roleFilter == 2 ? ' selected ' : '' ?>">Archived</a>
    <form id="list_search_form" method="GET" action="<?php echo $this->url('securityreminder', array('action' => 'list', 'roleFilter' => $roleFilter)); ?>">
        <a href="javascript:" onclick="$('#list_search_form').submit()" id="list_search-button"><i class="fa fa-search"></i></a>
        <input type="text" name="search" id="list_search" placeholder="Search" value="<?php echo $search?>">
    </form>
    <a href="/securityreminder/edit" class="button"><i class="fa fa-plus-circle"></i> Add New Security reminder</a>
    <div class="cboth"></div>
</div>

<p></p>

<table class="securityreminders" cellpadding="0" cellspacing="0">
    <thead>
        <tr>
            <?php $classSort = ($order_by == 'title') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>
                <a href="<?php echo $this->url('securityreminder', array('action' => 'list', 'page' => $page, 'order_by' => 'title', 'order' => $urlOrder, 'roleFilter' => $roleFilter, 'search' => $search)); ?>">
                    Title <i class="fa <?php echo $classSort ?>"></i>
                </a>
            </th>

            <?php $classSort = ($order_by == 'launched_date') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>
                <a href="<?php echo $this->url('securityreminder', array('action' => 'list', 'page' => $page, 'order_by' => 'launched_date', 'order' => $urlOrder, 'roleFilter' => $roleFilter, 'search' => $search)); ?>">
                    Launched Date <i class="fa <?php echo $classSort ?>"></i>
                </a>
            </th>

            <?php $classSort = ($order_by == 'developed_by') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>
                <a href="<?php echo $this->url('securityreminder', array('action' => 'list', 'page' => $page, 'order_by' => 'developed_by', 'order' => $urlOrder, 'roleFilter' => $roleFilter, 'search' => $search)); ?>">
                    Developed By <i class="fa <?php echo $classSort ?>"></i>
                </a>
            </th>

            <th> Distribution Type</th>

            <th>Comments</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->paginator as $sr): ?>
            <?php
            $copyOfMaterials = $this->noteTable->getNotes($sr->sr_id, \Note\Model\Note::NOTE_SRM);
            $comments        = $this->noteTable->getNotes($sr->sr_id, \Note\Model\Note::NOTE_SRC);
            ?>
            <tr>
                <td><?php echo $sr->sr_title ?></td>
                <td><?php echo ($sr->sr_launched_date != '0000-00-00') ? $this->formatDateA($sr->sr_launched_date) : '' ?></td>
                <td><?php echo $sr->_developed_by_name ?></td>
                <td><?php echo $sr->_dt_type ?></td>
                <td><?php echo $this->textHelper($sr->_sr_comment, 20); ?></td>
                <td style="white-space: nowrap;" class="aright">
                    <?php if ($sr->_sr_attachment): ?>
                        <a style="margin-left: 10px;" href="" class="attachments" rel="<?php echo $sr->sr_id ?>" title="View Attachments"><i class="fa fa-paperclip"></i></a> &nbsp;
                    <?php endif; ?>
                    <a href="/securityreminder/edit/<?php echo $sr->sr_id ?>" title="Edit"><i class="fa fa-pencil"></i></a> &nbsp;
                    <?php if ($sr->sr_active): ?>
                        <?php $deleteUrl = '/securityreminder/delete/' . $sr->sr_id; ?>
                        <a href="#confirmation-box-modal" onclick="$('#deleteYes').attr('href', '<?php echo $deleteUrl ?>')" class="confirmation-modal i-delete"><i class="fa fa-trash-o"></i></a>
                    <?php elseif ($identity['u_role_id'] == \Admin\Model\User::ROLE_ADMIN): ?>
                        <a href="/securityreminder/unarchive/<?php echo $sr->sr_id  ?>" class="">Unarchive</a>
                    <?php endif; ?>
                </td>
            </tr>
            <tr class="expandable" id="attachments<?php echo $sr->sr_id ?>">
                <td>&nbsp;</td>
                <?php foreach (array('Copy of Materials' => $copyOfMaterials, 'Reports' => $comments) as $keyAtt => $notes): ?>
                <td colspan="2">
                    <div>
                        <div><strong><?php echo $keyAtt ?>:</strong></div>
                        <div>
                        <?php foreach ($notes as $note): ?>
                            <?php if ($note->_files != ''): ?>
                                <?php
                                $_files = explode(',', $note->_files);
                                ?>
                                <?php foreach ($_files as $_file): ?>
                                    <?php
                                    $_file = explode('::', $_file);
                                    $_fileName = $_file[0];
                                    $_fileId = $_file[1];
                                    ?>
                                    <span style="float: left; margin-right: 5px;" class="i-file"></span><a href="/files/get/note/<?php echo $note->note_id ?>/<?php echo $_fileId ?>" class="" target="_blank"><?php echo $_fileName ?></a><br/>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        <?php endforeach; ?>
                        </div>
                    </div>
                </td>
                <?php endforeach; ?>
                <td>&nbsp;</td>
            </tr>

        <?php endforeach; ?>
    </tbody>
</table>

<?php echo $this->paginationControl(
    $this->paginator,
    'sliding',
    array('partial/paginator.phtml', 'securityreminder'),
    array('route' => 'list', 'order_by' => $order_by, 'order' => $order, 'page' => $page, 'roleFilter' => $roleFilter, 'role' => 1, 'controller' => 'securityreminder', 'action' => 'list')
);
?>

<div class="cboth"><br /></div>

<script type="text/javascript">
    jQuery(function() {
        $(document).ready(function() {
            $('.sr_active_checkbox').click(function() {
                var $this  = $(this);
                var id  = $(this).attr('data-id');
                var archived  = $(this).attr('data-archived') == 1 ? 0 : 1;

                $.ajax({
                    type:"POST",
                    url:"/securityreminder/setstatus",
                    data: {'id': id, 'archived': archived},
                    success: function(data){
                        if(data.result == 'true') {
                            $this.attr('data-archived', archived);
                            if(archived == 1) $this.attr('checked', true);
                                else $this.attr('checked', false);
                        }
                    }
                });

            });

            $('#list_search_form').submit(function(e){
                e.preventDefault();
                var search = $('#list_search').val();
                if(search === '') {
                    window.location.href = $(this).attr('action');
                } else if(search !== undefined) {
                    window.location.href = $(this).attr('action') + '/search/' + search;
                }
            });

            jQuery('.expandable').hide();
            jQuery('.attachments').click(function(e) {
                e.preventDefault();
                var $this = $(this);
                var idA = $this.attr('rel');
                if(jQuery('#attachments' + idA).is(':visible')) {
                    jQuery('#attachments' + idA).slideUp();
                } else {
                    jQuery('#attachments' + idA).slideDown();
                }
            });
        });
    });
</script>