<?php foreach ($this->logsActivities as $log): ?>
    <tr rel="<?php echo $log->lo_id ?>">
        <td>
            <?php if ($log->lo_item_type == \Application\Model\LogsTable::ITEM_TYPE_COMPANY): ?>
                <?php if ($log->lo_type == \Application\Model\LogsTable::TYPE_ADD): ?>
                    New company <?php echo $log->_c_name ?> has been added.<br /><small><?php echo $this->formatDateA($log->lo_create_date, true) ?></small>
                <?php elseif ($log->lo_type == \Application\Model\LogsTable::TYPE_EDIT): ?>
                    Company <?php echo $log->_c_name ?> has been edited.<br /><small><?php echo $this->formatDateA($log->lo_create_date, true) ?></small>
                <?php elseif ($log->lo_type == \Application\Model\LogsTable::TYPE_DELETE): ?>
                    Company <?php echo $log->_c_name ?> has been deleted.<br /><small><?php echo $this->formatDateA($log->lo_create_date, true) ?></small>
                <?php endif; ?>
            <?php elseif ($log->lo_item_type == \Application\Model\LogsTable::ITEM_TYPE_CLIENT): ?>
                <?php if ($log->lo_type == \Application\Model\LogsTable::TYPE_ADD): ?>
                    New client <?php echo $log->_cl_name ?> has been added.<br /><small><?php echo $this->formatDateA($log->lo_create_date, true) ?></small>
                <?php elseif ($log->lo_type == \Application\Model\LogsTable::TYPE_EDIT): ?>
                    Client <?php echo $log->_cl_name ?> has been edited.<br /><small><?php echo $this->formatDateA($log->lo_create_date, true) ?></small>
                <?php elseif ($log->lo_type == \Application\Model\LogsTable::TYPE_DELETE): ?>
                    Client <?php echo $log->_cl_name ?> has been deleted.<br /><small><?php echo $this->formatDateA($log->lo_create_date, true) ?></small>
                <?php endif; ?>
            <?php elseif ($log->lo_item_type == \Application\Model\LogsTable::ITEM_TYPE_BA): ?>
                <?php if ($log->lo_type == \Application\Model\LogsTable::TYPE_ADD): ?>
                    New Business Associate <?php echo $log->_ba_name ?> has been added.<br /><small><?php echo $this->formatDateA($log->lo_create_date, true) ?></small>
                <?php elseif ($log->lo_type == \Application\Model\LogsTable::TYPE_EDIT): ?>
                    Business Associate <?php echo $log->_ba_name ?> has been edited.<br /><small><?php echo $this->formatDateA($log->lo_create_date, true) ?></small>
                <?php elseif ($log->lo_type == \Application\Model\LogsTable::TYPE_DELETE): ?>
                    Business Associate <?php echo $log->_ba_name ?> has been deleted.<br /><small><?php echo $this->formatDateA($log->lo_create_date, true) ?></small>
                <?php endif; ?>
            <?php elseif ($log->lo_item_type == \Application\Model\LogsTable::ITEM_TYPE_BREACHLOG): ?>
                <?php if ($log->lo_type == \Application\Model\LogsTable::TYPE_ADD): ?>
                    New Breach Log <?php echo $log->_bl_name ?> has been added.<br /><small><?php echo $this->formatDateA($log->lo_create_date, true) ?></small>
                <?php elseif ($log->lo_type == \Application\Model\LogsTable::TYPE_EDIT): ?>
                    Breach Log <?php echo $log->_bl_name ?> has been edited.<br /><small><?php echo $this->formatDateA($log->lo_create_date, true) ?></small>
                <?php elseif ($log->lo_type == \Application\Model\LogsTable::TYPE_DELETE): ?>
                    Breach Log <?php echo $log->_bl_name ?> has been deleted.<br /><small><?php echo $this->formatDateA($log->lo_create_date, true) ?></small>
                <?php endif; ?>
            <?php elseif ($log->lo_item_type == \Application\Model\LogsTable::ITEM_TYPE_BRP): ?>
                <?php if ($log->lo_type == \Application\Model\LogsTable::TYPE_ADD): ?>
                    Breach Remediation Plan for <?php echo $log->_brpc_name ?> has been added.<br /><small><?php echo $this->formatDateA($log->lo_create_date, true) ?></small>
                <?php elseif ($log->lo_type == \Application\Model\LogsTable::TYPE_EDIT): ?>
                    Breach Remediation Plan for <?php echo $log->_brpc_name ?> has been edited.<br /><small><?php echo $this->formatDateA($log->lo_create_date, true) ?></small>
                <?php elseif ($log->lo_type == \Application\Model\LogsTable::TYPE_DELETE): ?>
                    Breach Remediation Plan for <?php echo $log->_brpc_name ?> has been deleted.<br /><small><?php echo $this->formatDateA($log->lo_create_date, true) ?></small>
                <?php elseif ($log->lo_type == \Application\Model\LogsTable::TYPE_SIGNEDOFF): ?>
                    Breach Remediation Plan for <?php echo $log->_brpc_name ?> has been signed-off.<br /><small><?php echo $this->formatDateA($log->lo_create_date, true) ?></small>
                <?php endif; ?>
            <?php elseif ($log->lo_item_type == \Application\Model\LogsTable::ITEM_TYPE_ASSESSMENT): ?>
                <?php if ($log->lo_type == \Application\Model\LogsTable::TYPE_ADD): ?>
                    Assessment for <?php echo $log->_ac_name ?> has been added.<br /><small><?php echo $this->formatDateA($log->lo_create_date, true) ?></small>
                <?php elseif ($log->lo_type == \Application\Model\LogsTable::TYPE_EDIT): ?>
                    Assessment for <?php echo $log->_ac_name ?> has been edited.<br /><small><?php echo $this->formatDateA($log->lo_create_date, true) ?></small>
                <?php elseif ($log->lo_type == \Application\Model\LogsTable::TYPE_DELETE): ?>
                    Assessment for <?php echo $log->_ac_name ?> has been deleted.<br /><small><?php echo $this->formatDateA($log->lo_create_date, true) ?></small>
                <?php elseif ($log->lo_type == \Application\Model\LogsTable::TYPE_UPLOADED_ROLES): ?>
                    <?php echo $log->_ac_name ?> uploaded organization roles.<br /><small><?php echo $this->formatDateA($log->lo_create_date, true) ?></small>
                <?php elseif ($log->lo_type == \Application\Model\LogsTable::TYPE_UPLOADED_INVENTORY): ?>
                    <?php echo $log->_ac_name ?> uploaded organization inventory.<br /><small><?php echo $this->formatDateA($log->lo_create_date, true) ?></small>
                <?php endif; ?>
            <?php elseif ($log->lo_item_type == \Application\Model\LogsTable::ITEM_TYPE_RP): ?>
                <?php if ($log->lo_type == \Application\Model\LogsTable::TYPE_ADD): ?>
                    Remediation Plan for <?php echo $log->_rpc_name ?> has been added.<br /><small><?php echo $this->formatDateA($log->lo_create_date, true) ?></small>
                <?php elseif ($log->lo_type == \Application\Model\LogsTable::TYPE_EDIT): ?>
                    Remediation Plan for <?php echo $log->_rpc_name ?> has been edited.<br /><small><?php echo $this->formatDateA($log->lo_create_date, true) ?></small>
                <?php elseif ($log->lo_type == \Application\Model\LogsTable::TYPE_DELETE): ?>
                    Remediation Plan for <?php echo $log->_rpc_name ?> has been deleted.<br /><small><?php echo $this->formatDateA($log->lo_create_date, true) ?></small>
                <?php elseif ($log->lo_type == \Application\Model\LogsTable::TYPE_SIGNEDOFF): ?>
                    Remediation Plan for <?php echo $log->_rpc_name ?> has been signed-off.<br /><small><?php echo $this->formatDateA($log->lo_create_date, true) ?></small>
                <?php endif; ?>
            <?php endif; ?>
        </td>
    </tr>
<?php endforeach; ?>