<div class="page-title">
    <h1 class="fleft">Dashboard</h1>
    <?php if($usRoleId != 7):?><a href="/breachlog/edit" class="button"><i class="fa fa-plus-circle"></i> Add New Incident Log</a><? endif;?>
    <div class="cboth"></div>
</div>

<p>Welcome paragraph will go here...</p>


<div class="cboth"><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /></div>