<?php

// within a view script
$form = $this->form;
$form->prepare();

// Assuming the "contact/process" route exists...
$form->setAttribute('action', '/traininglog/edit');

// Set the method attribute for the form
$form->setAttribute('method', 'post');

// Render the opening tag
?>


    <div class="page-title">
        <h1 class="fleft"><?php if($this->tlId) {?>Edit <?php } else {?>Add New <?php }?>Training Log</h1>
        <div class="cboth"></div>
    </div>

    <p></p>

<div class="col-left">
    <form action="/traininglog/edit/<?php echo $this->tlId ?>" method="post" enctype="multipart/form-data" name="traininglog" id="traininglog">
        <?php
            $fn = $form->get('tl_id');
            echo $this->formHidden($fn);
        ?>
        <?php
            $fn = $form->get('tl_active');
            echo $this->formHidden($fn);
        ?>

        <?php
            $authService = new \Zend\Authentication\AuthenticationService();
            $authService->setStorage(new \SanAuth\Model\MyAuthStorage('hipaa'));
            $identity = $authService->getIdentity();
        ?>

        <p>
            <?php $fn = $form->get('tl_company_id');
            echo $this->formLabel($fn);
            echo $this->formSelect($fn->setAttributes(array('class'=>'form-control required', 'id' => 'company')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        
        <p>
            <?php $fn = $form->get('tl_title');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <?php $fn = $form->get('tl_tlt_id');
            echo $this->formLabel($fn);
            echo $this->formSelect($fn->setAttributes(array('id'=>'type', 'class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p id="_tl_type_name_wrap" style="border: 0;display: none">
            <label for="_tl_type_name">Type Name</label>
            <input type="text" name="_tl_type_name" id="_tl_type_name" value="<?php echo $tlObj ? $tlObj->_tl_type_name : ''?>" required disabled="disabled">
        </p>

        <p>
            <?php
            $fn = $form->get('tl_conducted_date');
            if ($this->tlObj):
                $fn->setValue($this->formatDateA($this->tlObj->tl_conducted_date, false, true));
            endif;
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required', 'id' => 'tl_conducted_date', 'readonly' => 'readonly')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        
        <p>
            <?php
            $fn = $form->get('tl_hire_date');
            if ($this->tlObj && $this->tlObj->tl_hire_date):
                $fn->setValue($this->formatDateA($this->tlObj->tl_hire_date, false, true));
            endif;
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required', 'id' => 'tl_hire_date', 'readonly' => 'readonly')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <?php
            $fn = $form->get('_tl_trainer');
            echo $this->formLabel($fn);
            echo $this->formSelect($fn->setAttributes(array('class'=>'form-control required', 'id'=>'_tl_trainer')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p id="_tl_trainer_name_wrap" style="border: 0;display: none">
            <label for="_tl_trainer_name">Trainer Name</label>
            <input type="text" name="_tl_trainer_name" id="_tl_trainer_name" value="<?php echo $this->tlObj ? $this->tlObj->_tl_trainer_name : ''; ?>" required disabled="disabled">
        </p>

        <p>
            <label style="width: 300px;">Regulation</label><br />
            <?php
            $fn = $form->get('_tl_cur_regulations');
            echo $this->formSelect($fn->setAttributes(array('class'=>'', 'id' => '_tl_cur_regulations')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        <div>
            <?php foreach ($regulations as $value) {?>
                <div id="_regulation_wrap_<?php echo $value->rg_id?>" style="display:none">
                    <p>
                        <label for="regulation_pp_name_<?php echo $value->rg_id?>">Policy&Procedure Name</label>
                        <input type="text" name="_regulation[<?php echo $value->rg_id?>][rg_pp_name]" id="_regulation_pp_name_<?php echo $value->rg_id?>" value="<?php echo $value->rg_pp_name?>" readonly="readonly" disabled="disabled">
                    </p>
                    <p style="border: 0;">
                        <label for="regulation_pp_number_<?php echo $value->rg_id?>">Policy&Procedure Number</label>
                        <input type="text" name="_regulation[<?php echo $value->rg_id?>][rg_pp_number]" id="_regulation_pp_number_<?php echo $value->rg_id?>" value="<?php echo $value->rg_pp_number?>" readonly="readonly" disabled="disabled">
                    </p>
                    <p style="border: 0;">
                        <label for="regulation_number_<?php echo $value->rg_id?>">Regulation Number</label>
                        <input type="text" name="_regulation[<?php echo $value->rg_id?>][rg_number]" id="_regulation_number_<?php echo $value->rg_id?>" value="<?php echo $value->rg_number?>" readonly="readonly" disabled="disabled">
                    </p>
                    <?php if($value->rg_u_owner_id): ?>
                        <p style="border: 0;">
                            <label for="regulation_description_<?php echo $value->rg_id?>">Regulation Description</label>
                            <input type="text" name="_regulation[<?php echo $value->rg_id?>][rg_description]" id="_regulation_description_<?php echo $value->rg_id?>" value="<?php echo $value->rg_description?>">
                        </p>
                    <?php endif; ?>
                </div>
            <?php }?>
        
            <div id="_regulation_wrap_-1" style="display:none">
                <p>
                    <label for="regulation_pp_name_-1">Policy&Procedure Name</label>
                    <input type="text" name="_regulation[-1][rg_pp_name]" id="_regulation_pp_name_-1" value="">
                </p>
                <p style="border: 0;">
                    <label for="regulation_pp_number_-1">Policy&Procedure Number</label>
                    <input type="text" name="_regulation[-1][rg_pp_number]" id="_regulation_pp_number_-1" value="">
                </p>
                <p style="border: 0;">
                    <label for="regulation_number_-1">Regulation Number</label>
                    <input type="text" name="_regulation[-1][rg_number]" id="_regulation_number_-1" value="">
                </p>
                <p style="border: 0;">
                    <label for="regulation_description_-1">Regulation Description</label>
                    <input type="text" name="_regulation[-1][rg_description]" id="_regulation_description_-1" value="">
                </p>
            </div>
        </div>

        <div class="cboth"></div>

        <p style="overflow: hidden;">
            <strong style="line-height: 40px; float:left;">Attendees</strong>
            <a id="browseFile_attendees" style="margin-right: 130px; float:right" href="javascript:" class="button"><i class="fa fa-plus-circle"></i> Import from CSV</a>
            <div id="filesToUploadBox_attendees">

            </div>
            <?php
                $fn = $form->get('tl_attendees');
            ?>
            <span class="description_text" id="tl_attendees_help" style="display: none">To view the attendees added, please save your changes. You can then make any edits you might need to make to this page</span>
            <?php
                echo $this->formTextarea($fn->setAttributes(array('class'=>'', 'style' => 'width: 450px; height: 85px;')));
                echo $this->formElementErrors($fn);
            ?>
            <span class="description_text">"CSV file format: First name, Last name, title, email address"</span>
        </p>

        <p style="border: 0;">
            <strong style="line-height: 30px;">Training materials</strong><br />
            <a id="browseFile_training" href="javascript:" class="button"><i class="fa fa-plus-circle"></i> Browse Files...</a>
            <br /><br /><br />
        </p>

        <div class="cboth"></div>
        <div id="filesToUploadBox_training">

        </div>
            <?php foreach ($trainingMaterials as $note): ?>
                <div class="note">
                    <strong><?php echo $note->_username ?></strong> <small> on <?php echo $note->_note_create_date_format ?></small><br />
                    <p>
                        <?php echo $note->note_text ?><br />
                        <?php if ($note->_files != ''): ?>
                            <?php
                            $_files = explode(',', $note->_files);
                            ?>
                            <strong>Training materials:</strong><br />
                            <?php foreach ($_files as $_file): ?>
                                <?php
                                $_file = explode('::', $_file);
                                $_fileName = $_file[0];
                                $_fileId = $_file[1];
                                ?>
                                <span style="float: left; margin-right: 5px;" class="''?>"></span><a href="/files/get/note/<?php echo $note->note_id ?>/<?php echo $_fileId ?>" class="" target="_blank"><?php echo $_fileName ?></a><br/>

                            <?php endforeach; ?>
                        <?php endif; ?>
                    </p>
                </div>
            <?php endforeach; ?>
        <div class="cboth"></div>

        <p>
            <strong style="line-height: 30px;">Comments</strong><br />
            <?php
            $fn = $formNote->get('note_text');
            echo $this->formTextarea($fn->setAttributes(array('style' => 'width: 450px;')));
            echo $this->formElementErrors($fn);
            ?>

        </p>
        <p style="border: 0;">
            <a id="browseFile_comments" href="javascript:" class="button"><i class="fa fa-plus-circle"></i> Browse Files...</a>
            <br /><br /><br />
        </p>

        <div class="cboth"></div>
        <div id="filesToUploadBox_comments">

        </div>
        
        <div class="cboth"></div>
        
        <?php if ($this->tlId && is_object($comments) && ($comments->count())): ?>
            <?php foreach ($comments as $note): ?>
                <div class="note">
                    <strong><?php echo $note->_username ?></strong> <small> on <?php echo $note->_note_create_date_format ?></small><br />
                    <p>
                        <?php echo $note->note_text ?><br />
                        <?php if ($note->_files != ''): ?>
                            <?php
                            $_files = explode(',', $note->_files);
                            ?>
                            <strong>Comments:</strong><br />
                            <?php foreach ($_files as $_file): ?>
                                <?php
                                $_file = explode('::', $_file);
                                $_fileName = $_file[0];
                                $_fileId = $_file[1];
                                ?>
                                <span style="float: left; margin-right: 5px;" class="''?>"></span><a href="/files/get/note/<?php echo $note->note_id ?>/<?php echo $_fileId ?>" class="" target="_blank"><?php echo $_fileName ?></a><br/>

                            <?php endforeach; ?>
                        <?php endif; ?>
                    </p>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
        
        <div class="cboth"></div>
        
        <div class="form-buttons">
            <input type="submit" value="Save" class="form-button" />
            <div class="fleft">or</div>
            <a href="/traininglog/list" class="cancel">Cancel</a>
        </div>

    <?php echo $this->form()->closeTag() ?>
</div>

<div class="cboth"><br /></div>


<script type="text/javascript">
    jQuery(function() {
        $('#traininglog').validate();

        var browseFilesCounter = {'attendees':0, 'training':0, 'comments':0};
        
        $(document).ready(function() {
            $('a[id^=browseFile_]').click(function() {
                var type  = $(this).attr('id').split('_');
                var count = 0;
                
                switch(type[1]) {
                    case 'attendees':
                        $('#tl_attendees_help').show();
                        count = browseFilesCounter.attendees;
                        break;
                    case 'training':
                        count = browseFilesCounter.training;
                        break;
                    case 'comments':
                        count = browseFilesCounter.comments;
                        break;
                }

                if(count > 0) {
                    if(type[1] == 'attendees') return;
                    var prevFile = $('#file_' + type[1] + '_' + (count - 1)).val();
                    if(prevFile == undefined || prevFile == '') {
                        $('#file_' + type[1] + '_' + (count - 1)).click();
                        return;
                    }
                }

                $('#filesToUploadBox_' + type[1]).append('<input type="file" name="' + type[1] + '[]" id="file_' + type[1] + '_' + count + '" />');

                $('#file_' + type[1] + '_' + count).click();

                switch(type[1]) {
                    case 'attendees':
                        ++browseFilesCounter.attendees;
                        break;
                    case 'training':
                        ++browseFilesCounter.training;
                        break;
                    case 'comments':
                        ++browseFilesCounter.comments;
                        break;
                }

            });
            
            $( "#tl_conducted_date, #tl_hire_date" ).datepicker({dateFormat: 'mm/dd/yy'});

            if($('#type option:selected').val() != '1') {
                $("#tl_hire_date").datepicker("disable").val('-');
            }

            $('#type').change(function(){
                if($('#type option:selected').val() != '1') {
                    $("#tl_hire_date").datepicker("disable").val('-');
                } else {
                    $("#tl_hire_date").val('').attr('disabled',false).datepicker('enable');
                }
            });
        });

        function regulationHandle()
        {
            $('div[id^=_regulation_wrap_]').each(function(){
                $(this).css('display', 'none');
            });

            $('#_tl_cur_regulations option:selected').each(function(){
                $('#_regulation_wrap_' + $(this).val()).css('display', 'block');
            });
        }

        regulationHandle();

        $('#_tl_cur_regulations').change(function(){
            regulationHandle();
        });

        $('#_tl_trainer').change(function(){
            if($('#_tl_trainer option:selected').val() == '-1') {
                $('#_tl_trainer_name_wrap').css('display', 'block');
                $('#_tl_trainer_name').attr('disabled', false);
            } else {
                $('#_tl_trainer_name_wrap').css('display', 'none');
                $('#_tl_trainer_name').attr('disabled', true);
            }
        });

        $('#type').change(function(){
            if($('#type option:selected').val() == '-1') {
                $('#_tl_type_name_wrap').css('display', 'block');
                $('#_tl_type_name').attr('disabled', false);
            } else {
                $('#_tl_type_name_wrap').css('display', 'none');
                $('#_tl_type_name').attr('disabled', true);
            }
        });

        $("#company").change(function(){
            getCompanyUsers()
        });

        function getCompanyUsers()
        {
            var cId = $("#company option:selected").val();
            
            if(cId != undefined && cId != '') {
                $.ajax({
                    type:"GET",
                    url:"/traininglog/gettrainers/" + cId,
                    success: function(data){
                        var html = '<option value="">Please Select</option>';
                        $.each(data, function(index, value) {
                            html += '<option value="' + index + '">' + value + '</option>';
                        });
                        html += '<option value="-1">Other</option>';
                        $('#_tl_trainer').html(html);
                    }
                });
            }
        }
    });
</script>
