<?php

// within a view script
$form = $this->form;
$form->prepare();

// Assuming the "contact/process" route exists...
$form->setAttribute('action', '/traininglog/employeemasterlist');

// Set the method attribute for the form
$form->setAttribute('method', 'post');

// Render the opening tag
?>


    <div class="page-title">
        <h1 class="fleft">Edit Employee Master List</h1>
        <div class="cboth"></div>
    </div>

    <p></p>

<div class="col-left">
    <form action="/traininglog/employeemasterlist" method="post" enctype="multipart/form-data" name="traininglog" id="traininglog">
        
        <?php if ($this->lists && $this->lists->count()) : ?>
        <?php foreach ($lists as $list) : ?>
        <p>
            <?php $fn = $form->get('eml_company_id[]');
            $fn->setValue($list->eml_company_id);
            echo $this->formLabel($fn);
            echo $this->formSelect($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        
        <p>
            <?php $fn = $form->get('eml_list[]');
            $fn->setValue($list->eml_list);
            echo $this->formLabel($fn);
            echo $this->formTextarea($fn->setAttributes(array('class'=>'required', 'style' => 'width: 450px; height: 185px;')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        <?php endforeach; ?>
        <?php else : ?>
        <p>
            <?php $fn = $form->get('eml_company_id[]');
            echo $this->formLabel($fn);
            echo $this->formSelect($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        
        <p>
            <?php $fn = $form->get('eml_list[]');
            echo $this->formLabel($fn);
            echo $this->formTextarea($fn->setAttributes(array('class'=>'required', 'style' => 'width: 450px; height: 185px;')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        <?php endif; ?>
        
        <div class="cboth"></div>
        <p style="border-top: 0">
                        <a id="addLocationButton" href="javascript:void(0)"class="button"><i class="fa fa-plus-circle"></i> + Add list for other Company</a>
                    </p>
        <div class="cboth"></div>
        <div class="form-buttons">
            <input type="submit" value="Save" class="form-button" />
        </div>

    <?php echo $this->form()->closeTag() ?>
</div>

<div class="cboth"><br /></div>
<div id="step" style="display:none">
<p>
    <?php $fn = $form->get('eml_company_id[]');
    $fn->setValue(0);
    echo $this->formLabel($fn);
    echo $this->formSelect($fn->setAttributes(array('class'=>'form-control required')));
    echo $this->formElementErrors($fn);
    ?>
</p>

<p>
    <?php $fn = $form->get('eml_list[]');
    $fn->setValue('');
    echo $this->formLabel($fn);
    echo $this->formTextarea($fn->setAttributes(array('class'=>'required', 'style' => 'width: 450px; height: 185px;')));
    echo $this->formElementErrors($fn);
    ?>
</p>
</div>
<script type="text/javascript">
$(document).ready(function() {
    $('#traininglog').validate();
    var step = $('#step').html();
    $('#addLocationButton').click(function() {
        $(this).parent().before(step);
    })
});
</script>