<?php
$urlOrder = $order == 'ASC' ? 'DESC' : 'ASC';
$authService = new \Zend\Authentication\AuthenticationService();
$authService->setStorage(new \SanAuth\Model\MyAuthStorage('hipaa'));
$identity = $authService->getIdentity();
?>
				
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.css"></link>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>

<div class="page-title">
    <h1 class="fleft">Training Logs</h1>
    <a href="<?php echo $this->url('traininglog', array('action' => 'list', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => 0)); ?>" class="label <?php echo $roleFilter == 0 ? ' selected ' : '' ?>">All</a>
    <a href="<?php echo $this->url('traininglog', array('action' => 'list', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => 1)); ?>" class="label <?php echo $roleFilter == 1 ? ' selected ' : '' ?>">Active</a>
    <a href="<?php echo $this->url('traininglog', array('action' => 'list', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => 2)); ?>" class="label <?php echo $roleFilter == 2 ? ' selected ' : '' ?>">Archived</a>
    <form id="list_search_form" method="GET" onsubmit="encodeInput(this)" action="<?php echo $this->url('traininglog', array('action' => 'list', 'roleFilter' => $roleFilter)); ?>">
        <a href="javascript:" onclick="$('#list_search_form').submit()" id="list_search-button"><i class="fa fa-search"></i></a>
        <input type="text" name="search" id="list_search" placeholder="Search" value="<?php echo $search?>">
    </form>
    <a href="/traininglog/edit" class="button"><i class="fa fa-plus-circle"></i> Add New Training Log</a>
    <div class="cboth"></div>
</div>

<p></p>

<table id="traininglogs-list" cellpadding="0" cellspacing="0">
    <thead>
        <tr>
            <?php $classSort = ($order_by == 'title') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>Title</th>
            <?php $classSort = ($order_by == 'type') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>Type</th>

            <?php $classSort = ($order_by == 'conducted_date') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>Conducted Date</th>

            <?php $classSort = ($order_by == 'hire_date') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>Hire Date</th>

            <?php $classSort = ($order_by == 'trainer') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>Trainer</th>
            <th>Company</th>
            <th>Regulation</th>
            <th>Attendees</th>
            <th>Comments</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->paginator as $tl): ?>
            <?php
            $trainingMaterials = $this->noteTable->getNotes($tl->tl_id, \Note\Model\Note::NOTE_TLT);
            $comments          = $this->noteTable->getNotes($tl->tl_id, \Note\Model\Note::NOTE_TLC);
            ?>
            <tr>
                <td><?php echo $tl->tl_title ?></td>
                <td><?php echo $tl->_tlt_name ?></td>
                <td><?php echo ($tl->tl_conducted_date != '0000-00-00') ? $this->formatDateA($tl->tl_conducted_date) : '' ?></td>
                <td><?php echo ($tl->tl_hire_date != '0000-00-00') ? $this->formatDateA($tl->tl_hire_date) : '-' ?></td>
                <td><?php echo $tl->_tl_trainer_name ?></td>
                <td><?php echo $tl->_tl_company_name ?></td>
                <td><?php echo $this->textHelper($tl->_tl_regulation, 20); ?></td>
                <td><?php echo $this->textHelper($tl->tl_attendees, 20); ?></td>
                <td><?php echo $this->textHelper($tl->_tl_comment, 20); ?></td>
                <td style="white-space: nowrap;" class="aright">
										<?php if ($tl->_tl_attachment): ?>
                        <a style="margin-left: 10px;" href="" class="attachments" rel="<?php echo $tl->tl_id ?>" title="View Attachments">
													<i class="fa fa-paperclip"></i>
												</a> &nbsp;
                    <?php endif; ?>
                    <a href="/traininglog/edit/<?php echo $tl->tl_id ?>" title="Edit"><i class="fa fa-pencil"></i></a> &nbsp;
                    <?php if ($tl->tl_active): ?>
                        <?php $deleteUrl = '/traininglog/delete/' . $tl->tl_id; ?>
                        <a href="#confirmation-box-modal" onclick="$('#deleteYes').attr('href', '<?php echo $deleteUrl ?>')" class="confirmation-modal i-delete"><i class="fa fa-trash-o"></i></a>                        
                    <?php elseif ($identity['u_role_id'] == \Admin\Model\User::ROLE_ADMIN): ?>
                        <a href="/traininglog/unarchive/<?php echo $tl->tl_id  ?>" class="">Unarchive</a>
                    <?php endif; ?>
										<?php $tgrid = array("subgrid" => array()); ?>
										<?php $ct = 0; ?>
										<?php foreach (array('Training materials' => $trainingMaterials, 'Reports' => $comments) as $keyAtt => $notes): ?>
											<?php $tgrid['subgrid'][$ct] = array("keyAtt" => $keyAtt); ?>
                      <?php foreach ($notes as $note): ?>
												<?php if ($note->_files != ''): ?>
													<?php	$_files = explode(',', $note->_files); ?>
													<?php foreach ($_files as $_file): ?>
														<?php
															$_file = explode('::', $_file);
															$_noteId = $note->note_id;
															$_fileName = $_file[0];
															$_fileId = $_file[1];
														?>
														<?php $ngrid = array("note_id" => $_noteId, "fileId" => $_fileId, "fileName" => $_fileName); ?>
													<?php endforeach; ?>
												<?php endif; ?>
                      <?php endforeach; ?>
											<?php $tgrid['subgrid'][$ct]['notes'] = array($ngrid); ?>
											<?php $ct++; ?>
										<?php endforeach; ?>

										<?php $jdat = json_encode($tgrid); ?>
										<input type="hidden" id="data_json<?php echo $tl->tl_id ?>" value='<?php echo htmlentities($jdat); ?>' ></input>
				        </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<script type="text/javascript">
	$(document).ready(function(){
		$('#list_search_form').submit(function(e){
				e.preventDefault();
				var search = $('#list_search').val();
				if(search === '') {
						window.location.href = $(this).attr('action');
				} else if(search !== undefined) {
						window.location.href = $(this).attr('action') + '/search/' + search;
				}
		});
		function format ( jdat ) {
			//alert('format d='+jdat);
			var j = JSON.parse(jdat);
			if(typeof j === 'undefined')
				return '';
			if(typeof j.subgrid === 'undefined')
				return '';
			var s = '<tr>';
			s += '<td>&nbsp;</td>';
			j.subgrid.forEach(function(e){
				s += '<td colspan="2">';	
        s += 		'<div>';
        s += 			'<div><strong>' + e.keyAtt + ':</strong></div>';
        s += 			'<div>';
				if(typeof e.notes !== 'undefined'){
					e.notes.forEach(function(e2) {
						if(typeof e2.fileName !== "undefined" && typeof e2.fileId !== "undefined" && typeof e2.note_id !== "undefined"){
              s +=	'<span style="float: left; margin-right: 5px;" class="i-file"></span><a href="/files/get/note/' + e2.note_id + '/' + e2.fileId + '" class="" target="_blank">' + e2.fileName + '</a><br/>';							
						}
					});
				}
        s += 			'</div>';
        s += 		'</div>';
			});
					
			s += 		'</td>';
			s += 	'</td>';
			s += '</tr>';

			return s;
		}


		var table = $('#traininglogs-list').DataTable({
			"columnDefs": [
					{ "orderable": false, "targets": 9 }
			]
		});								
				
		$('.dataTables_filter input[type="search"]').
			css({'width':'95%','display':'inline-block'});

		$('.attachments').click(function(e) {
			e.preventDefault();
			var $this = $(this);
      var idA = $this.attr('rel');
      var datx = $('#data_json' + idA).val();
			var dat = datx.replace( /\&amp;/g, '&' );
			
			var tr = $(this).closest('tr');
			var row = table.row( tr );

			if ( row.child.isShown() ) {
					// This row is already open - close it
					row.child.hide();
					tr.removeClass('shown');
			}
			else {
					// Open this row
					row.child( format(dat) ).show();
					tr.addClass('shown');
			}			
		});
	});
</script>

<div class="cboth"><br /></div>
