CREATE TABLE IF NOT EXISTS `disclosure_records` (
  `dr_id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `dr_c_id` int(11) NOT NULL,
  `dr_adr_id` int(11) NOT NULL,
  `dr_date_received` date NOT NULL,
  `dr_patient_name` varchar(255) NOT NULL,
  `dr_date_disclosure` date NOT NULL,
  `dr_medical_record_number` varchar(255) NOT NULL,
  `dr_date_of_birth` date NOT NULL,
  `dr_phi_information_disclosed` varchar(4096) NOT NULL,
  `dr_purpose_of_disclosure` varchar(4096) NOT NULL,
  `dr_name_of_requestor` varchar(4096) NOT NULL,
  `dr_address` varchar(4096) NOT NULL,
  `dr_is_verbal` char(3) NOT NULL,
  `dr_is_authorized` char(3) NOT NULL,
  `dr_entered_by` varchar(255) NOT NULL,
  `dr_date_entered` date NOT NULL,
  `dr_reviewed_by` varchar(255) NOT NULL,
  `dr_date_reviewed` date NOT NULL,
  `dr_disclosed_by` varchar(255) NOT NULL,
  `dr_date_disclosed` date NOT NULL,  
  `dr_active` tinyint(1) NOT NULL DEFAULT '1',
  `dr_create_u_id` int(11) NOT NULL
) ENGINE=InnoDB CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `accounting_requests` (
  `ar_id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ar_c_id` int(11) NOT NULL,
  `ar_adr_id` int(11) NOT NULL,
  `ar_requested_by` varchar(255) NOT NULL,
  `ar_date_requested` date NOT NULL,
  `ar_disclosure_address` varchar(255) NOT NULL,
  `ar_patient_name` varchar(255) NOT NULL,
  `ar_medical_record_number` varchar(255) NOT NULL,
  `ar_date_of_birth` date NOT NULL,
  `ar_patient_address` varchar(255) NOT NULL,
  `ar_date_requested_from` date NOT NULL,
  `ar_date_requested_to` date NOT NULL,
  `ar_fees_charge` varchar(255) NOT NULL,
  `ar_is_fees` char(3) NOT NULL,
  `ar_is_extensions` char(3) NOT NULL,
  `ar_extension_reason` varchar(255) NOT NULL,
  `ar_is_finalized` char(3) NOT NULL,
  `ar_date_sent` date NOT NULL,
  `ar_date_patient_notified` date NOT NULL,
  `ar_staff_member` varchar(255) NOT NULL,
  `ar_active` tinyint(1) NOT NULL DEFAULT '1',
  `ar_create_u_id` int(11) NOT NULL
) ENGINE=InnoDB CHARSET=utf8;