<?php

// within a view script
$form = $this->form;
$form->prepare();

// Assuming the "contact/process" route exists...
$form->setAttribute('action', '/breachlog/edit');

// Set the method attribute for the form
$form->setAttribute('method', 'post');

// Render the opening tag
?>


    <div class="page-title">
        <h1 class="fleft">Add New Suspected Breach Incident Log</h1>
        <div class="cboth"></div>
    </div>

    <p></p>

<div class="col-left">
    <form action="/breachlog/edit/<?php echo $this->blId ?>" method="post" enctype="multipart/form-data" name="breachlog" id="breachlog">
        <input type="hidden" id="_bl_cur_regulations_hidden" name="_bl_cur_regulations" value="<?php echo $this->blObj && $this->blObj->_bl_cur_regulations ? implode(',', $this->blObj->_bl_cur_regulations) : ''; ?>">
        <?php
            $fn = $form->get('bl_id');
            echo $this->formHidden($fn);
        ?>

        <?php
            $authService = new \Zend\Authentication\AuthenticationService();
            $authService->setStorage(new \SanAuth\Model\MyAuthStorage('hipaa'));
            $identity = $authService->getIdentity();
        ?>
        <?php if (in_array($identity['u_role_id'], array(\Admin\Model\User::ROLE_ADMIN, \Admin\Model\User::ROLE_CONSULTANT, \Admin\Model\User::ROLE_SENIOR_CONSULTANT))): ?>
            <p>
                <?php $fn = $form->get('bl_c_id');
                echo $this->formLabel($fn);
                echo $this->formSelect($fn->setAttributes(array('id'=>'company', 'class'=>'form-control required')));
                echo $this->formElementErrors($fn);
                ?>
            </p>
            <p style="padding: 0;border-top: 0;">
                <?php if($companyRolesMsg) :?>
                    <label style="padding:0" for="a_c_id" generated="true" class="error"><?php echo $companyRolesMsg ?></label>
                <?php endif; ?>
            </p>
        <?php endif; ?>

        <p>
            <?php
            $fn = $form->get('bl_name');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        
        <p>
            <?php
            $fn = $form->get('bl_invest_led_by');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <?php
            $fn = $form->get('bl_date_of_occurrence');
            if ($this->blObj):
                $fn->setValue($this->formatDateA($this->blObj->bl_date_of_occurrence, false, true));
            endif;
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required', 'id' => 'bl_date_of_occurrence', 'readonly' => 'readonly')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        
        <p>
            <?php
            $fn = $form->get('bl_date_invest_start');
            if ($this->blObj):
                $fn->setValue($this->formatDateA($this->blObj->bl_date_invest_start, false, true));
            endif;
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required', 'id' => 'bl_date_invest_start', 'readonly' => 'readonly')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        
        <p>
            <?php
            $fn = $form->get('bl_date_invest_complete');
            if ($this->blObj):
                $fn->setValue($this->formatDateA($this->blObj->bl_date_invest_complete, false, true));
            endif;
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required', 'id' => 'bl_date_invest_complete', 'readonly' => 'readonly')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <?php
            $fn = $form->get('bl_size');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control', 'id'=>'bl_size')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <label style="width: 300px;">Description of the Breach Event</label><br />
            <?php
            $fn = $form->get('bl_description');
            echo $this->formTextarea($fn->setAttributes(array('class'=>'', 'style' => 'width: 450px; height: 85px;')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <label for="_search_regulation">Regulation Number or Regulation Description</label>
            <input type="text" name="_search_regulation" id="_search_regulation" class="form-control">
        </p>

        <p>
        <div style="width: 750px; height: 300px; overflow-y: scroll;">
            <table id="_regulations_table">
                <thead>
                    <tr>
                        <th>Policy&Procedure Name</th>
                        <th>Policy&Procedure Number</th>
                        <th>Regulation Number</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($regulations as $value) : ?>
                        <tr id="<?php echo $value->rg_id; ?>">
                            <td><?php echo $value->rg_pp_name; ?></td>
                            <td><?php echo $value->rg_pp_number; ?></td>
                            <td><?php echo $value->rg_number; ?></td>
                        </tr>
                    <?php endforeach; ?>
                    <tr id="-1">
                        <td colspan="3">Other</td>
                    </tr>
                </tbody>
            </table>
        </div>
        </p>

        <div>
            <?php foreach ($regulations as $value) {?>
                <div id="_regulation_wrap_<?php echo $value->rg_id?>" style="display:none">
                    <p>
                        <label for="regulation_pp_name_<?php echo $value->rg_id?>">Policy&Procedure Name</label>
                        <input type="text" name="_regulation[<?php echo $value->rg_id?>][rg_pp_name]" id="_regulation_pp_name_<?php echo $value->rg_id?>" value="<?php echo $value->rg_pp_name?>" readonly="readonly" disabled="disabled">
                    </p>
                    <p style="border: 0;">
                        <label for="regulation_pp_number_<?php echo $value->rg_id?>">Policy&Procedure Number</label>
                        <input type="text" name="_regulation[<?php echo $value->rg_id?>][rg_pp_number]" id="_regulation_pp_number_<?php echo $value->rg_id?>" value="<?php echo $value->rg_pp_number?>" readonly="readonly" disabled="disabled">
                    </p>
                    <p style="border: 0;">
                        <label for="regulation_number_<?php echo $value->rg_id?>">Regulation Number</label>
                        <input type="text" name="_regulation[<?php echo $value->rg_id?>][rg_number]" id="_regulation_number_<?php echo $value->rg_id?>" value="<?php echo $value->rg_number?>" readonly="readonly" disabled="disabled">
                    </p>
                    <?php if($value->rg_u_owner_id): ?>
                        <p style="border: 0;">
                            <label for="regulation_description_<?php echo $value->rg_id?>">Regulation Description</label>
                            <input type="text" name="_regulation[<?php echo $value->rg_id?>][rg_description]" id="_regulation_description_<?php echo $value->rg_id?>" value="<?php echo $value->rg_description?>" readonly="readonly" disabled="disabled">
                        </p>
                    <?php endif; ?>
                </div>
            <?php }?>
        
            <div id="_regulation_wrap_-1" style="display:none">
                <p>
                    <label for="regulation_pp_name_-1">Policy&Procedure Name</label>
                    <input type="text" name="_regulation[-1][rg_pp_name]" id="_regulation_pp_name_-1" value="">
                </p>
                <p style="border: 0;">
                    <label for="regulation_pp_number_-1">Policy&Procedure Number</label>
                    <input type="text" name="_regulation[-1][rg_pp_number]" id="_regulation_pp_number_-1" value="">
                </p>
                <p style="border: 0;">
                    <label for="regulation_number_-1">Regulation Number</label>
                    <input type="text" name="_regulation[-1][rg_number]" id="_regulation_number_-1" value="">
                </p>
                <p style="border: 0;">
                    <label for="regulation_description_-1">Regulation Description</label>
                    <input type="text" name="_regulation[-1][rg_description]" id="_regulation_description_-1" value="">
                </p>
            </div>
        </div>

        <div class="cboth"></div>

        <?php if ($this->questionsErrors): ?>
            <ul><li>Questions error</li></ul>
        <?php endif; ?>

        <?php foreach ($this->questions as $question): ?>
            <p>
                <?php echo $question->blq_title ?><br />
                <?php
                if (isset($questionsFormAnswers[$question->blq_id])):
                    $checked = isset($questionsFormAnswers[$question->blq_id]) && ($questionsFormAnswers[$question->blq_id] == 2) ? ' CHECKED ' : '';
                else:
                    $checked = $question->_bla_value == 2 ? ' CHECKED ' : '';
                endif;
                ?>
                <?php
                    $qLabel = $question->blq_order == 10 ? 'In 60 days' : 'Yes';
                    $disabled = $this->blId ? ' DISABLED ' : '';
                ?>
                <input <?php echo $checked ?> <?php echo $disabled ?> type="radio" name="questions[<?php echo $question->blq_id ?>]" id="q<?php echo $question->blq_id ?>2" value="2" class="radio" style="margin-top: 10px; margin-bottom: 20px;" /> <label for="q<?php echo $question->blq_id ?>2" class="checkbox fleft" style="margin-top: 10px; margin-bottom: 20px;"><?php echo $qLabel ?> &nbsp; &nbsp; &nbsp; </label>

                <?php
                if (isset($questionsFormAnswers[$question->blq_id])):
                    $checked = isset($questionsFormAnswers[$question->blq_id]) && ($questionsFormAnswers[$question->blq_id] == 1) ? ' CHECKED ' : '';
                else:
                    $checked = $question->_bla_value == 1 ? ' CHECKED ' : '';
                endif;
                ?>

                <?php
                    $qLabel = $question->blq_order == 10 ? '60 days after end of year' : 'No';
                ?>
                <input <?php echo $checked ?> <?php echo $disabled ?> type="radio" name="questions[<?php echo $question->blq_id ?>]" id="q<?php echo $question->blq_id ?>1" value="1" class="radio" style="margin-top: 10px; margin-bottom: 20px;" /> <label for="q<?php echo $question->blq_id ?>1" class="checkbox fleft" style="margin-top: 10px; margin-bottom: 20px;"><?php echo $qLabel ?> &nbsp; &nbsp; &nbsp; </label>
            </p>
        <?php endforeach; ?>
        
        <div class="cboth"></div>

        <p style="border: 0;">
           <?php $fn = $form->get('bl_approver_u_id')->setOptions($companyUsers);
            echo '<strong>' . $this->formLabel($fn->setLabelAttributes(array('style'=>'width:190px'))) . '</strong>';
            echo $this->formSelect($fn->setAttributes(array('class'=>'form-control', 'id'=>'bl_approver_u_id')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        <p style="border: 0;">
            <?php
                $fn = $form->get('bl_initials_approver');
                echo $this->formLabel($fn->setLabelAttributes(array('style'=>'width:190px')));
                echo $this->formInput($fn->setAttributes(array('class'=>'form-control required', 'id'=>'bl_initials_approver')));
                echo $this->formElementErrors($fn);
            ?>
        </p>

        <div class="cboth"></div>

        <p style="border: 0;">
           <?php $fn = $form->get('bl_accepter_u_id')->setOptions($companyUsers);
            echo '<strong>' . $this->formLabel($fn->setLabelAttributes(array('style'=>'width:190px'))) . '</strong>';
            echo $this->formSelect($fn->setAttributes(array('class'=>'form-control', 'id'=>'bl_accepter_u_id')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        <p style="border: 0;">
            <?php
                $fn = $form->get('bl_initials');
                echo $this->formLabel($fn->setLabelAttributes(array('style'=>'width:190px')));
                echo $this->formInput($fn->setAttributes(array('class'=>'form-control required', 'id'=>'bl_initials')));
                echo $this->formElementErrors($fn);
            ?>
        </p>
        <p style="border: 0;">
            <strong style="line-height: 30px;">Notes</strong><br />
            <?php
            $fn = $formNote->get('note_text');
            echo $this->formTextarea($fn->setAttributes(array('style' => 'width: 570px;')));
            echo $this->formElementErrors($fn);
            ?>

        </p>
        <p style="border: 0;">
            Please upload your documents from your Breach Investigation:
        </p>
        <p style="border: 0;">
            <strong style="line-height: 30px;">Additional Attachments</strong><br />
            <a id="browseFile" href="javascript:" class="button"><i class="fa fa-plus-circle"></i> Browse Files...</a>
            <br /><br /><br />
        </p>

        <div class="cboth"></div>
        <div id="filesToUploadBox">

        </div>
        
        <div class="cboth"></div>
        
        <?php if ($this->blId && is_object($notes) && ($notes->count())): ?>
            <?php foreach ($notes as $note): ?>
                <div class="note">
                    <strong><?php echo $note->_username ?></strong> <small> on <?php echo $note->_note_create_date_format ?></small><br />
                    <p>
                        <?php echo $note->note_text ?><br />
                        <?php if ($note->_files != ''): ?>
                            <?php
                            $_files = explode(',', $note->_files);
                            ?>
                            <strong>Attachments:</strong><br />
                            <?php foreach ($_files as $_file): ?>
                                <?php
                                $_file = explode('::', $_file);
                                $_fileName = $_file[0];
                                $_fileId = $_file[1];
                                ?>
                                <span style="float: left; margin-right: 5px;" class="<?php echo !$this->isPdf ? $this->renderPictoIcon($_fileName) : ''; ?>"></span><a href="/files/get/note/<?php echo $note->note_id ?>/<?php echo $_fileId ?>" class="" target="_blank"><?php echo $_fileName ?></a><br/>

                            <?php endforeach; ?>
                        <?php endif; ?>
                    </p>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
        
        <div class="cboth"></div>
        
        <div class="form-buttons">
            <input type="submit" value="Save" class="form-button" />
            <div class="fleft">or</div>
            <a href="/breachlog/list" class="cancel">Cancel</a>
        </div>

    <?php echo $this->form()->closeTag() ?>
</div>

<div class="cboth"><br /></div>


<script type="text/javascript">
    jQuery(function() {
        $('#breachlog').validate();
        $('input[name="u_zip"]').mask("99999");
        //$('input[name="bl_size"]').mask("99999");

        $('#q22, #q21').change(function() {
            var isChecked = $('#q22').attr('checked');
            if (isChecked == 'checked') {
                $('#q32, #q31').parent().hide().end().prop('disabled', true);
            } else {
                $('#q32, #q31').parent().show().end().prop('disabled', false);
            }
        });

        $('#q22, #q21').change();
        $('#bl_size').change(function(){
            if($('#q102').is(':disabled')) return;
            if(parseFloat($('#bl_size').val()) >= 500) {
                $('#q102').attr('checked', 'checked');
            } else {
                $('#q101').attr('checked', 'checked');
            }
        });
        
        $("#company").change(function(){
            getCompanyUsers()
        });

        function getCompanyUsers()
        {
            var cId = $("#company option:selected").val();
            
            if(cId != undefined && cId != '') {
                $.ajax({
                    type:"GET",
                    url:"/breachlog/getcompanyusers/" + cId,
                    success: function(data){
                        var html = '<option value="">Please Select</option>';
                        $.each(data, function(index, value) {
                            html += '<option value="' + value.u_id + '">' + value.u_firstname + ' ' + value.u_lastname + '</option>';
                        });
                        $('#bl_accepter_u_id, #bl_approver_u_id').html(html);
                    }
                });
            }
        }
        
        var browseFilesCounter = 0;
        
        $(document).ready(function() {
            $('#browseFile').click(function() { 
                if(browseFilesCounter > 0) {
                    var prevFile = $('#file' + (browseFilesCounter - 1)).val();
                    if(prevFile == undefined || prevFile == '') {
                        $('#file' + (browseFilesCounter - 1)).click();
                        return;
                    }
                }
                
                $('#filesToUploadBox').append('<input type="file" name="notesFiles[]" id="file' + browseFilesCounter + '" />');

                $('#file' + browseFilesCounter).click();
                browseFilesCounter++;
            });
            
            $( "#bl_date_of_occurrence, #bl_date_invest_start, #bl_date_invest_complete" ).datepicker({dateFormat: 'mm/dd/yy'});
        });

        function searchRegulations()
        {
            var value = $('#_search_regulation').val().toLowerCase();
            if (value) {
                $('#_regulations_table tbody tr').hide();
                $('#_regulations_table th:nth-child(3), #_regulations_table td:nth-child(3)').show();
                $('#_regulations_table tbody td').each(function(i, v) {
                    var $td = $(v);
                    if ($td.text().toLowerCase().indexOf(value) != -1) {
                        $td.closest('tr').show();
                    }
                });
            } else {
                $('#_regulations_table th:nth-child(3), #_regulations_table td:nth-child(3)').hide();
                $('#_regulations_table tbody tr').show();
            }
        }

        $('#_search_regulation').keyup(function(){
            searchRegulations();
        });
        searchRegulations();

        $('#_regulations_table tbody tr').click(function() {
            $(this).toggleClass('tr-selected');
            regulationHandle();
        });

        function regulationHandle()
        {
            $('div[id^=_regulation_wrap_]').css('display', 'none');

            $('#_regulations_table tbody tr').each(function(i, v){
                if ($(v).hasClass('tr-selected')) {
                    $('#_regulation_wrap_' + $(v).prop('id')).css('display', 'block');
                }
            });
        }

        var cur_regulations_hidden = $('#_bl_cur_regulations_hidden').val();
        if (cur_regulations_hidden) {
            var cur_regulations = cur_regulations_hidden.split(',');
            for (var i = 0; i <  cur_regulations.length; i++) {
                $('#_regulations_table tbody tr#' + cur_regulations[i]).toggleClass('tr-selected');
            };
            regulationHandle();
        }

        $('#breachlog').submit(function(e) {
            var value = '';
            $('#_regulations_table tbody tr.tr-selected').each(function(i, v) {
                value += $(v).prop('id') + ',';
            });
            if (value) {
                value = value.slice(0, -1);
            }
            $('#_bl_cur_regulations_hidden').val(value);
        });
    });
</script>
