<?php

// within a view script
$form = $this->form;
$form->prepare();

// Assuming the "contact/process" route exists...
$form->setAttribute('action', '/breachlog/edit');

// Set the method attribute for the form
$form->setAttribute('method', 'post');

// Render the opening tag
?>


    <div class="page-title">
        <h1 class="fleft">Add New Suspected Breach Incident Log</h1>
        <div class="cboth"></div>
    </div>

    <p></p>

<div class="col-left">
    <form action="/breachlog/edit/<?php echo $this->blId ?>" method="post" name="breachlog" id="breachlog">
        <?php
            $fn = $form->get('bl_id');
            echo $this->formHidden($fn);
        ?>

        <?php
            $authService = new \Zend\Authentication\AuthenticationService();
            $authService->setStorage(new \SanAuth\Model\MyAuthStorage('hipaa'));
            $identity = $authService->getIdentity();
        ?>
        <?php if (in_array($identity['u_role_id'], array(\Admin\Model\User::ROLE_CONSULTANT, \Admin\Model\User::ROLE_SENIOR_CONSULTANT))): ?>
            <p>
                <?php $fn = $form->get('bl_c_id');
                echo $this->formLabel($fn);
                echo $this->formSelect($fn->setAttributes(array('class'=>'form-control required')));
                echo $this->formElementErrors($fn);
                ?>
            </p>
        <?php endif; ?>

        <p>
            <?php
            $fn = $form->get('bl_name');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        
        <p>
            <?php
            $fn = $form->get('bl_invest_led_by');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <?php
            $fn = $form->get('bl_date_of_occurrence');
            if ($this->blObj):
                $fn->setValue($this->formatDateA($this->blObj->bl_date_of_occurrence, false, true));
            endif;
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required', 'id' => 'bl_date_of_occurrence')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        
        <p>
            <?php
            $fn = $form->get('bl_date_invest_start');
            if ($this->blObj):
                $fn->setValue($this->formatDateA($this->blObj->bl_date_invest_start, false, true));
            endif;
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required', 'id' => 'bl_date_invest_start')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        
        <p>
            <?php
            $fn = $form->get('bl_date_invest_complete');
            if ($this->blObj):
                $fn->setValue($this->formatDateA($this->blObj->bl_date_invest_complete, false, true));
            endif;
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required', 'id' => 'bl_date_invest_complete')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <?php
            $fn = $form->get('bl_size');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control', 'id'=>'bl_size')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <label style="width: 300px;">Description of the Breach Event</label><br />
            <?php
            $fn = $form->get('bl_description');
            echo $this->formTextarea($fn->setAttributes(array('class'=>'', 'style' => 'width: 450px; height: 85px;')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <?php if ($this->questionsErrors): ?>
            <ul><li>Questions error</li></ul>
        <?php endif; ?>

        <?php foreach ($this->questions as $question): ?>
            <p>
                <?php echo $question->blq_title ?><br />
                <?php
                if (isset($questionsFormAnswers[$question->blq_id])):
                    $checked = isset($questionsFormAnswers[$question->blq_id]) && ($questionsFormAnswers[$question->blq_id] == 2) ? ' CHECKED ' : '';
                else:
                    $checked = $question->_bla_value == 2 ? ' CHECKED ' : '';
                endif;
                ?>
                <?php
                    $qLabel = $question->blq_order == 10 ? 'In 60 days' : 'Yes';
                    $disabled = $this->blId ? ' DISABLED ' : '';
                ?>
                <input <?php echo $checked ?> <?php echo $disabled ?> type="radio" name="questions[<?php echo $question->blq_id ?>]" id="q<?php echo $question->blq_id ?>2" value="2" class="radio" style="margin-top: 10px; margin-bottom: 20px;" /> <label for="q<?php echo $question->blq_id ?>2" class="checkbox fleft" style="margin-top: 10px; margin-bottom: 20px;"><?php echo $qLabel ?> &nbsp; &nbsp; &nbsp; </label>

                <?php
                if (isset($questionsFormAnswers[$question->blq_id])):
                    $checked = isset($questionsFormAnswers[$question->blq_id]) && ($questionsFormAnswers[$question->blq_id] == 1) ? ' CHECKED ' : '';
                else:
                    $checked = $question->_bla_value == 1 ? ' CHECKED ' : '';
                endif;
                ?>

                <?php
                    $qLabel = $question->blq_order == 10 ? '60 days after end of year' : 'No';
                ?>
                <input <?php echo $checked ?> <?php echo $disabled ?> type="radio" name="questions[<?php echo $question->blq_id ?>]" id="q<?php echo $question->blq_id ?>1" value="1" class="radio" style="margin-top: 10px; margin-bottom: 20px;" /> <label for="q<?php echo $question->blq_id ?>1" class="checkbox fleft" style="margin-top: 10px; margin-bottom: 20px;"><?php echo $qLabel ?> &nbsp; &nbsp; &nbsp; </label>
            </p>
        <?php endforeach; ?>
        
        <div class="cboth"></div>

        <p style="border: 0;"><strong>Reviewed and approved by</strong></p>
        <?php if (!$this->blId): ?>
            <p style="border: 0;">
                <?php
                    $fn = $form->get('bl_initials_approver');
                    echo $this->formLabel($fn);
                    echo $this->formInput($fn->setAttributes(array('class'=>'form-control required', 'id'=>'bl_initials_approver')));
                    echo $this->formElementErrors($fn);
                ?>
            </p>
        <?php else: ?>
            <p style="border: 0;">
                <label>Initials: <?php echo $this->blObj->bl_initials_approver ?></label>
            </p>
        <?php endif; ?>

        <div class="cboth"></div>

        <p><strong>Agreed to and accepted by</strong></p>
        <?php if (!$this->blId): ?>
            <p style="border: 0;">
                <?php
                    $fn = $form->get('bl_initials');
                    echo $this->formLabel($fn);
                    echo $this->formInput($fn->setAttributes(array('class'=>'form-control required', 'id'=>'bl_initials')));
                    echo $this->formElementErrors($fn);
                ?>
            </p>
            </p>
        <?php else: ?>
            <p style="border: 0;">
                <label>Initials: <?php echo $this->blObj->bl_initials ?></label>
            </p>
        <?php endif; ?>
        
        <div class="cboth"></div>
        <div class="form-buttons">
            <input type="submit" value="Save" class="form-button" />
            <div class="fleft">or</div>
            <a href="/breachlog/list" class="cancel">Cancel</a>
        </div>

    <?php echo $this->form()->closeTag() ?>
</div>

<div class="cboth"><br /></div>


<script type="text/javascript">
    jQuery(function() {
        $('#breachlog').validate();
        $('input[name="u_zip"]').mask("99999");
        //$('input[name="bl_size"]').mask("99999");
        jQuery("#bl_date_of_occurrence, #bl_date_invest_start, #bl_date_invest_complete").mask("99/99/9999");

        $('#q22, #q21').change(function() {
            var isChecked = $('#q22').attr('checked');
            if (isChecked == 'checked') {
                $('#q32').parent().hide();
            } else {
                $('#q32').parent().show();
            }
        });

        $('#q22, #q21').change();
        $('#bl_size').change(function(){
            if($('#q102').is(':disabled')) return;
            if(parseFloat($('#bl_size').val()) >= 500) {
                $('#q102').attr('checked', 'checked');
            } else {
                $('#q101').attr('checked', 'checked');
            }
        });
    });
</script>
