<?php
$urlOrder = $order == 'ASC' ? 'DESC' : 'ASC';
$authService = new \Zend\Authentication\AuthenticationService();
$authService->setStorage(new \SanAuth\Model\MyAuthStorage('hipaa'));
$identity = $authService->getIdentity();
$isClientRole = $identity['u_role_id'] == 5 ? 1 : 0;
?>

<div class="page-title">
    <h1 class="fleft">Suspected Incident Logs</h1>
    <a href="/breachlog/edit" class="button"><i class="fa fa-plus-circle"></i> Add New Incident Log</a>
    <div class="cboth"></div>
</div>

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>

<p></p>

<table id="incident-log-list-table" cellpadding="0" cellspacing="0">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <?php if (!$isClientRole): ?>
                <th>Client</th>
            <?php endif; ?>
            <th>Reportable</th>
            <th>Date</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->paginator as $bl): ?>
            <tr>
                <td><?php echo $bl->bl_id ?></td>
                <td><a href="/breachlog/edit/<?php echo $bl->bl_id ?>"><?php echo $bl->bl_name ?></a></td>
                <?php if (!$isClientRole): ?>
                    <td><?php echo stripslashes($bl->_client_name) ?></td>
                <?php endif; ?>
                <td><?php echo $bl->bl_reportable ? 'Yes' : 'No' ?></td>
                <td><?php echo ($bl->bl_date_of_occurrence != '0000-00-00 00:00:00') ? $this->formatDateA($bl->bl_date_of_occurrence) : '' ?></td>
                <td style="white-space: nowrap;" class="aright">
										<?php if ($bl->bl_accepter_u_id === 0 || $bl->bl_accepter_u_id === NULL): ?>
											<a href="/breachlog/edit/<?php echo $bl->bl_id ?>" title="Edit"><i class="fa fa-pencil"></i></a> &nbsp;
										<?php endif; ?>										
										<!--even though this is /breachlog/edit send a url var type=view. 
											this will make it read only for anybody to view.-->
                    <a href="/breachlog/edit/<?php echo $bl->bl_id . '?type=view' ?>" title="View Only"><i class="fa fa-book"></i></a> &nbsp;
                    <?php if ($identity['u_role_id'] == \Admin\Model\User::ROLE_ADMIN): ?>
                        <?php if ($bl->bl_active): ?>
                            <?php $deleteUrl = '/breachlog/delete/' . $bl->bl_id; ?>
                            <a href="#confirmation-box-modal" onclick="$('#deleteYes').attr('href', '<?php echo $deleteUrl ?>')" class="confirmation-modal i-delete"><i class="fa fa-trash-o">
                        <?php else: ?>
                            <a href="/breachlog/unarchive/<?php echo $bl->bl_id  ?>" class="">Unarchive</a>
                        <?php endif; ?>
                    <?php else: ?>
                        <?php $deleteUrl = '/breachlog/delete/' . $bl->bl_id; ?>
                        <a href="#confirmation-box-modal" onclick="$('#deleteYes').attr('href', '<?php echo $deleteUrl ?>')" class="confirmation-modal i-delete"><i class="fa fa-trash-o"></i></a>
                    <?php endif; ?>
                </td>
            </tr>

        <?php endforeach; ?>
    </tbody>
</table>

<script>

    $(document).ready( function () {
        $('#incident-log-list-table').DataTable(
            {
                "order": [],
                "columnDefs": [
                    { "type": "date", "targets": 4},
                    { "orderable": false, "targets": 5 }
                ]
            }
        );
        $('.dataTables_filter input[type="search"]').
        css({'width':'95%','display':'inline-block'});
    } );

</script>

<div class="cboth"><br /></div>