<?php

$form = $this->form;
$form->setAttribute('action', $this->url('auth', array('action' => 'forgotpassword')));
$form->prepare();

?>

<form action="/auth/forgotpassword" method="post" id="login-form" name="login-form">
    <?php if (isset($flashMessagesErrors) && count($flashMessagesErrors)) : ?>
        <div class="flash-container">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <?php foreach ($flashMessagesErrors as $msg) : ?>
                            <div class="alert alert-flash alert-dismissable center alert-danger">
                                <button type="button" class="close" aria-hidden="true">&times;</button>
                                <strong>
                                    <?php echo $msg; ?>
                                </strong>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        </div>
    <?php endif; ?>


    <label for="email">Email</label>
    <?php $fn = $form->get('u_email'); ?>
    <?php
        echo $this->formInput($fn->setAttributes(array('class' => '', "required" => "true", "type" => "text")));
        echo $this->formElementErrors($fn);
    ?>

    <div class="cboth"></div>
    <a href="/" class="fleft">Return to login</a>
    <input type="submit" value="Send &nbsp; &rarr;" class="button" />
<?php echo $this->form()->closeTag() ?>