<form action="/auth/authenticate" method="post" id="login-form" name="login-form">
    <?php
        $fn = $form->get('u_email');
        echo $this->formLabel($fn);
        echo $this->formInput($fn->setAttributes(array('class'=>'form-control', "required" => "true")));
    ?>

    <?php
        $fn = $form->get('u_password');
        echo $this->formLabel($fn);
        echo $this->formInput($fn->setAttributes(array('class'=>'form-control', "required" => "true")));
    ?>

    <?php if($this->showCaptcha): ?>
        <?php
            $fn = $form->get('captcha');
            echo $this->formLabel($fn);
        ?>
        <div class="login-captcha-wrap">
            <?php
            echo $this->formElement($fn->setAttributes(array('class'=>'form-control', "required" => "true")));
            ?>
        </div>
    <?php endif; ?>

    <input type="checkbox" value="1" name="u_remember_me" id="remember" class="checkbox" />
    <label for="remember" class="checkbox">Remember me on this computer</label>
    <div class="cboth"></div>
    <a href="/auth/forgotpassword" class="fleft">Forgot your password?</a>
    <input type="submit" value="Login &nbsp; &rarr;" class="button" />
</form>