<?php

$form = $this->form;
$form->setAttribute('action', $this->url('auth', array('action' => 'newpassword', 'id' => $id, 'hash' => $hash)));
$form->prepare();

?>

<form action="/auth/newpassword/<?php echo $id ?>/<?php echo $hash ?>" method="post" id="login-form" name="login-form">
    <?php if (isset($flashMessagesErrors) && count($flashMessagesErrors)) : ?>
        <div class="flash-container">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <?php foreach ($flashMessagesErrors as $msg) : ?>
                            <div class="alert alert-flash alert-dismissable center alert-danger">
                                <button type="button" class="close" aria-hidden="true">&times;</button>
                                <strong>
                                    <?php echo $msg; ?>
                                </strong>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        </div>
    <?php endif; ?>


    <label for="email">Password</label>
    <?php $fn = $form->get('u_password'); ?>
    <?php
    echo $this->formInput($fn->setAttributes(array('class' => '', "required" => "true", "type" => "password")));
    echo $this->formElementErrors($fn);
    ?>
    <label for="email">Password conf.</label>
    <?php $fn = $form->get('u_password_repeat'); ?>
    <?php
    echo $this->formInput($fn->setAttributes(array('class' => '', "required" => "true", "type" => "password")));
    echo $this->formElementErrors($fn);
    ?>

    <div class="cboth"></div>
    <input type="submit" value="Change password &nbsp; &rarr;" class="button" />
<?php echo $this->form()->closeTag() ?>

