<?php
$urlOrder = $order == 'ASC' ? 'DESC' : 'ASC';
$authService = new \Zend\Authentication\AuthenticationService();
$authService->setStorage(new \SanAuth\Model\MyAuthStorage('hipaa'));
$identity = $authService->getIdentity();
?>

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>

<div class="page-title">
    <h1 class="fleft">Clients</h1>
    <a href="<?php echo $this->url('client', array('action' => 'list', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => 0, 'activeFilter' => $activeFilter)); ?>" class="label <?php echo $roleFilter == 0 ? ' selected ' : '' ?>">All</a>
    <a href="<?php echo $this->url('client', array('action' => 'list', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => 1, 'activeFilter' => $activeFilter)); ?>" class="label <?php echo $roleFilter == 1 ? ' selected ' : '' ?>">Organizations</a>
    <a href="<?php echo $this->url('client', array('action' => 'list', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => 2, 'activeFilter' => $activeFilter)); ?>" class="label <?php echo $roleFilter == 2 ? ' selected ' : '' ?>">Contacts</a>
    <?php if (in_array($identity['u_role_id'], array(\Admin\Model\User::ROLE_ADMIN, \Admin\Model\User::ROLE_SENIOR_CONSULTANT))
        || $identity['u_company_id_admin']) : ?>
    <a href="<?php echo $this->url('client', array('action' => 'list', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => $roleFilter, 'activeFilter' => 1)); ?>" class="label <?php echo $activeFilter == 1 ? ' selected ' : '' ?>">Active</a>
    <a href="<?php echo $this->url('client', array('action' => 'list', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => $roleFilter, 'activeFilter' => 2)); ?>" class="label <?php echo $activeFilter == 2 ? ' selected ' : '' ?>">Inactive</a>
    <?php endif;?>
    <?php if ($identity['u_role_id'] != \Admin\Model\User::ROLE_TRIAL) : ?>
    <a href="/client/edit" class="button"><i class="fa fa-plus-circle"></i> Add New Contact</a>
    <?php if(in_array($identity['u_role_id'], array(\Admin\Model\User::ROLE_ADMIN, \Admin\Model\User::ROLE_SENIOR_CONSULTANT, \Admin\Model\User::ROLE_PARTIAL))): ?>
        <a href="/company/edit" class="button"><i class="fa fa-plus-circle"></i> Add New Organization</a>
    <?php endif;?>
    <?php endif;?>
    <div class="cboth"></div>
</div>

<p></p>

<table id="client-list" cellpadding="0" cellspacing="0">
    <thead>
        <tr>
            <?php $classSort = ($order_by == 'id') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>ID</th>
            <th>Type </th>

            <?php $classSort = ($order_by == 'name') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>Name</th>

            <?php $classSort = ($order_by == 'company') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>Organization</th>
            <th>Phone</th>
            <th>Created</th>
            <th>Renewal Date</th>
            <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->paginator as $company): ?>
            <?php $isUser = ($company->u_id > 0) ? 1 : 0; ?>
            <?php
           // echo $company->_c_active;
            ?>

            <tr>
                <td><?php echo ($isUser) ? $company->u_id : $company->c_id ?></td>
                <td><span class="<?php echo ($isUser) ? 'i-contact' : 'i-company' ?>"></span></td>
                <td>
                    <span class="fleft"><a href="/client/edit/<?php echo ($isUser) ? $company->u_id : '' ?>"><?php echo ($isUser) ? $company->u_firstname . ' ' . $company->u_lastname : '' ?></a></span>
                    <?php if ($isUser): ?>
                        <?php if ($company->u_id == $company->c_primary_contact_u_id): ?>
                            <span class="label primary">Primary Contact</span>
                        <?php endif; ?>
                    <?php endif; ?>
                </td>
                <td>
                    <?php if ($company->_c_active || ($identity['u_role_id'] == \Admin\Model\User::ROLE_ADMIN)): ?>
                        <a href="/company/edit/<?php echo $company->c_id ?>"><?php echo $company->c_name ?></a>
                    <?php endif; ?>
                </td>
                <td><?php echo ($isUser) ? '' : $company->c_phone ?></td>
                <td><?php echo ($isUser) ? '' : ($company->c_create_date != '0000-00-00 00:00:00') ? $this->formatDateA($company->c_create_date) : '' ?></td>
                <td><?php echo ($isUser) ? '' : ($company->c_renewal_date != '0000-00-00 00:00:00') ? $this->formatDateA($company->c_renewal_date) : '' ?></td>                
                <td class="aright">
                    <a href="/<?php echo ($isUser) ? 'client' : 'company' ?>/edit/<?php echo ($isUser) ? $company->u_id : $company->c_id ?>" title="Edit"><i class="fa fa-pencil"></i></a> &nbsp;
                    <?php if ($identity['u_role_id'] != \Admin\Model\User::ROLE_TRIAL) : ?>
                        <?php if ($company->_c_active): ?>
                            <?php $deleteUrl = '/' . (($isUser) ? 'client' : 'company') . '/delete/' . (($isUser) ? $company->u_id : $company->c_id); ?>
                            <a href="#deactivation-box-modal" onclick="$('#deactivateYes').attr('href', '<?php echo $deleteUrl ?>')" class="confirmation-modal i-delete" title="Deactivate"><i class="fa fa-trash-o"></i></a>
                        <?php else: ?>
                            <?php $unarchiveUrl = '/' . (($isUser) ? 'client' : 'company') . '/unarchive/' . (($isUser) ? $company->u_id : $company->c_id); ?>
                            <a href="<?php echo $unarchiveUrl ?>" class="confirmation-modal i-delete">Activate</a>
                        <?php endif; ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script>
	$(document).ready( function () {
		$('#client-list').DataTable({
			"order": [[ 2, "asc" ]],
			"columnDefs": [
				{"type": "num", "targets": 0},
				{"type": "date", "targets": 5},
				{"type": "date", "targets": 6},
				{ "orderable": false, "targets": 7 }
			]
		});
		$('.dataTables_filter input[type="search"]').
			css({'width':'95%','display':'inline-block'});
	});
</script>

<div class="cboth"><br /></div>