<?php

// within a view script
$form = $this->form;
$form->prepare();

// Assuming the "contact/process" route exists...
$form->setAttribute('action', '/user/account');

// Set the method attribute for the form
$form->setAttribute('method', 'post');

// Render the opening tag
?>

<div id="canvas">

    <div class="page-title">
        <h1 class="fleft">My Profile</h1>
        <div class="cboth"></div>
    </div>

    <div class="col-left">

        <form action="/user/account/" method="post" name="user" id="user">
            <h2>New password</h2>
            <p>
                <label for="u_password">New password</label>
                <input type="text" value="" class="form-control" name="u_password" value="<?= $this->password ?>">
                <span class="description_text">"Must contain at least 8 characters, at least one upper case letter, at lease 1 lower case character, at least one number, at least one special character"</span>
            </p>
            <?php
            if ($this->passwordWrong == 1): ?>
                <ul><li>Password doesn’t match the requirements above</li></ul>
            <?php endif; ?>
            <p>
                <label for="u_confirm_password">Confirm password</label>
                <input type="text" value="" class="form-control" name="u_confirm_password"
                    value="<?= $this->confirm_password ?>">
            </p>
            <?php
            if ($this->passwordWrong == 2): ?>
                <ul><li>Passwords do not match</li></ul>
            <?php endif; ?>

            <h2>User Details</h2>

            <?php
            $fn = $form->get('u_id');
            echo $this->formHidden($fn);
            ?>

            <p>
                <?php
                $fn = $form->get('u_firstname');
                echo $this->formLabel($fn);
                echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
                echo $this->formElementErrors($fn);
                ?>
            </p>
            <p>
                <?php
                $fn = $form->get('u_lastname');
                echo $this->formLabel($fn);
                echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
                echo $this->formElementErrors($fn);
                ?>
            </p>
            <p>
                <?php
                $fn = $form->get('u_title');
                echo $this->formLabel($fn);
                echo $this->formInput($fn->setAttributes(array('class'=>'form-control')));
                echo $this->formElementErrors($fn);
                ?>
            </p>
            <p>
                <?php
                $fn = $form->get('u_office_phone');
                echo $this->formLabel($fn);
                echo $this->formInput($fn->setAttributes(array('class'=>'phone')));
                echo $this->formElementErrors($fn);
                ?>

                <?php
                $fn = $form->get('u_office_phone_inner');
                echo $this->formInput($fn->setAttributes(array('class'=>'ext')));
                echo $this->formElementErrors($fn);
                ?>
            </p>
            <p>
                <?php
                $fn = $form->get('u_direct_phone');
                echo $this->formLabel($fn);
                echo $this->formInput($fn->setAttributes(array('class'=>'phone')));
                echo $this->formElementErrors($fn);
                ?>
                <?php
                $fn = $form->get('u_direct_phone_inner');
                echo $this->formInput($fn->setAttributes(array('class'=>'ext')));
                echo $this->formElementErrors($fn);
                ?>
            </p>
            <p>
                <?php
                $fn = $form->get('u_cell_phone');
                echo $this->formLabel($fn);
                echo $this->formInput($fn->setAttributes(array('class'=>'form-control')));
                echo $this->formElementErrors($fn);
                ?>
            </p>
            <p>
                <?php
                $fn = $form->get('u_other_phone');
                echo $this->formLabel($fn);
                echo $this->formInput($fn->setAttributes(array('class'=>'phone')));
                echo $this->formElementErrors($fn);
                ?>
                <?php
                $fn = $form->get('u_other_phone_inner');
                echo $this->formInput($fn->setAttributes(array('class'=>'ext')));
                echo $this->formElementErrors($fn);
                ?>
            </p>
            <p>
                <?php
                $fn = $form->get('u_fax');
                echo $this->formLabel($fn);
                echo $this->formInput($fn->setAttributes(array('class'=>'form-control')));
                echo $this->formElementErrors($fn);
                ?>
            </p>

            <p>
                <label for="u_email">Email</label>
                <label for="u_email"><?php echo $this->email ?></label>
            </p>

            <h2>Address</h2>

            <p>
                <?php
                $fn = $form->get('u_address1');
                echo $this->formLabel($fn);
                echo $this->formInput($fn->setAttributes(array('class'=>'form-control')));
                echo $this->formElementErrors($fn);
                ?>
            </p>
            <p>
                <?php
                $fn = $form->get('u_address2');
                echo $this->formLabel($fn);
                echo $this->formInput($fn->setAttributes(array('class'=>'form-control')));
                echo $this->formElementErrors($fn);
                ?>
            </p>
            <p>
                <?php
                $fn = $form->get('u_city');
                echo $this->formLabel($fn);
                echo $this->formInput($fn->setAttributes(array('class'=>'form-control')));
                echo $this->formElementErrors($fn);
                ?>
            </p>
            <p>
                <?php $fn = $form->get('u_state_id');
                echo $this->formLabel($fn);
                echo $this->formSelect($fn->setAttributes(array('class'=>'form-control')));
                echo $this->formElementErrors($fn);
                ?>
            </p>
            <p>
                <?php
                $fn = $form->get('u_zip');
                echo $this->formLabel($fn);
                echo $this->formInput($fn->setAttributes(array('class'=>'form-control')));
                echo $this->formElementErrors($fn);
                ?>
            </p>

            <div class="cboth"></div>
            <div class="form-buttons">
                <input type="submit" value="Save" class="form-button" />
                <div class="fleft">or</div>
                <a href="/admin/users" class="cancel">Cancel</a>
            </div>

            <?php echo $this->form()->closeTag() ?>

    </div>

    <div class="cboth"><br /></div>

</div>

<script>
    jQuery(document).ready(function() {
        $('#user').validate();
        //Conditional logic for account types
        jQuery('#seniorConsult').hide();
        jQuery('#accountType').change(function() {
            jQuery('#seniorConsult').hide();
            if (jQuery(this).val() == 3) {
                jQuery('#seniorConsult').show();
            }
        });
        jQuery('#accountType').change();

        $('input[name="u_office_phone"], input[name="u_direct_phone"], input[name="u_other_phone"], input[name="u_fax"]').mask("(999) 999-9999");
        $('input[name="u_zip"]').mask("99999");
    });

</script>