<?php

// within a view script
$form = $this->form;
$form->prepare();

// Assuming the "contact/process" route exists...
$form->setAttribute('action', '/user/registration');

// Set the method attribute for the form
$form->setAttribute('method', 'post');

// Render the opening tag
?>

<div class="page-title">
    <h1 class="fleft">Register</h1>
    <div class="cboth"></div>
</div>

<div class="col-left">

    <form action="/user/registration" method="post" name="user" id="registration">
        <p style="border: 0">
            <?php
            $fn = $form->get('u_firstname');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        <p>
            <?php
            $fn = $form->get('u_lastname');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        <p>
            <?php
            $fn = $form->get('u_company');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        <p>
            <?php
            $fn = $form->get('u_office_phone');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'phone')));
            echo $this->formElementErrors($fn);
            ?>

            <?php
            $fn = $form->get('u_office_phone_inner');
            echo $this->formInput($fn->setAttributes(array('class'=>'ext')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        <p>
            <?php
            $fn = $form->get('u_direct_phone');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'phone')));
            echo $this->formElementErrors($fn);
            ?>
            <?php
            $fn = $form->get('u_direct_phone_inner');
            echo $this->formInput($fn->setAttributes(array('class'=>'ext')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        <p>
            <?php
            $fn = $form->get('u_cell_phone');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        <p>
            <?php
            $fn = $form->get('u_other_phone');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'phone')));
            echo $this->formElementErrors($fn);
            ?>
            <?php
            $fn = $form->get('u_other_phone_inner');
            echo $this->formInput($fn->setAttributes(array('class'=>'ext')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p id="phoneRequired" style="display: none">
            <label for="" generated="true" class="error">At least 1 phone number is required</label>
        </p>

        <p>
            <?php
            $fn = $form->get('u_email');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required email')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        <p>
            <?php
            $fn = $form->get('u_confirm_email');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required email')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p class="registation_captcha">
            <?php
            $fn = $form->get('captcha');
            echo $this->formLabel($fn);
            ?>
            <div class="registation_captcha_wrap">
                <?php
                echo $this->formElement($fn);
                echo $this->formElementErrors($fn);
                ?>
            </div>
        </p>

        <div class="cboth"></div>
        <div class="form-buttons">
            <input type="submit" value="Save" class="form-button" />
            <div class="fleft">or</div>
            <a href="/admin/users" class="cancel">Cancel</a>
        </div>

        <?php echo $this->form()->closeTag() ?>

</div>

<div class="cboth"><br /></div>


<script>
    jQuery(document).ready(function() {
        $('#registration').validate();

        $('input[name="u_office_phone"], input[name="u_direct_phone"], input[name="u_other_phone"], input[name="u_fax"]').mask("(999) 999-9999");

        $('#registration').submit(function() {
            var isPhoneValid = false;
            $("input[name=u_cell_phone], input[name=u_office_phone], input[name=u_direct_phone], input[name=u_other_phone]").each(function() {
                if ($(this).val() != '') {
                    isPhoneValid = true;
                    return;
                }
            });
            var isValid = $('#registration').valid();
            if (isPhoneValid) {
                $('#phoneRequired, #phoneRequired label').hide();
            } else {
                $('#phoneRequired, #phoneRequired label').show();
            }

            if (isPhoneValid && isValid) {
                return true;
            }
            return false;
        });
    });

</script>