<?php

// within a view script
$form = $this->form;
$form->prepare();

// Assuming the "contact/process" route exists...
$form->setAttribute('action', '/disclosuretrackinglog/edit');

// Set the method attribute for the form
$form->setAttribute('method', 'post');

// Render the opening tag
?>


    <div class="page-title">
        <h1 class="fleft"><?php if($this->dtlId) {?>Edit <?php } else {?>Add New <?php }?>Disclosure Tracking Log</h1>
        <div class="cboth"></div>
    </div>

    <p></p>

<div class="col-left">
    <form action="/disclosuretrackinglog/edit/<?php echo $this->dtlId ?>" method="post" enctype="multipart/form-data" name="disclosuretrackinglog" id="disclosuretrackinglog">
        <?php
            $fn = $form->get('dtl_id');
            echo $this->formHidden($fn);
        ?>
        <?php
            $fn = $form->get('dtl_active');
            echo $this->formHidden($fn);
        ?>

        <p>
            <?php $fn = $form->get('dtl_reference_number');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <?php $fn = $form->get('dtl_patient_name');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        
        <p>
            <?php $fn = $form->get('dtl_medical_record_number');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        
        <p>
            <?php $fn = $form->get('dtl_name_of_requestor');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <?php $fn = $form->get('dtl_address');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <?php $fn = $form->get('dtl_auth_type');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        
        <p>
            <?php $fn = $form->get('dtl_purpose_of_disclosure');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        
        <p>
            <?php $fn = $form->get('dtl_phi_information_disclosed');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <?php $fn = $form->get('dtl_disclosed_by');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <?php $fn = $form->get('dtl_extension_notification');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <?php $fn = $form->get('dtl_copy_of_request');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <?php
            $fn = $form->get('dtl_date_received');
            if ($this->tlObj):
                $fn->setValue($this->formatDateA($this->tlObj->dtl_date_received, false, true));
            endif;
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required', 'id' => 'dtl_date_received', 'readonly' => 'readonly')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <?php
            $fn = $form->get('dtl_date_disclosed');
            if ($this->tlObj):
                $fn->setValue($this->formatDateA($this->tlObj->dtl_date_disclosed, false, true));
            endif;
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required', 'id' => 'dtl_date_disclosed', 'readonly' => 'readonly')));
            echo $this->formElementErrors($fn);
            ?>
        </p>


        <div class="cboth"></div>
        
        <div class="form-buttons">
            <input type="submit" value="Save" class="form-button" />
            <div class="fleft">or</div>
            <a href="/disclosuretrackinglog/list" class="cancel">Cancel</a>
        </div>

    <?php echo $this->form()->closeTag() ?>
</div>

<div class="cboth"><br /></div>


<script type="text/javascript">
    jQuery(function() {
        $('#disclosuretrackinglog').validate();

        $("#dtl_date_received, #dtl_date_disclosed").datepicker({dateFormat: 'mm/dd/yy'});

    });
</script>
