UPDATE business_associates_questions
SET baq_text = '<p style="border: 0;">All covered entities should have organizational policies and procedures that address each requirement in the HIPAA Privacy and Security regulations. These HIPAA policies also need to address the changes outlined in the HITECH Act, enacted as part of ARRA. Further, when the final HITECH Act regulations were published in January 2013, HIPAA policies and procedures needed updating.</p>
<p style="border: 0;">Policies and Procedures need to be maintained in a Master Manual and be available for all employees, on an as needed basis.</p>
<p style="border: 0;">Organizations should also be monitoring employee compliance with HIPAA regulations to ensure that the policies and procedures in place effectively guide employees to correctly follow required HIPAA practices.</p>'
WHERE baq_id = 1;

UPDATE business_associates_questions
SET baq_text = '<p style="border: 0;">The HIPAA Security Rule Administrative Safeguards provisions require covered entities to perform a risk assessment as part of their security management processes.   When analyzing potential risks to the security of PHI, organizations should (1) evaluate each risk''s likelihood and impact; (2) implement appropriate security measures to address identified risks; and (3) document the selected security measures, including an explanation of the reasoning for selection. Any corrective action taken by an organization as a result of the risk assessment findings should be monitored to completion and documented.  While not part of the Privacy Regulations, best practice is to conduct the same risk assessment on your privacy management processes.</p>
<p style="border: 0;">Once the Risk Assessment is completed, a remediation plan is required.  The remediation plan outlines a strategy to remediate the gaps in compliance identified during the Risk Assessment.  The plan should include for each identified threat, the risk score for the threat, the action to be taken to mitigate the threat, the individual responsible in mitigating the threat, and a  target date  for the threat to be mitigated.  Meaningful progress in implementing the mitigation plan is required for compliance.</p>
<p style="border: 0;">As risk assessment is an ongoing process, organizations should update their risk analysis, at least annually, to ensure that risks are appropriately identified, remediated and monitored.   Additionally, internal controls and security measures used should be regularly monitored and evaluated to ensure that PHI is appropriately and effectively protected.</p>'
WHERE baq_id = 3;