<?php
    $urlOrder = $order == 'ASC' ? 'DESC' : 'ASC';
    $authService = new \Zend\Authentication\AuthenticationService();
    $authService->setStorage(new \SanAuth\Model\MyAuthStorage('hipaa'));
    $identity = $authService->getIdentity();
?>

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>


<div class="page-title">
    <h1 class="fleft">Contact(s)</h1>
    <a href="<?php echo $this->url('contact', array('action' => 'list', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => 0, 'activeFilter' => $activeFilter)); ?>" class="label <?php echo $roleFilter == 0 ? ' selected ' : '' ?>">All</a>
    <a href="<?php echo $this->url('contact', array('action' => 'list', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => 1, 'activeFilter' => $activeFilter)); ?>" class="label <?php echo $roleFilter == 1 ? ' selected ' : '' ?>">Contacts</a>
    <?php if (in_array($identity['u_role_id'], array(\Admin\Model\User::ROLE_ADMIN, \Admin\Model\User::ROLE_SENIOR_CONSULTANT))
        || $identity['u_company_id_admin']) : ?>
        <a href="<?php echo $this->url('contact', array('action' => 'list', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => $roleFilter, 'activeFilter' => 1)); ?>" class="label <?php echo $activeFilter == 1 ? ' selected ' : '' ?>">Active</a>
        <a href="<?php echo $this->url('contact', array('action' => 'list', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => $roleFilter, 'activeFilter' => 2)); ?>" class="label <?php echo $activeFilter == 2 ? ' selected ' : '' ?>">Inactive</a>
    <?php endif;?>

    <?php if ($identity['u_role_id'] != \Admin\Model\User::ROLE_TRIAL) : ?>
        <?php if(in_array($identity['u_role_id'], array(\Admin\Model\User::ROLE_ADMIN, \Admin\Model\User::ROLE_SENIOR_CONSULTANT, \Admin\Model\User::ROLE_PARTIAL))): ?>
            <a href="/contact/edit" class="button"><i class="fa fa-plus-circle"></i> Add Contact</a>
        <?php endif;?>
    <?php endif;?>
    <div class="cboth"></div>
</div>

<p></p>

<table id="contact-list" cellpadding="0" cellspacing="0">
    <thead>
        <tr>
            <?php $classSort = ($order_by == 'id') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>ID</th>
            
            <?php $classSort = ($order_by == 'company') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            
            <th>Name</th>
            <th>Title</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Created</th>
            <th>Licensed User</th>
            <th>Organization</th>
            <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->users as $user): ?>
                        
            <tr>
                <td><?php echo $user->u_id ?></td>
                
                <td>
                    <a href="/contact/edit/<?php echo $user->u_id ?>"><?php echo $user->u_firstname . ' ' . $user->u_lastname?></a>
                </td>
                
                <td><?php echo $user->u_title ?></td>
                <td><?php echo $user->u_email ?></td>
                <td><?php echo $user->u_office_phone ?></td>
                <td><?php echo ($user->u_create_date != '0000-00-00 00:00:00') ? $this->formatDateA($user->u_create_date) : '' ?></td>
                <td><?php echo $user->licensed_user ?></td>
                <td><?php echo $user->u_company ?></td>

                <td class="aright">
                    <a href="/<?php echo 'contact' ?>/edit/<?php echo $user->u_id ?>" title="Edit"><i class="fa fa-pencil"></i></a> &nbsp;
                    <?php if ($identity['u_role_id'] != \Admin\Model\User::ROLE_TRIAL) : ?>
                        <?php if ($user->u_active): ?>
                            <?php $deleteUrl = '/' . ('contact') . '/delete/' . ($user->u_id); ?>
                            <a href="#deactivation-box-modal" onclick="$('#deactivateYes').attr('href', '<?php echo $deleteUrl ?>')" class="confirmation-modal i-delete" title="Deactivate"><i class="fa fa-trash-o"></i></a>
                        <?php else: ?>
                            <?php $unarchiveUrl = '/' . ('contact') . '/unarchive/' . ($user->u_id); ?>
                            <a href="<?php echo $unarchiveUrl ?>" class="confirmation-modal i-delete">Activate</a>
                        <?php endif; ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<script>
	$(document).ready( function () {
		$('#contact-list').DataTable({
			"order": [[ 2, "asc" ]],
			"columnDefs": [
				{"type": "num", "targets": 0},
				{"type": "date", "targets": 5},
				{"type": "date", "targets": 6},
				{ "orderable": false, "targets": 7 }
			]
		});
		$('.dataTables_filter input[type="search"]').
			css({'width':'95%','display':'inline-block'});
	});
</script>

<div class="cboth"><br /></div>