<table id="auditbreach_brp" cellpadding="0" cellspacing="0">
    <thead>
        <tr>
            <th>Title</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->bRPPaginator as $brp): ?>
            <tr>
                <td>
                    <a href="<?php echo $this->url('breachremediationplan', array('action' => 'edit', 'id' => $brp->brp_id)); ?>" target="_blank"><?php echo $brp->_client_name ?></a>
                </td>
            </tr>

        <?php endforeach; ?>
    </tbody>
</table>

<?php echo $this->paginationControl(
    $this->bRPPaginator,
    'sliding',
    array('partial/paginator.phtml', 'Reporting'),
    array('route' => 'auditbreach', 'order_by' => $order_by, 'order' => $order, 'page' => $page, 'search' => $search, 'roleFilter' => 1, 'role' => 1, 'controller' => 'reporting', 'action' => 'auditbreachbrp')
);
?>
