<div class="page-title">
    <h1 class="fleft">Plans Progress</h1>
    <div class="cboth"></div>
</div>

<div class="auditbreach_wrap">
        <form action="/reporting/planprogress" method="get" id="plan-progress-form">
            <?php if($identity['u_role_id'] == \Admin\Model\User::ROLE_ADMIN || $identity['u_role_id'] == \Admin\Model\User::ROLE_CONSULTANT || $identity['u_role_id'] == \Admin\Model\User::ROLE_SENIOR_CONSULTANT): ?>
                <p class="plan-progress-top-select">
                    <?php
                    $fn = $form->get('company');
                    echo $this->formLabel($fn);
                    echo $this->formSelect($fn->setAttributes(array('class'=>'form-control')));
                    echo $this->formElementErrors($fn);
                    ?>
                </p>
            <?php endif; ?>
        
            <p class="plan-progress-bottom-select">
                <?php
                $fn = $form->get('type');
                echo $this->formLabel($fn);
                echo $this->formSelect($fn->setAttributes(array('class'=>'form-control plan-progress-type')));
                echo $this->formElementErrors($fn);
                ?>

                <?php
                $fn = $form->get('status');
                echo $this->formLabel($fn);
                echo $this->formSelect($fn->setAttributes(array('class'=>'form-control plan-progress-status')));
                echo $this->formElementErrors($fn);
                ?>
            
                <input type="submit" value="Search" class="form-button plan-progress-submit" />
            </p>
    <?php echo $this->form()->closeTag() ?>

    <div>
        <table cellpadding="0" cellspacing="0">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Company</th>
                    <th>Status</th>
                    <th>Type</th>
                    <th>Date</th>
                    <th>Report</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->paginator as $pn): ?>
                    <tr>
                        <td>
                            <?php echo $pn->_id ?>
                        </td>
                        <td>
                            <a href="<?php echo $this->url($pn->_type == 'breach' ? 'breachremediationplan' : 'remediationplan', array('action' => 'edit', 'id' => $pn->_id)); ?>" target="_blank"><?php echo $pn->_c_name ?></a>
                        </td>
                        <td>
                            <?php echo isset($statuses[$pn->_type][$pn->_status]) ? $statuses[$pn->_type][$pn->_status] : '' ?>
                        </td>
                        <td>
                            <?php echo \Assessment\Model\RemediationplanTable::getTypeForReporting($pn) ?>
                        </td>
                        <td>
                            <?php echo date('m/d/Y', strtotime($pn->_date)) ?>
                        </td>
                        <td>
                            <a href="<?php echo $this->url('reporting', array('action' => 'reportpage', 'type' => $pn->_type, 'id' => $pn->_id)); ?>" target="_blank"><i class="fa fa-file-o"></i></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <?php echo $this->paginationControl(
            $this->bRPPaginator,
            'sliding',
            array('partial/paginator.phtml', 'Reporting'),
            array('route' => 'reporting', 'order_by' => $order_by, 'order' => $order, 'page' => $page, 'search' => null, 'roleFilter' => 1, 'role' => 1, 'controller' => 'reporting', 'action' => 'planprogress')
        );
        ?>
    </div>
</div>

<div class="cboth"><br /></div>
