<div class="page-title">
    <h1 class="fleft">Report Page</h1>
    <div class="cboth"></div>
</div>

<div class="auditbreach_wrap">
        <form action="/reporting/reportpage/<?php echo $type?>/<?php echo $id?>" method="get" id="plan-progress-form">
            <p class="plan-progress-bottom-select">
                <?php
                $fn = $form->get('status');
                echo $this->formLabel($fn);
                echo $this->formSelect($fn->setAttributes(array('class'=>'form-control plan-progress-status')));
                echo $this->formElementErrors($fn);
                ?>
            
                <input type="submit" value="Search" class="form-button plan-progress-submit" />
            </p>
    <?php echo $this->form()->closeTag() ?>

    <div>
        <table cellpadding="0" cellspacing="0">
            <thead>
                <tr>
                    <th style="width: 190px">Company</th>
                    <th>Task|Threat</th>
                    <th>Status</th>
                    <th>Assignee</th>
                    <th>Approver</th>
                    <th style="width: 75px">Date</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->paginator as $pn): ?>
                    <tr>
                        <td>
                            <?php echo $pn->_c_name ?>
                        </td>
                        <td>
                            <a href="/<?php echo $type == 'breach' ? 'breachremediationplan' : 'remediationplan'?>/edit/<?php echo $pn->_parent_id ?>?edittask=<?php echo $pn->_id ?>" target="_blank"><?php echo $pn->_task ?></a>
                        </td>
                        <td>
                            <?php echo isset($statuses[$pn->_type][$pn->_status]) ? $statuses[$pn->_type][$pn->_status] : '' ?>
                        </td>
                        <td>
                            <?php echo $pn->_contact_name ?>
                        </td>
                        <td>
                            <?php echo $pn->_approver_name ?>
                        </td>
                        <td>
                            <?php echo $pn->_latest_action_date ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <?php echo $this->paginationControl(
            $this->bRPPaginator,
            'sliding',
            array('partial/paginator.phtml', 'Reporting'),
            array('route' => 'reporting', 'order_by' => $order_by, 'order' => $order, 'customParams' => array('type' => $type, 'id' => $id), 'page' => $page, 'search' => null, 'roleFilter' => 1, 'role' => 1, 'controller' => 'reporting', 'action' => 'reportpage')
        );
        ?>
    </div>
</div>

<div class="cboth"><br /></div>
