<h1>
Company Assessment Role Alias Detail
</h1>
<p>
    <strong>Default Role Name:</strong> <?php echo $this->defaultAlias;?>
<p>
    <strong>Current Role Alias:</strong> <?php echo $this->alias;?>
</p>
<p>
Specify new role alias (optional)
</p>

    <div class="form-buttons">

        <form method="post" action="/alias/edit/<?php echo $this->id ?>/<?php echo $this->cId?>/<?php echo $this->redirect?>" class="inline">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>">
            <input type="text" name="alias"><br><br><br>
            <button type="submit" name="companyId" value="<?php echo $this->cId; ?>" class="form-button">
                Save
            </button>
        </form>
        <br><br>

        <form method="post" action="/alias/edit/<?php echo $this->id ?>/<?php echo $this->cId?>/<?php echo $this->redirect?>" class="inline">
            <input type="hidden" name="delete" value="<?php echo $this->id; ?>">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>">
            <button type="submit" name="companyId" value="<?php echo $this->cId; ?>" class="form-button">
                Revert to Default
            </button>

        </form>
        <br><br>
            <div class="fleft">or</div>
        <a href="/assessment/list" class="cancel">Cancel</a>
    </div>