
<h1>
    Company Assessment Role Alias Detail
</h1>
<p>
    <strong>Default Role Name:</strong> <?php echo $this->defaultAlias;?>
<p>
    <strong>Current Role Alias:</strong> <?php echo $this->alias;?>
</p>
<p>
    Specify new role alias (optional)

<form action="/alias/edit/<?php echo $this->id . "/" . $this->cId; ?>/" method="post" name="alias">
    <input type="text" name="aliasform"/><br><br><br>
    </p>

    <p>
        <!--<button type="submit" name="revert-alias" class="button" value="--><?php //echo $this->id; ?><!--">Edit</button>-->
        <button type="submit" name="revert" class="button" value="test">Revert</button>
        <!--<button type="submit" name="redirect-alias" class="button" value="--><?php //echo $this->id; ?><!--">Back</button>-->
    </p>
</form>