<table cellpadding="0" cellspacing="0">
    <thead>
        <tr>
            <th>Username</th>
            <th>IP</th>
            <th>Status</th>
            <th style="width:135px">Datetime</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->paginator as $pn): ?>
            <tr class="<?php echo $pn->lo_type != \Application\Model\LogsTable::TYPE_AUTH_SUCCESS ? 'login-unsuccess' : ''?>">
                <td>
                    <a href="<?php echo $this->url('client', array('action' => 'edit', 'id' => $pn->u_id)); ?>" target="_blank"><?php echo $pn->_username ?></a>
                </td>
                <td>
                    <?php echo $pn->lo_ip ?>
                </td>
                <td>
                    <?php echo $statusesMap[$pn->lo_type] ?>
                </td>
                <td>
                    <?php echo $pn->lo_create_date ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php echo $this->paginationControl(
    $this->paginator,
    'sliding',
    array('partial/paginator.phtml', 'company'),
    array('route' => 'company', 'order_by' => $order_by, 'order' => $order, 'page' => $page, 'customParams' => array('id' => $cId), 'search' => null, 'roleFilter' => 1, 'role' => 1, 'controller' => 'company', 'action' => 'usersloginhistory')
);
?>
