<div class="page-title">
    <h1 class="fleft">Business Associate Assessment</h1>
    <div class="cboth"></div>
</div>

<div class="col-left" style="float: none !important; margin: 0 auto;">
        <h3>Assessment Answers</h3>

        <?php foreach ($this->answers as $answer): ?>

            <div class="note">
                <h5><?php echo $answer->_baq_title ?></h5>
                <p>
                    <?php
                    $answerUser = ($answer->baa_value == 0) ? 'N/A' : (($answer->baa_value == 1) ? 'NO' : 'YES');
                    ?>
                    Answer: <strong><?php echo $answerUser ?></strong><br />

                    <?php echo ($answer->_note_text != '') ? 'Note: ' . $answer->_note_text : '' ?><br />

                    <?php if ($answer->_files != ''): ?>
                        <?php
                        $_files = explode(',', $answer->_files);
                        ?>
                        Attachments:<br />
                        <?php foreach ($_files as $_file): ?>
                            <?php
                            $_file = explode('::', $_file);
                            $_fileName = $_file[0];
                            $_fileId = $_file[1];
                            ?>
                            <span style="float: left; margin-right: 5px;" class="<?php echo $this->renderPictoIcon($_fileName); ?>"></span><a href="/files/get/note/<?php echo $answer->note_id ?>/<?php echo $_fileId ?>" class="" target="_blank"><?php echo $_fileName ?></a><br/>

                        <?php endforeach; ?>
                    <?php endif; ?>

                </p>
            </div>

        <?php endforeach; ?>

</div>

