<?php
    $urlOrder = $order == 'ASC' ? 'DESC' : 'ASC';

    $action = isset($action) && ($action != '') ? $action : 'list';
    $hasIdentity = isset($hasIdentity) ? $hasIdentity : false;
?>
				
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>

<div id="canvas">
    <div class="page-title">
        <h1 class="fleft">Users</h1>
        <?php if(!$isConsultant):?>
            <a href="<?php echo $this->url('admin', array('action' => 'users', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => 0)); ?>" class="label <?php echo $roleFilter == 0 ? ' selected ' : '' ?>">All</a>
            <a href="<?php echo $this->url('admin', array('action' => 'users', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => 3)); ?>" class="label <?php echo $roleFilter == 3 ? ' selected ' : '' ?>">Consultants</a>
            <a href="<?php echo $this->url('admin', array('action' => 'users', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => 2)); ?>" class="label <?php echo $roleFilter == 2 ? ' selected ' : '' ?>">Senior Consultants</a>
            <a href="<?php echo $this->url('admin', array('action' => 'users', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => 4)); ?>" class="label <?php echo $roleFilter == 4 ? ' selected ' : '' ?>">Sales Reps</a>
            <a href="<?php echo $this->url('admin', array('action' => 'users', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => 5)); ?>" class="label <?php echo $roleFilter == 5 ? ' selected ' : '' ?>">Clients</a>
            <a href="<?php echo $this->url('admin', array('action' => 'users', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => 6)); ?>" class="label <?php echo $roleFilter == 6 ? ' selected ' : '' ?>">Business Associates</a>
            <a href="<?php echo $this->url('admin', array('action' => 'users', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => 7)); ?>" class="label <?php echo $roleFilter == 7 ? ' selected ' : '' ?>">Partial</a>
            <a href="<?php echo $this->url('admin', array('action' => 'users', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => 8)); ?>" class="label <?php echo $roleFilter == 8 ? ' selected ' : '' ?>">Trail User</a>
        <?php else: ?>
            <a href="<?php echo $this->url('admin', array('action' => 'users', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => 0)); ?>" class="label <?php echo $roleFilter == 0 ? ' selected ' : '' ?>">All</a>
            <a href="<?php echo $this->url('admin', array('action' => 'users', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => 5)); ?>" class="label <?php echo $roleFilter == 5 ? ' selected ' : '' ?>">Clients</a>
            <a href="<?php echo $this->url('admin', array('action' => 'users', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => 6)); ?>" class="label <?php echo $roleFilter == 6 ? ' selected ' : '' ?>">Business Associates</a>
            <a href="<?php echo $this->url('admin', array('action' => 'users', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => 7)); ?>" class="label <?php echo $roleFilter == 7 ? ' selected ' : '' ?>">Partial</a>
        <?php endif; ?>
        <a href="/admin/edituser" class="button"><i class="fa fa-plus-circle"></i> Add New User</a>
        <div class="cboth"></div>
    </div>

    <p></p>

		<table id="users-list" cellpadding="0" cellspacing="0">
        <thead>
            <tr>
                <?php $classSort = ($order_by == 'id') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
                <th>
                    ID
                </th>

                <?php $classSort = ($order_by == 'name') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
                <th>
                    Name 
                </th>

                <?php $classSort = ($order_by == 'role') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
                <th>
                    Account Type 
                </th>

                <?php $classSort = ($order_by == 'active') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
                <th>Status</th> 
                <th>Phone</th>
                <th>Created</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->paginator as $user): ?>
                <tr>
                    <td><?php echo $user->u_id ?></td>
                    <td><a href="/admin/edituser/<?php echo $user->u_id ?>"><?php echo $user->u_firstname ?> <?php echo $user->u_lastname ?></a></td>
                    <td><?php echo $user->_rolename ?></td>
                    <td><?php echo $user->u_active ? 'Active' : 'Inactive'  ?></td>
                    <td><?php echo $user->u_office_phone ?></td>
                    <td><?php echo $this->formatDateA($user->u_create_date) ?></td>
                    <td class="aright">
                        <a href="/admin/edituser/<?php echo $user->u_id ?>" title="Edit"><i class="fa fa-pencil"></i></a> &nbsp;
                        <?php $deleteUrl = '/admin/deactivateuser/' . $user->u_id; ?>
                        <?php if ($user->u_active == 1): ?>
                            <a href="#deactivation-box-modal" onclick="$('#deactivateYes').attr('href', '<?php echo $deleteUrl ?>')" class="confirmation-modal i-delete"  title="Deactivate"><i class="fa fa-trash-o"></i></a>
                        <?php else : ?>  
                            <a href="/admin/activateuser/<?php echo $user->u_id ?>" class="">Activate</a> 
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
		<script>
			$(document).ready(function(){
				$('#users-list').DataTable({
						"order": [[ 1, "asc" ]],
						"columnDefs": [
								{"type": "num", "targets": 0},
								{"type": "date", "targets": 5},
								{"orderable": false, "targets": 6}
						]
				});
			});
			$('.dataTables_filter input[type="search"]').
				css({'width':'95%','display':'inline-block'});

		</script>
</div>