<?php
$urlOrder = $order == 'ASC' ? 'DESC' : 'ASC';
$authService = new \Zend\Authentication\AuthenticationService();
$authService->setStorage(new \SanAuth\Model\MyAuthStorage('hipaa'));
$identity = $authService->getIdentity();
$isClientRole = $identity['u_role_id'] == \Admin\Model\User::ROLE_CLIENT ? 1 : 0;
?>

<div class="it-asset-inventory-list page-title">
    <h2 class="fleft">IT Asset Inventory Logs</h2>
    <a href="<?php echo $this->url('itassetinventory', array('action' => 'list', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => 0)); ?>" class="label <?php echo $roleFilter == 0 ? ' selected ' : '' ?>">All</a>
    <a href="<?php echo $this->url('itassetinventory', array('action' => 'list', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => 1)); ?>" class="label <?php echo $roleFilter == 1 ? ' selected ' : '' ?>">Active</a>
    <a href="<?php echo $this->url('itassetinventory', array('action' => 'list', 'page' => $page, 'order_by' => $order_by, 'order' => $order, 'roleFilter' => 2)); ?>" class="label <?php echo $roleFilter == 2 ? ' selected ' : '' ?>">Archived</a>
    <form id="list_search_form" method="GET" onsubmit="escape(this)" action="<?php echo $this->url('itassetinventory', array('action' => 'list', 'roleFilter' => $roleFilter)); ?>">
        <a href="javascript:" onclick="$('#list_search_form').submit()" id="list_search-button"><i class="fa fa-search"></i></a>
        <input type="text" name="search" id="list_search" placeholder="Search" value="<?php echo $search?>">
    </form>
    <?php if (in_array($identity['u_role_id'], array(\Admin\Model\User::ROLE_ADMIN, \Admin\Model\User::ROLE_CONSULTANT, \Admin\Model\User::ROLE_SENIOR_CONSULTANT)) || ($identity['u_role_id'] == \Admin\Model\User::ROLE_CLIENT && $identity['u_company_id_admin'])): ?>
        <a href="/itassetinventory/edit/0" class="button"><i class="fa fa-clipboard"></i> Add New It Asset Log</a>
    <?php endif; ?>
    <div class="cboth"></div>
</div>


<p></p>

<table cellpadding="0" cellspacing="0">
    <thead>
        <tr>
            <?php $classSort = ($order_by == 'id') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>
                <a href="<?php echo $this->url('itassetinventory', array('action' => 'list', 'page' => $page, 'order_by' => 'id', 'order' => $urlOrder, 'roleFilter' => $roleFilter)); ?>">
                    ID <i class="fa <?php echo $classSort ?>"></i>
                </a>
            </th>

            <?php if (!$isClientRole): ?>
                <?php $classSort = ($order_by == 'cName') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
                <th>
                    <a href="<?php echo $this->url('itassetinventory', array('action' => 'list', 'page' => $page, 'order_by' => 'cName', 'order' => $urlOrder, 'roleFilter' => $roleFilter)); ?>">
                        Client <i class="fa <?php echo $classSort ?>"></i>
                    </a>
                </th>
            <?php endif; ?>

            <?php $classSort = ($order_by == 'location') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>
                <a href="<?php echo $this->url('itassetinventory', array('action' => 'list', 'page' => $page, 'order_by' => 'location', 'order' => $urlOrder, 'roleFilter' => $roleFilter)); ?>">
                    Location <i class="fa <?php echo $classSort ?>"></i>
                </a>
            </th>

            <?php $classSort = ($order_by == 'type') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>
                <a href="<?php echo $this->url('itassetinventory', array('action' => 'list', 'page' => $page, 'order_by' => 'type', 'order' => $urlOrder, 'roleFilter' => $roleFilter)); ?>">
                    Type <i class="fa <?php echo $classSort ?>"></i>
                </a>
            </th>

            <?php $classSort = ($order_by == 'date') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>
                <a href="<?php echo $this->url('itassetinventory', array('action' => 'list', 'page' => $page, 'order_by' => 'date', 'order' => $urlOrder, 'roleFilter' => $roleFilter)); ?>">
                    Date <i class="fa <?php echo $classSort ?>"></i>
                </a>
            </th>

            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->paginator as $iai): ?>
            <tr>
                <td><?php echo $iai->iai_id ?></td>
                <td><?php echo $iai->_c_name ?></td>
                <td><?php echo $iai->_location ?></td>
                <td><?php echo $iai->_type ?></td>
                <td><?php echo ($iai->iai_create_date != '0000-00-00 00:00:00') ? $this->formatDateA($iai->iai_create_date) : '' ?></td>
                <td style="white-space: nowrap;" class="aright">
                    <?php if ($iai->iai_active) : ?>
                    <a href="/itassetinventory/edit/<?php echo $iai->iai_id ?>" title="Edit"><i class="fa fa-pencil"></i></a> &nbsp;
                    <?php endif; ?>
                    <?php if (in_array($identity['u_role_id'], array(\Admin\Model\User::ROLE_CONSULTANT, \Admin\Model\User::ROLE_SENIOR_CONSULTANT, \Admin\Model\User::ROLE_ADMIN))): ?>
                        <?php if ($iai->iai_active) : ?>
                            <?php $deleteUrl = '/itassetinventory/delete/' . $iai->iai_id; ?>
                            <a href="#confirmation-box-modal" onclick="$('#deleteYes').attr('href', '<?php echo $deleteUrl ?>')" class="confirmation-modal i-delete"><i class="fa fa-trash-o"></i></a>
                        <?php elseif ($identity['u_role_id'] == \Admin\Model\User::ROLE_ADMIN): ?>
                            <a href="/itassetinventory/unarchive/<?php echo $iai->iai_id ?>" class="">Unarchive</a>
                        <?php endif; ?>
                    <?php endif; ?>

                </td>
            </tr>

        <?php endforeach; ?>
    </tbody>
</table>

<?php echo $this->paginationControl(
    $this->paginator,
    'sliding',
    array('partial/paginator.phtml', 'It Asset Inventory Logs'),
    array('route' => 'list', 'order_by' => $order_by, 'order' => $order, 'page' => $page, 'roleFilter' => $roleFilter, 'role' => 1, 'controller' => 'itassetinventory', 'action' => 'list')
);
?>

<div class="cboth"><br /></div>
<script type="text/javascript">
    jQuery(function() {
        $(document).ready(function() {
            $('#list_search_form').submit(function(e){
                e.preventDefault();
                var search = $('#list_search').val();
                if(search === '') {
                    window.location.href = $(this).attr('action');
                } else if(search !== undefined) {
                    window.location.href = $(this).attr('action') + '/search/' + search;
                }
            });
        });
    });
</script>