<?php
/**
 * Zend Framework (http://framework.zend.com/)
 *
 * @link      http://github.com/zendframework/ZendSkeletonApplication for the canonical source repository
 * @copyright Copyright (c) 2005-2013 Zend Technologies USA Inc. (http://www.zend.com)
 * @license   http://framework.zend.com/license/new-bsd New BSD License
 */

namespace Application;

use Zend\Mvc\ModuleRouteListener;
use Zend\Mvc\MvcEvent;
use Application\Model\ProvinceTable;
use Zend\Db\ResultSet\ResultSet;
use Zend\Db\TableGateway\TableGateway;
use Zend\Mail;
use Zend\Mail\Transport\Smtp as SmtpTransport;
use Zend\Mail\Transport\SmtpOptions;
//use Mail\Model\Mailtemplate;
use Zend\ServiceManager\ServiceManager;

class Module
{
    public function onBootstrap(MvcEvent $e)
    {
        $eventManager        = $e->getApplication()->getEventManager();
        $moduleRouteListener = new ModuleRouteListener();
        $moduleRouteListener->attach($eventManager);

        $translator = $e->getApplication()->getServiceManager()->get('translator');
        \Zend\Validator\AbstractValidator::setDefaultTranslator($translator);

				//handle the dispatch error (exception) 
				$eventManager->attach(MvcEvent::EVENT_DISPATCH_ERROR, array($this, 'handleError'));
				//handle the view render error (exception) 
				$eventManager->attach(MvcEvent::EVENT_RENDER_ERROR, array($this, 'handleError'));
    }
		public function handleError(MvcEvent $e)
		{
			//don't do any global error handling if this is a locally run instance.
      if($_SERVER['SERVER_ADDR'] == '127.0.0.1')
				return;
			//get the exception
			$exception = $e->getParam('exception');
			$sm = $e->getApplication()->getServiceManager();
			$mtt = $sm->get('Mail\Model\MailtemplateTable');
			$controllerLoader = $e->getApplication()->getServiceManager()->get('ControllerLoader');
			$routeMatch       = $e->getRouteMatch();
			$controllerName   = $routeMatch->getParam('controller', 'not-found');
			$controller = $controllerLoader->get($controllerName);
			$sl = $controller->getServiceLocator();
			
			$authService = new \Zend\Authentication\AuthenticationService();
			$authService->setStorage(new \SanAuth\Model\MyAuthStorage('hipaa'));
			$identity = $authService->getIdentity();

			$user = $sl->get('Admin\Model\UserTable')->getUser($identity['u_id']);

			if($user) {
					$cName = $user->u_firstname . ' ' . $user->u_lastname;
					$cEmail = $user->u_email;
					$cPhone = $user->u_office_phone;
					$message = 'global error generated by user = ' . $cName . ' phone(' . $cPhone. ') email(' . $cEmail. ')';	
			}else{
					$message = 'global error';	
			}
			
			$message .= "<br><br>message:" . $exception->getMessage();
			$message .= "<br><br>backtrace: " . $this->get_caller_info();
			$message .= "<br><br>trace: " . $exception->getTraceAsString();
			$mtt->sendMail($sl, array('type' => 'error', 'message' => $message));
		}
		private function get_caller_info() {
			
				$c = '';
				$file = '';
				$func = '';
				$class = '';
				$trace = debug_backtrace();
				if (isset($trace[2])) {
						$file = $trace[1]['file'];
						$func = $trace[2]['function'];
						if ((substr($func, 0, 7) == 'include') || (substr($func, 0, 7) == 'require')) {
								$func = '';
						}
				} else if (isset($trace[1])) {
						$file = $trace[1]['file'];
						$func = '';
				}
				if (isset($trace[3]['class'])) {
						$class = $trace[3]['class'];
						$func = $trace[3]['function'];
						$file = $trace[2]['file'];
				} else if (isset($trace[2]['class'])) {
						$class = $trace[2]['class'];
						$func = $trace[2]['function'];
						$file = $trace[1]['file'];
				}
				if ($file != '') $file = basename($file);
				$c = $file . ": ";
				$c .= ($class != '') ? ":" . $class . "->" : "";
				$c .= ($func != '') ? $func . "(): " : "";
				return($c);
		}		
		
    public function getConfig()
    {
        return include __DIR__ . '/config/module.config.php';
    }

    public function getAutoloaderConfig()
    {
        return array(
            'Zend\Loader\StandardAutoloader' => array(
                'namespaces' => array(
                    __NAMESPACE__ => __DIR__ . '/src/' . __NAMESPACE__,
                ),
            ),
        );
    }

    public function getServiceConfig()
    {
        return array(
            'factories' => array(

                'Application\Model\FilesTable' =>  function($sm) {
                    $tableGateway = $sm->get('FilesTableGateway');
                    $table = new \Application\Model\FilesTable($tableGateway);
                    return $table;
                },
                'FilesTableGateway' => function ($sm) {
                    $dbAdapter = $sm->get('Zend\Db\Adapter\Adapter');
                    $resultSetPrototype = new ResultSet();
                    return new TableGateway('files', $dbAdapter, null, $resultSetPrototype);
                },
                'Application\Model\LogsTable' =>  function($sm) {
                    $tableGateway = $sm->get('LogsTableGateway');
                    $table = new \Application\Model\LogsTable($tableGateway);
                    return $table;
                },
                'LogsTableGateway' => function ($sm) {
                    $dbAdapter = $sm->get('Zend\Db\Adapter\Adapter');
                    $resultSetPrototype = new ResultSet();
                    return new TableGateway('logs', $dbAdapter, null, $resultSetPrototype);
                },
                'Sitesetting\Model\SitesettingTable' =>  function($sm) {
                    $tableGateway = $sm->get('SitesettingTableGateway');
                    $table = new \Sitesetting\Model\SitesettingTable($tableGateway);
                    return $table;
                },
                'SitesettingTableGateway' => function ($sm) {
                    $dbAdapter = $sm->get('Zend\Db\Adapter\Adapter');
                    $resultSetPrototype = new ResultSet();
                    $resultSetPrototype->setArrayObjectPrototype(new \Sitesetting\Model\Sitesetting());
                    return new TableGateway('site_settings', $dbAdapter, null, $resultSetPrototype);
                }


            ),
        );
    }
}
