<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    'modules' => array(
        'Application',
        'User',
        'SanAuth',
        'Admin',
        'Client',
        'Note',
        'Businessassociate',
        'Mail',
        'Breachlog',
        'Assessment',
        'Dashboard',
        'Search',
        'Traininglog',
        'Securityreminder',
        'Sitesetting',
        'Disclosure',
        'Reporting',
        'Itassetinventory'
        ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor'
            ),
        'config_glob_paths' => array('config/autoload/{,*.}{global,local}.php')
        )
    );
