<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
    <meta http-equiv="Content-type" content="text/html; CHARSET=utf-8">
    <title>HIPAA Suite by The Carosh Group</title>

    <style type="text/css">
        body{
            margin: 0;
            padding: 0;
            background: #0a2a47;
            color: #0d3253;
            font-family:arial, tahoma, verdana;
            font-size:16px;
            line-height:22px;
        }
        a,a:visited{
            color:#0e5270;
            text-decoration:none;
        }
        a:hover{
            color:#0e5270;
            text-decoration:underline;
        }
        td.content{
            color:#0d3253;
            font-family:arial, tahoma, verdana;
            font-size:16px;
            line-height:22px;
        }
        h1{
            margin: 25px 0 20px 0;
            padding: 0;
            color: #38a7db;
            font-family: arial, tahoma, verdana;
            font-size: 20px;
            line-height: 24px;
        }
        p{
            margin:15px 0 15px 0;
            padding: 0;
            color: #0d3253;
            font-family:arial, tahoma, verdana;
            font-size:16px;
            line-height:22px;
        }
        ul{
            margin:0;
            padding:0;
            list-style-type:none;
            list-style-image:none;
        }
    </style>
</head>


<body style="background:#0a2a47;color:#333333;margin:0;padding:0;">
    <div style="padding-top: 40px;">
        <table width="600" align="center" border="0" cellspacing="0" cellpadding="0" style="margin: 40px auto 0 auto; background:#f4f7f9; -moz-box-shadow: 0 3px 4px 5px #08233b; -webkit-box-shadow: 0 3px 4px 5px #08233b; box-shadow: 0 3px 4px 5px #08233b; border-top-left-radius: 4px; border-top-right-radius: 4px;">
            <tr>
                <td style="padding: 45px 0 0 0; text-align: center;">
                    <a href="http://hipaa.carosh.com/" target="_blank"><img src="http://hipaa.carosh.com//images/email-logo.png" width="523" height="100" border="0" alt="" /></a>
                </td>
            </tr>
            <tr>
                <td class="content" align="left" valign="top" style="color: #0d3253;font-family: arial, tahoma, verdana; font-size:16px;line-height:22px;">
                    <div style="padding: 15px 40px 40px 40px; text-align: left;">
                        <?php echo $this->content ?>
                    </div>
                </td>
            </tr>
            <tr>
                <td class="signature" align="left" valign="top" style="color: #fff;font-family: arial, tahoma, verdana; font-size:16px;line-height:20px;background:#189494;">
                    <div style="padding: 24px 40px 28px 40px; text-align: left;">
                        <p style="margin: 0;color:#93cccc;line-height:20px;background: transparent url(http://hipaa.carosh.com/images/email-logo-bottom.png) right center no-repeat;">
                            <strong style="color:#fff;font-size:18px;font-weight:600;line-height:32px;"><?php echo (trim($this->consultant_name) != '') ? $this->consultant_name . ',' : '' ?></strong><br>
                            <span style="color:#dff4f4;"><?php echo $this->consultant_role ?></span><br>
                            <a href="mailto:<?php echo $this->consultant_email ?>" style="color: #93cccc;"><?php echo $this->consultant_email ?></a>

                            <?php
                            $authService = new \Zend\Authentication\AuthenticationService();
                            $authService->setStorage(new \SanAuth\Model\MyAuthStorage('hipaa'));
                            $identity = $authService->getIdentity();
                            $isConsultantRole = ($identity['u_role_id'] == 2) || ($identity['u_role_id'] == 3) ? 1 : 0;
                            ?>

                            <?php if ($isConsultantRole && ($this->consultant_phone != '')): ?>
                                <br/><?php echo $identity['u_office_phone'] ?>
                            <?php endif; ?>
                            <br/>The Carosh Group
                            <br/><a style="color: #93cccc;" href="http://www.carosh.com">www.carosh.com</a>
                        </p>
                    </div>
                </td>
            </tr>
        </table>
        <table width="100%" align="center" border="0" cellspacing="0" cellpadding="0">
            <tr>
                <td align="center">
                    <p style="margin: 25px 0 18px 0; color: #476580; font-family: arial, tahoma, verdana; font-size: 12px; line-height: 21px;">
                        Copyright &copy; 2014 <a href="http://www.carosh.com/" style="color: #476580;" target="_blank">The Carosh Group</a>. All rights reserved.<br>
                        <a href="http://hipaa.carosh.com/Privacy_Policy.pdf" style="color: #476580;" target="_blank">Privacy Statement</a> &nbsp; | &nbsp; <a href="http://hipaa.carosh.com/Terms_of_Use.pdf" style="color: #476580;" target="_blank">Terms and Conditions</a>
                    </p>
                    <br>
                </td>
            </tr>
        </table>
    </div>


</body>
</html>
