<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Baza dobrych praktyk'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/datepicker.css')
                        ->prependStylesheet($this->basePath() . '/css/custom.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . 'http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css')
                        ->prependStylesheet($this->basePath() . '/css/pFirst.css')
                        ->prependStylesheet($this->basePath() . '/css/chosen.css')
                        ->prependStylesheet($this->basePath() . '/css/pWidok_praktyka.css')
                        ->prependStylesheet($this->basePath() . '/css/menu.css')
                        ->prependStylesheet($this->basePath() . '/css/pKonkurs.css')
                        ->prependStylesheet($this->basePath() . '/css/styles.css')

        ?>

        <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css">

        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
        <script type="text/javascript" src="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
        <script type="text/javascript"  src="/js/chosen.jquery.min.js"></script>
        <script type="text/javascript"  src="/js/bootstrap-datepicker.js"></script>
        <script type="text/javascript"  src="/js/jquery.jqEasyCharCounter.min.js"></script>
        <script type="text/javascript"  src="/js/jquery.autosize.min.js"></script>
        <!-- Custom -->
        <script type="text/javascript"  src="/js/custom.js"></script>
        <script type="text/javascript"  src="/ckeditor/ckeditor.js"></script>
        <script type="text/javascript"  src="/ckfinder/ckfinder.js"></script>
        <script type="text/javascript"  src="/js/pRejestracja_przedstawiciela.js"></script>
        <script src="/js/jquery.ba-hashchange.js" type="text/javascript"></script>
        <script src="/js/jquery.easytabs.js" type="text/javascript"></script>
        <!-- Scripts -->
        <?php /*echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; */?>

    </head>

    <body id="<?php echo $this->bodyId ?>">
        <nav class="navbar navbar-fixed-top navbar-default">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
                    </button>
                    <a href="/" class="navbar-brand"><b><i class="icon-thumbs-up-alt icon-2x"></i>&nbsp;&nbsp;<?php echo $this->translate('Baza Dobrych Praktyk') ?></b></a>
                </div>
                <div class="collapse navbar-collapse">
                    <?php //echo $this->navigation()->menu()->setPartial('application/partials/menutop'); ?>
                    <?php echo $this->menuTop(); ?>

                    <form method="POST" action="/search/list" class="navbar-form navbar-right" role="search">
                        <div class="form-group">
                            <input name="searchValue" value="<?php echo isset($searchValue) ? $searchValue : '' ?>" type="text" class="form-control" placeholder="<?php echo $this->translate('tytul dobrej praktyki') ?>">
                        </div>
                        <button type="submit" class="btn btn-default"><?php echo $this->translate('szukaj') ?></button>
                        <div>
                            <a href="/search/advanced"><small><?php echo $this->translate('wyszukiwanie zaawansowane') ?></small></a>
                        </div>
                    </form>
                    <div class="clearfix"></div>
                </div>
            </div>
        </nav>

        <div class="container">
            <!-- CONTENT -->
        <?php if (isset($flashMessagesSuccess) && count($flashMessagesSuccess)) : ?>
            <div class="flash-container">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                                <?php foreach ($flashMessagesSuccess as $msg) : ?>
                                    <div class="alert alert-flash alert-dismissable center alert-success">
                                      <button type="button" class="close" aria-hidden="true">&times;</button>
                                        <strong>
                                            <?php echo $msg; ?>
                                        </strong>
                                    </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <?php if (isset($flashMessagesErrors) && count($flashMessagesErrors)) : ?>
            <div class="flash-container">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12"> 
                            <?php foreach ($flashMessagesErrors as $msg) : ?>
                                <div class="alert alert-flash alert-dismissable center alert-danger">
                                  <button type="button" class="close" aria-hidden="true">&times;</button>
                                    <strong>
                                        <?php echo $msg; ?>
                                    </strong>
                                </div>
                            <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                </div>
        <?php endif; ?>
            <div class="row">
                <!-- RENDER MENU -->
                <?php $sm = $this->getHelperPluginManager()->getServiceLocator(); ?>
                <?php echo $this->menuLeft($sm); ?>
                <?php echo $this->content; ?>
            </div>

        </div>
        <hr>
        <div class="container second">
            <div class="row footer">
                <div class="col-md-12 center">
                    <a href="http://www.efs.gov.pl" target="_blank">
                        <img src="http://bslipek.s3.amazonaws.com/akra/bdp/images/stopka.jpg" alt="Stopka strony zawierająca loga." width="70%">
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 center"><?php echo $this->translate('Projekt współfinansowany ze środków Unii Europejskiej w ramach Europejskiego Funduszu Społecznego.') ?>
                </div>
            </div>
        </div>
    </body>

    <script>
        CKFinder.setupCKEditor( null, '/ckfinder/' );
    </script>
</html>
