
<div class="col-md-3 menu-left" id="menu_left">
    <?php foreach ($items as $item): ?>
        <div class="panel panel-menu">
            <div class="panel-heading"><h3 class="panel-title"><?php echo $item['title'] ?></h3></div>
            <div class="panel-body">
                <ul>
                    <?php foreach ($item['items'] as $subitem): ?>
                        <?php if ($subitem['title'] == 'border'): ?>
                            <p></p>
                        <?php continue; endif; ?>

                        <li class="<?php echo isset($subitem['active']) ? 'active' : '' ?>">
                            <div class="arrow-right"></div>
                            <a href="<?php echo $subitem['url'] ?>">
                                <?php echo $subitem['title'] ?>
                                <span class="badge pull-right"></span>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div><!-- END menu test test 10-->

    <?php endforeach; ?>
</div>
<!-- END RENDER MENU -->
