<?php
$urlOrder = $order == 'ASC' ? 'DESC' : 'ASC';
$authService = new \Zend\Authentication\AuthenticationService();
$authService->setStorage(new \SanAuth\Model\MyAuthStorage('hipaa'));
$identity = $authService->getIdentity();
?>

<div class="page-title">
    <h1 class="fleft">Search Results</h1>
    <a href="/search/search/<?php echo $this->searchValue ?>" class="label <?php echo ($this->roleFilter === 'a') ? 'selected' : '' ?>">All</a>
    <a href="/search/search/<?php echo $this->searchValue ?>/roleFilter/company" class="label <?php echo ($this->roleFilter === 'company') ? 'selected' : '' ?>">Companies</a>
    <a href="/search/search/<?php echo $this->searchValue ?>/roleFilter/contact" class="label <?php echo ($this->roleFilter === 'contact') ? 'selected' : '' ?>">Contacts</a>
    <a href="/search/search/<?php echo $this->searchValue ?>/roleFilter/breachlog" class="label <?php echo ($this->roleFilter === 'breachlog') ? 'selected' : '' ?>">Breach Logs</a>
    <a href="/search/search/<?php echo $this->searchValue ?>/roleFilter/assessment" class="label <?php echo ($this->roleFilter === 'assessment') ? 'selected' : '' ?>">Assessments</a>
    <a href="/search/search/<?php echo $this->searchValue ?>/roleFilter/remediationplan" class="label <?php echo ($this->roleFilter === 'remediationplan') ? 'selected' : '' ?>">Remediation Plans</a>
    <?php
    if ($identity['u_role_id'] == 1): ?>
        <a href="/search/search/<?php echo $this->searchValue ?>/roleFilter/user" class="label <?php echo ($this->roleFilter === 'user') ? 'selected' : '' ?>">Users</a>
    <?php endif; ?>
    <div class="cboth"></div>
</div>

<p></p>

<table cellpadding="0" cellspacing="0">
    <thead>
        <tr>
            <?php $classSort = ($order_by == 'type') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>
                <a href="<?php echo $this->url('search', array('action' => 'search', 'page' => $page, 'order_by' => 'type', 'order' => $urlOrder, 'roleFilter' => $roleFilter, 'searchValue' => $this->searchValue)); ?>">
                    Type <i class="fa <?php echo $classSort ?>"></i>
                </a>
            </th>

            <?php $classSort = ($order_by == 'name') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>
                <a href="<?php echo $this->url('search', array('action' => 'search', 'page' => $page, 'order_by' => 'name', 'order' => $urlOrder, 'roleFilter' => $roleFilter, 'searchValue' => $this->searchValue)); ?>">
                    Result <i class="fa <?php echo $classSort ?>"></i>
                </a>
            </th>
            <?php if(in_array($this->roleFilter, array('a', 'assessment', 'remediationplan'))): ?>
                <?php $classSort = ($order_by == 'status') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
                <th>
                    <a href="<?php echo $this->url('search', array('action' => 'search', 'page' => $page, 'order_by' => 'status', 'order' => $urlOrder, 'roleFilter' => $roleFilter, 'searchValue' => $this->searchValue)); ?>">
                        Status <i class="fa <?php echo $classSort ?>"></i>
                    </a>
                </th>
                <?php $classSort = ($order_by == 'date') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
                <th>
                    <a href="<?php echo $this->url('search', array('action' => 'search', 'page' => $page, 'order_by' => 'date', 'order' => $urlOrder, 'roleFilter' => $roleFilter, 'searchValue' => $this->searchValue)); ?>">
                        Date <i class="fa <?php echo $classSort ?>"></i>
                    </a>
                </th>
            <?php endif; ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->paginator as $result): ?>
            <?php if ($result['_type'] == 'company'): ?>
                <tr>
                    <td>Company</td>
                    <td><a href="/company/edit/<?php echo $result['_id'] ?>"><?php echo $result['_name'] ?></a></td>
                    <?php if($this->roleFilter == 'a'): ?>
                        <td></td>
                        <td></td>
                    <?php endif; ?>
                </tr>
            <?php elseif ($result['_type'] == 'contact'): ?>
                <tr>
                    <td>Contact</td>
                    <td><a href="/client/edit/<?php echo $result['_id'] ?>"><?php echo $result['_name'] ?></a></td>
                    <?php if($this->roleFilter == 'a'): ?>
                        <td></td>
                        <td></td>
                    <?php endif; ?>
                </tr>
            <?php elseif ($result['_type'] == 'user'): ?>
                <tr>
                    <td>User</td>
                    <td><a href="/admin/edituser/<?php echo $result['_id'] ?>"><?php echo $result['_name'] ?></a></td>
                    <?php if($this->roleFilter == 'a'): ?>
                        <td></td>
                        <td></td>
                    <?php endif; ?>
                </tr>
            <?php elseif ($result['_type'] == 'breachlog'): ?>
                <tr>
                    <td>Breach log</td>
                    <td><a href="/breachlog/edit/<?php echo $result['_id'] ?>"><?php echo $result['_name'] ?></a></td>
                    <?php if($this->roleFilter == 'a'): ?>
                        <td></td>
                        <td></td>
                    <?php endif; ?>
                </tr>
            <?php elseif ($result['_type'] == 'assessment'): ?>
                <tr>
                    <td><?= \Assessment\Model\Assessment::$typesNames[$result['_item_type']]?></td>
                    <td><a href="/assessment/edit/<?php echo $result['_id'] ?>"><?php echo $result['_name'] ?></a></td>
                    <td><?php echo \Assessment\Model\Assessment::$statusesNames[$result['_status']] ?></td>
                    <td><?php echo ($result['_date'] != '0000-00-00 00:00:00') ? $this->formatDateA($result['_date']) : '' ?></td>
                </tr>
            <?php elseif ($result['_type'] == 'remediationplan'): ?>
                <tr>
                    <td><?= \Assessment\Model\Assessment::$typesNames[$result['_item_type']]?></td>
                    <td><a href="/remediationplan/edit/<?php echo $result['_id'] ?>"><?php echo $result['_name'] ?></a></td>
                    <td><?php echo \Assessment\Model\Remediationplan::$statusesNames[$result['_status']] ?></td>
                    <td><?php echo ($result['_date'] != '0000-00-00 00:00:00') ? $this->formatDateA($result['_date']) : '' ?></td>
                </tr>
            <?php endif; ?>

        <?php endforeach; ?>
    </tbody>
</table>

<?php echo $this->paginationControl(
    $this->paginator,
    'sliding',
    array('partial/paginator.phtml', 'Search'),
    array('route' => 'search', 'order_by' => $order_by, 'order' => $order, 'page' => $page, 'roleFilter' => $roleFilter, 'role' => 1, 'controller' => 'search', 'action' => 'search', 'searchValue' => $this->searchValue)
);
?>

<div class="cboth"><br /></div>