<?php

// within a view script
$form = $this->form;
$form->prepare();

// Assuming the "contact/process" route exists...
$form->setAttribute('action', '/disclosurerecord/edit');

// Set the method attribute for the form
$form->setAttribute('method', 'post');

// Render the opening tag
?>


    <div class="page-title">
        <h1 class="fleft"><?php if($this->drId) {?>Edit <?php } else {?>Add New <?php }?>Disclosure Record</h1>
        <div class="cboth"></div>
    </div>

    <p></p>

<div class="col-left">
    <form action="/disclosurerecord/edit/<?php echo $this->drId ?>" method="post" enctype="multipart/form-data" name="disclosurerecord" id="disclosurerecord">
        <?php
            $fn = $form->get('dr_id');
            echo $this->formHidden($fn);
        ?>
        <?php
            $fn = $form->get('dr_active');
            echo $this->formHidden($fn);
        ?>

        <p>
            <?php
            $fn = $form->get('dr_location');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <?php
            $fn = $form->get('dr_date_received');
            if ($this->drObj):
                $fn->setValue($this->formatDateA($this->drObj->dr_date_received, false, true));
            endif;
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required', 'id' => 'dr_date_received', 'readonly' => 'readonly')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <h5 class="fleft m10">Patient Information</h5>

        <p>
            <?php
            $fn = $form->get('dr_date_disclosure');
            if ($this->drObj):
                $fn->setValue($this->formatDateA($this->drObj->dr_date_disclosure, false, true));
            endif;
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required', 'id' => 'dr_date_disclosure', 'readonly' => 'readonly')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <?php $fn = $form->get('dr_medical_record_number');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <?php
            $fn = $form->get('dr_patient_name');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <?php
            $fn = $form->get('dr_date_of_birth');
            if ($this->tlObj):
                $fn->setValue($this->formatDateA($this->tlObj->dr_date_of_birth, false, true));
            endif;
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required', 'id' => 'dr_date_of_birth', 'readonly' => 'readonly')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <?php
            $fn = $form->get('dr_phi_information_disclosed');
            echo $this->formLabel($fn);
            echo $this->formTextarea($fn->setAttributes(array('class' => 'double')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <?php
            $fn = $form->get('dr_purpose_of_disclosure');
            echo $this->formLabel($fn);
            echo $this->formTextarea($fn->setAttributes(array('class' => 'double')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <?php
            $fn = $form->get('dr_name_of_requestor');
            echo $this->formLabel($fn);
            echo $this->formTextarea($fn->setAttributes(array('class' => 'double')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <?php
            $fn = $form->get('dr_address');
            echo $this->formLabel($fn);
            echo $this->formTextarea($fn->setAttributes(array('class'=>'', 'style' => 'width: 450px; height: 85px;')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <label>Verbal Request for Disclosure</label>
            <span class="radio-button-wrap">
                <input type="radio" name="dr_is_verbal" id="dr_is_verbal_yes" <?php if($drObj && $drObj->dr_is_verbal == 'Yes'){?>checked<?php }?> class="radio" value="Yes" />
                    <label for="dr_is_verbal_yes" class="checkbox">Yes</label>
                <input type="radio" name="dr_is_verbal" id="dr_is_verbal_no" <?php if(!$drObj || $drObj->dr_is_verbal == 'No'){?>checked<?php }?> class="radio" value="No" />
                    <label for="dr_is_verbal_no" class="checkbox">No</label>
                <input type="radio" name="dr_is_verbal" id="dr_is_verbal_na" <?php if($drObj && $drObj->dr_is_verbal == 'N/A'){?>checked<?php }?> class="radio" value="N/A" />
                    <label for="dr_is_verbal_na" class="checkbox">N/A</label>
            </span>
        </p>

        <p>
            <label>Authorized or Written Request(Y/N) </label>
            <span class="radio-button-wrap">
                <input type="radio" name="dr_is_authorized" id="dr_is_authorized_yes" <?php if($drObj && $drObj->dr_is_authorized == 'Yes'){?>checked<?php }?> class="radio" value="Yes" />
                    <label for="dr_is_authorized_yes" class="checkbox">Yes</label>
                <input type="radio" name="dr_is_authorized" id="dr_is_authorized_no" <?php if(!$drObj || $drObj->dr_is_authorized == 'No'){?>checked<?php }?> class="radio" value="No" />
                    <label for="dr_is_authorized_no" class="checkbox">No</label>
                <input type="radio" name="dr_is_authorized" id="dr_is_authorized_na" <?php if($drObj && $drObj->dr_is_authorized == 'N/A'){?>checked<?php }?> class="radio" value="N/A" />
                    <label for="dr_is_authorized_na" class="checkbox">N/A</label>
            </span>
        </p>

        <div class="cboth"></div>

        <p>
            <strong style="line-height: 30px;">Comments</strong><br />
            <?php
            $fn = $formNote->get('note_text');
            echo $this->formTextarea($fn->setAttributes(array('style' => 'width: 450px;')));
            echo $this->formElementErrors($fn);
            ?>

        </p>

        <p style="border: 0;">
            <a id="browseFile" href="javascript:" class="button"><i class="fa fa-plus-circle"></i> Browse Files...</a>
        </p>

        <div class="cboth"></div>
        <div id="filesToUploadBox">

        </div>
        
        <div class="cboth"></div>
        
        <?php if ($this->drId && is_object($comments) && ($comments->count())): ?>
            <?php foreach ($comments as $note): ?>
                <div class="note">
                    <strong><?php echo $note->_username ?></strong> <small> on <?php echo $note->_note_create_date_format ?></small><br />
                    <p>
                        <?php echo $note->note_text ?><br />
                        <?php if ($note->_files != ''): ?>
                            <?php
                            $_files = explode(',', $note->_files);
                            ?>
                            <strong>Attachments:</strong><br />
                            <?php foreach ($_files as $_file): ?>
                                <?php
                                $_file = explode('::', $_file);
                                $_fileName = $_file[0];
                                $_fileId = $_file[1];
                                ?>
                                <span style="float: left; margin-right: 5px;" class="''?>"></span><a href="/files/get/note/<?php echo $note->note_id ?>/<?php echo $_fileId ?>" class="" target="_blank"><?php echo $_fileName ?></a><br/>

                            <?php endforeach; ?>
                        <?php endif; ?>
                    </p>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>

        <h5 class="fleft m10">Entered By</h5>

        <p>
            <?php $fn = $form->get('dr_entered_by');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        
        <p>
            <?php
            $fn = $form->get('dr_date_entered');
            if ($this->tlObj && $this->tlObj->dr_date_entered):
                $fn->setValue($this->formatDateA($this->tlObj->dr_date_entered, false, true));
            endif;
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required', 'id' => 'dr_date_entered', 'readonly' => 'readonly')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <h5 class="fleft m10">Reviewed and Approved By</h5>

        <p>
            <?php $fn = $form->get('dr_reviewed_by');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        
        <p>
            <?php
            $fn = $form->get('dr_date_reviewed');
            if ($this->tlObj && $this->tlObj->dr_date_reviewed):
                $fn->setValue($this->formatDateA($this->tlObj->dr_date_reviewed, false, true));
            endif;
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required', 'id' => 'dr_date_reviewed', 'readonly' => 'readonly')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <h5 class="fleft m10">Disclosed By</h5>

        <p>
            <?php $fn = $form->get('dr_disclosed_by');
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        
        <p>
            <?php
            $fn = $form->get('dr_date_disclosed');
            if ($this->tlObj && $this->tlObj->dr_date_disclosed):
                $fn->setValue($this->formatDateA($this->tlObj->dr_date_disclosed, false, true));
            endif;
            echo $this->formLabel($fn);
            echo $this->formInput($fn->setAttributes(array('class'=>'form-control required', 'id' => 'dr_date_disclosed', 'readonly' => 'readonly')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        
        <div class="cboth"></div>
        
        <div class="form-buttons">
            <input type="submit" value="Save" class="form-button" />
            <div class="fleft">or</div>
            <a href="/disclosurerecord/list" class="cancel">Cancel</a>
        </div>

    <?php echo $this->form()->closeTag() ?>
</div>

<div class="cboth"><br /></div>


<script type="text/javascript">
    var browseFilesCounter = 0;
    $(document).ready(function() {
        $('#browseFile').click(function() {
            $('#filesToUploadBox').append('<input type="file" name="notesFiles[]" id="file' + browseFilesCounter + '" />');

            $('#file' + browseFilesCounter).click();
            browseFilesCounter++;
        });
    });

    jQuery(function() {
        $('#disclosurerecord').validate();

        $("#dr_date_received, #dr_date_disclosure, #dr_date_of_birth, #dr_date_entered, #dr_date_reviewed, #dr_date_disclosed").datepicker({dateFormat: 'mm/dd/yy'});

    });
</script>
