<?php

// within a view script
$form = $this->form;
$form->prepare();

// Assuming the "contact/process" route exists...
$form->setAttribute('action', '/physicalsecuritychange/edit');

// Set the method attribute for the form
$form->setAttribute('method', 'post');

// Render the opening tag
?>


    <div class="page-title">
        <h1 class="fleft"><?php if($this->psc_id) {?>Edit <?php } else {?>Add New <?php }?>Security Change</h1>
        <div class="cboth"></div>
    </div>

    <p></p>

<div class="col-left">
    <form action="/physicalsecuritychange/edit/<?php echo $this->psc_id ?>" method="post" enctype="multipart/form-data" name="physicalsecuritychange" id="physicalsecuritychange">
        <?php
            $fn = $form->get('psc_id');
            echo $this->formHidden($fn);
        ?>
        <?php
            $fn = $form->get('psc_active');
            echo $this->formHidden($fn);
        ?>

        <?php
            $authService = new \Zend\Authentication\AuthenticationService();
            $authService->setStorage(new \SanAuth\Model\MyAuthStorage('hipaa'));
            $identity = $authService->getIdentity();
        ?>

        <p>
            <?php $fn = $form->get('psc_c_id');
            echo $this->formLabel($fn);
            echo $this->formSelect($fn->setAttributes(array('class'=>'form-control required', 'id' => 'company')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <p>
            <?php $fn = $form->get('psc_adr_id');
            echo $this->formLabel($fn);
            echo $this->formSelect($fn->setAttributes(array('id'=>'location', 'class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>
        
        <p>
            <?php $fn = $form->get('psc_adr_id');
            echo $this->formLabel($fn);
            echo $this->formSelect($fn->setAttributes(array('id'=>'location', 'class'=>'form-control required')));
            echo $this->formElementErrors($fn);
            ?>
        </p>

        <div class="cboth"></div>

        <p>
            <strong style="line-height: 30px;">Comments</strong><br />
            <?php
            $fn = $formNote->get('note_text');
            echo $this->formTextarea($fn->setAttributes(array('style' => 'width: 450px;')));
            echo $this->formElementErrors($fn);
            ?>

        </p>
        <p style="border: 0;">
            <a id="browseFile" href="javascript:" class="button"><i class="fa fa-plus-circle"></i> Browse Files...</a>
            <br /><br /><br />
        </p>

        <div class="cboth"></div>
        <div id="filesToUploadBox">

        </div>
        
        <div class="cboth"></div>
        
        <?php if ($this->psc_id && is_object($comments) && ($comments->count())): ?>
            <?php foreach ($comments as $note): ?>
                <div class="note">
                    <strong><?php echo $note->_username ?></strong> <small> on <?php echo $note->_note_create_date_format ?></small><br />
                    <p>
                        <?php echo $note->note_text ?><br />
                        <?php if ($note->_files != ''): ?>
                            <?php
                            $_files = explode(',', $note->_files);
                            ?>
                            <strong>Comments:</strong><br />
                            <?php foreach ($_files as $_file): ?>
                                <?php
                                $_file = explode('::', $_file);
                                $_fileName = $_file[0];
                                $_fileId = $_file[1];
                                ?>
                                <span style="float: left; margin-right: 5px;" class="''?>"></span><a href="/files/get/note/<?php echo $note->note_id ?>/<?php echo $_fileId ?>" class="" target="_blank"><?php echo $_fileName ?></a><br/>

                            <?php endforeach; ?>
                        <?php endif; ?>
                    </p>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
        
        <div class="cboth"></div>
        
        <div class="form-buttons">
            <input type="submit" value="Save" class="form-button" />
            <div class="fleft">or</div>
            <a href="/physicalsecuritychange/list" class="cancel">Cancel</a>
        </div>

    <?php echo $this->form()->closeTag() ?>
</div>

<div class="cboth"><br /></div>


<script type="text/javascript">
    jQuery(function() {
        $('#physicalsecuritychange').validate();

        var browseFilesCounter = 0;
        
        $(document).ready(function() {
            $('#browseFile').click(function() {
                $('#filesToUploadBox').append('<div><input type="file" name="notesFiles[]" id="file' + browseFilesCounter + '" /><div class="cboth"></div></div>');

                $('#file' + browseFilesCounter).click();
                browseFilesCounter++;
            });
        });

        $("#company").change(function(){
            getCompanyLocations()
        });

        function getCompanyLocations()
        {
            var cId = $("#company option:selected").val();
            
            if(cId != undefined && cId != '') {
                $.ajax({
                    type:"GET",
                    url:"/traininglog/gettrainers/" + cId,
                    success: function(data){
                        var html = '<option value="">Please Select</option>';
                        $.each(data, function(index, value) {
                            html += '<option value="' + index + '">' + value + '</option>';
                        });
                        $('#_tl_trainer').html(html);
                    }
                });
            }
        }
    });
</script>
