<?php
$urlOrder = $order == 'ASC' ? 'DESC' : 'ASC';
$authService = new \Zend\Authentication\AuthenticationService();
$authService->setStorage(new \SanAuth\Model\MyAuthStorage('hipaa'));
$identity = $authService->getIdentity();
$isClientRole = $identity['u_role_id'] == 5 ? 1 : 0;
?>

<div class="page-title">
    <h1 class="fleft">Incident Remediation Plans</h1>
    <div class="cboth"></div>
</div>

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
<p></p>

<table id="incident-remediation-plan-list-table" cellpadding="0" cellspacing="0">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <?php if (!$isClientRole): ?>
                <th>Client</th>
            <?php endif; ?>
            <th>Status</th>
            <th>Date</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        <?php $isVersion = false; $counterVersion = 0; $paddingVersion = 0; $rowIdParent = ''; $isParentActive = false; $lastVersionIndex = 0;
        foreach ($this->paginator as $brp): ?>
            <?php
            if (!$brp->brp_parent_brp_id):
                $rowId = $brp->brp_id;
                $rowIdParent = $brp->brp_id;
                if ($isVersion):
                    $counterVersion = 0;
                endif;
                $paddingVersion = 0;
                $isVersion = false;
                $isParentActive = true;
                $lastVersionIndex = $brp->brp_id;
            else:
                if ($lastVersionIndex != $brp->brp_version_index):
                    $lastVersionIndex = $brp->brp_version_index;
                    $isParentActive = false;
                endif;

                $counterVersion++;
                if (!$isParentActive):
                    $isParentActive = true;
                    $counterVersion = 0;
                    $isVersion = false;
                else:
                    $isVersion = true;
                endif;

                $paddingVersion = $counterVersion * 20;
                $rowId = $brp->brp_version_index . '-' . $brp->brp_version_index_item;
            endif;
            $classBold = '';
            if ($brp->brp_status == 10):
                $classBold = ' bold ';
            endif;

            ?>
            <tr>
                <td class="<?php echo $classBold ?>"><?php echo $brp->brp_id ?></td>
                <td class="<?php echo $classBold ?>"><a href="/breachremediationplan/edit/<?php echo $brp->brp_id ?>"><?php echo $brp->_bl_name ?></a></td>
                <?php if (!$isClientRole): ?>
                    <td class="<?php echo $classBold ?>" style="padding-left: <?php echo $paddingVersion ?>px"><?php if ($isVersion): ?><i class="fa fa-code-fork"></i> &nbsp; <?php endif ?><a href="/breachremediationplan/edit/<?php echo $brp->brp_id ?>"><?php echo stripslashes($brp->_client_name) ?></a></td>
                <?php endif; ?>
                <td class="<?php echo $classBold ?>"><?php echo \Breachlog\Model\Breachremediationplan::$statusesNames[$brp->brp_status]  ?></td>
                <td class="<?php echo $classBold ?>"><?php echo ($brp->brp_incident_date != '0000-00-00') ? $this->formatDateA($brp->brp_incident_date) : '' ?></td>
                <td style="white-space: nowrap;" class="aright <?php echo $classBold ?>">
                    <a class="<?php echo $classBold ?>" href="/breachremediationplan/edit/<?php echo $brp->brp_id ?>" title="Edit"><i class="fa fa-pencil"></i></a> &nbsp;
                    <?php if (!$isClientRole): ?>
                        <?php if ($brp->brp_active): ?>
                            <?php $deleteUrl = '/breachremediationplan/delete/' . $brp->brp_id; ?>
                            <a href="#confirmation-box-modal" onclick="$('#deleteYes').attr('href', '<?php echo $deleteUrl ?>')" class="confirmation-modal i-delete <?php echo $classBold ?>"><i class="fa fa-trash-o"></i></a>
                        <?php elseif ($identity['u_role_id'] == \Admin\Model\User::ROLE_ADMIN): ?>
                            <a href="/breachremediationplan/unarchive/<?php echo $brp->brp_id ?>" class="">Unarchive</a>
                        <?php endif; ?>
                    <?php endif; ?>
                </td>
            </tr>

        <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(document).ready( function () {
        $('#incident-remediation-plan-list-table').DataTable(
            {
                "order": [],
                "columnDefs": [
                    { "type": "date", "targets": 4},
                    { "orderable": false, "targets": 5 }
                ]
            }
        );
        $('.dataTables_filter input[type="search"]').
        css({'width':'95%','display':'inline-block'});
    } );
</script>

<div class="cboth"><br /></div>