<?php

// within a view script
$form = $this->form;
$form->prepare();

// Assuming the "contact/process" route exists...
$form->setAttribute('action', '/assessment/edit');

// Set the method attribute for the form
$form->setAttribute('method', 'post');

// Render the opening tag
?>

<style>
    .labelBold label {
        font-weight: 700;
    }
    #step1 {
        margin-top: 30px;
    }

    .col-left {
        min-height: 0;
    }
</style>

<div class="page-title">
    <h1 class="fleft">
        <?php if ($this->aId): ?>
            Assessment for <?php echo $this->aObj->_client_name; ?>
        <?php endif; ?>
    </h1>

    <div class="cboth"></div>
</div>

    <h2><?php if ($this->aObj->a_type == 1): ?>Step 3 of 3 - <?php endif; ?><?php echo $this->locationName . ' ' . $this->assessmentRoleName ?> Interview</h2>

    <?php $locationName = ''; ?>
    <div>
        <?php if (!$this->isClosed): ?>
            <form action="/assessment/edit/<?php echo $this->aId ?>/step/3/adrId/<?php echo $this->location ?>/assessmentRole/<?php echo $this->assessmentRole ?>" method="post" name="assessment" id="assessment" enctype="multipart/form-data">
        <?php endif; ?>
            <input type="hidden" name="locationHidden" value="<?php echo $this->location ?>" />
            <div class="fleft" style="width: 480px;">
                <p>
                    <?php
                    $locationRole = $this->location . '_' . $this->assessmentRole;
                    ?>
                    <label style="font-weight: 700;">Switch Interview</label>
                    <select name="locationRole" id="selectLocation">
                        <option value="">Select Interview</option>
                        <option value="">---</option>
                        <?php foreach ($this->addresses as $address): ?>
                            <?php if ($this->location == $address->adr_id) $locationName = $address->adr_name; ?>
                            <optgroup label="<?php echo $address->adr_name ?>">
                                <?php $counterRoles = 0; $last = ''; ?>
                                <?php foreach ($this->assessmentsRoles->buffer() as $ar): ?>
                                    <option <?php echo $locationRole == $address->adr_id . '_' . $ar['ar_id'] ? ' SELECTED ' : '' ?> value="<?php echo $address->adr_id ?>_<?php echo $ar['ar_id'] ?>"><?php echo $ar['ar_name'] ?></option>
                                <?php $counterRoles++; endforeach; ?>
                            </optgroup>
                        <?php endforeach; ?>
                    </select>
                </p>
            </div>

            <?php if ($this->location): ?>
                <div class="fright" style="width: 480px;">
                    <p style="padding: 20px 0 0 190px;">
                        <input type="checkbox" name="checkbox1" id="answeredCheckbox" class="checkbox" value="" />
                        <label for="answeredCheckbox" class="checkbox">Show Only Un-Answered Questions</label>
                    </p>
                </div>
            <?php endif; ?>
            <p></p>
        </form>
    </div>

    <form action="/assessment/edit/<?php echo $this->aId ?>/step/3/adrId/<?php echo $this->location ?>/assessmentRole/<?php echo $this->assessmentRole ?>" method="post" name="assessment" id="assessment2" enctype="multipart/form-data">
        <input id="setStep" type="hidden" name="setStep" value="" />
        <input id="autoSave" type="hidden" name="autoSave" value="" />
        <?php
            $fn = $form->get('a_id');
            echo $this->formHidden($fn);
        ?>

        <?php if ($this->location && $this->assessmentRole): ?>
            <?php

            $maxCounterQuestions = 0;
            foreach ($this->questions as $question):
                $maxCounterQuestions++;
                foreach ($question['elements'] as $questionEl):
                    if (isset($questionEl['children'])):
                        $maxCounterQuestions += count($questionEl['children']);
                    endif;
                endforeach;
            endforeach;

            $counterQuestions = 1;
            foreach ($this->questions as $question): ?>
                <div class="col-left">
                    <?php foreach ($question['elements'] as $questionEl): ?>
                        <?php
                        //echo '<pre>';
                        //print_r($questionEl);
                        //die;
                        ?>

                        <?php
                        $_options = $questionEl['_options'];
                        $_optionsT = explode(',', $_options);
                        $isYes = false;
                        foreach ($_optionsT as $_option):
                            $_optionT = explode('::', $_option);
                            $isYes = isset($this->answers[$questionEl['aq_id']]) && ($this->answers[$questionEl['aq_id']]['answerId'] == $_optionT[0]) && ($_optionT[1] == 'Yes') ? true : false;
                            if (isset($this->answers[$questionEl['aq_id']]) && ($questionEl['aq_id'] == 14)):
                                $isYes = isset($this->answers[$questionEl['aq_id']]) && ($this->answers[$questionEl['aq_id']]['answerId'] == $_optionT[0]) && ($_optionT[1] == 'No') ? true : false;
                            endif;
                            if ($isYes):
                                break;
                            endif;
                        endforeach; ?>

                        <div class="questionBox" rel="<?php echo $questionEl['aq_id'] ?>" id="question<?php echo $questionEl['aq_id'] ?>">
                            <?php echo $this->partial('assessment/assessment/_question.phtml', array('isClosed' => $this->isClosed, 'questionEl' => $questionEl, 'maxCounterQuestions' => $maxCounterQuestions, 'counterQuestions' => $counterQuestions, 'answers' => $this->answers, 'isParent' => true)); ?>
                        </div>

                        <div <?php echo !$isYes ? ' style="display: none;" ' : '' ?> id="childrenQuestions<?php echo $questionEl['aq_id'] ?>" rel="<?php echo $questionEl['aq_id'] ?>" class="childrenQuestions">
                            <?php
                            if (isset($questionEl['children'])):
                                foreach ($questionEl['children'] as $questionElChild): ?>
                                    <?php $counterQuestions++; ?>
                                    <div class="questionBox" rel="<?php echo $questionElChild['aq_id'] ?>" id="question<?php echo $questionElChild['aq_id'] ?>">
                                        <?php echo $this->partial('assessment/assessment/_question.phtml', array('isClosed' => $this->isClosed, 'questionEl' => $questionElChild, 'maxCounterQuestions' => $maxCounterQuestions, 'counterQuestions' => $counterQuestions, 'answers' => !$isYes ? null : $this->answers, 'isParent' => false)); ?>
                                    </div>
                                <?php endforeach;
                            endif; ?>
                        </div>

                    <?php $counterQuestions++; endforeach; ?>
                </div>


                <div class="col-right" style="font-size: 14px; line-height: 21px;">

                    <div id="rightBox<?php echo $questionEl['aq_id'] ?>" class="rightBox" rel="<?php echo $questionEl['aq_id'] ?>" style="float: right; width: 240px; padding: 18px 30px 12px 30px; background: #ededed; border-radius: 12px;">
                        <p><strong>Category</strong><br />&nbsp; &nbsp; <?php echo $this->aObj->a_type == 2 ? 'Privacy' : $question['cat']['aqc_name'] ?></p>
                        <p><strong>Citation</strong><br />&nbsp; &nbsp; <?php echo $question['cat']['aqc_citation'] ?></p>
                        <p><strong>Specification</strong><br />&nbsp; &nbsp; <?php echo $question['cat']['aqc_specification'] ?></p>
                        <p><strong>Policy and Procedure</strong><br />&nbsp; &nbsp; <?php echo $question['cat']['aqc_policy'] ?></p>
                        <p><?php echo $question['cat']['aqc_description'] ?></p>
                    </div>

                </div>
                <div class="cboth" style="margin-bottom:1px;"></div>
            <?php endforeach; ?>

            <div class="form-buttons">
                <?php if (!$this->locationFinished): ?>
                <?php if (!$this->isClosed): ?>
                    <?php //if (($this->assessmentRole == 6) && ($this->location == $this->lastAdrId)): ?>
                    <?php //else: ?>
                        <input id="saveAndContinue" type="button" value="Save and Continue" class="form-button" />
                    <?php //endif; ?>
                    <input type="submit" value="Save" class="form-button" />
                    <div class="fleft">or</div>
                <?php endif; ?>
                <?php endif; ?>
                <a href="/assessment/list" class="cancel">Cancel</a>
            </div>

        <?php endif; ?>
        <div class="cboth"></div>
    <?php echo $this->form()->closeTag() ?>


<div class="cboth"><br /></div>
<?php
    $application_vars = new \Zend\Session\Container('application_vars');
    $assessment_interview_autosave_interval = $application_vars->storage['assessment_interview_autosave_interval'];
    ?>

<script type="text/javascript">    
    var assessment_interview_autosave_interval = <?php echo $assessment_interview_autosave_interval ? $assessment_interview_autosave_interval * 60000 : 60000; ?>;
    jQuery(document).ready(function() {
        window.setInterval(function(){
            $('#autoSave').val(1);
          $('#setStep').val(3);
            $('#assessment2').submit();
        }, assessment_interview_autosave_interval);

        renumeringQuestions();
        $('#saveAndContinue').click(function() {
            $('#setStep').val(3);
            $('#assessment2').submit();
        });

        $('#selectLocation').change(function() {
            var location = $(this).val();

            if (location) {
                window.location.href = '/assessment/edit/<?php echo $this->aId ?>/step/<?php echo $this->step ?>/locationRole/' + location;
            }
        });

        $('.parentInput').click(function() {
            var isYes = $(this).attr('rel') == 'Yes' ? true : false;
            var aqId = $(this).attr('name').replace('question[', '').replace(']', '');

            if (aqId == 14) {
                var isYes = $(this).attr('rel') == 'No' ? true : false;
            }

            if (isYes) {
                $('#childrenQuestions' + aqId).show();
            } else {
                $('#childrenQuestions' + aqId).hide();
                $('#childrenQuestions' + aqId).find('input').removeAttr('checked');
            }

            renumeringQuestions();
        });

        var browseFilesCounter = new Object();
        $('.browseFile').click(function() {
            var aqId = $(this).attr('rel');

            if (browseFilesCounter[aqId] == undefined) {
                browseFilesCounter[aqId] = 1;
            } else {
                browseFilesCounter[aqId]++;
            }
            $('#filesToUploadBox' + aqId).append('<input type="file" name="notesFiles[' + aqId + '][]" id="file' + aqId + '_' + browseFilesCounter[aqId] + '" />');

            $('#file' + aqId + '_' + browseFilesCounter[aqId]).unbind('click');

            $('#file' + aqId + '_' + browseFilesCounter[aqId]).click(function() {
                resetActivity();
            })

        });

        $('#answeredCheckbox').click(function() {
            if ($(this).is(':checked')) {
                $('.questionBox').each(function() {
                    var aqId = $(this).attr('rel');
                    if ($('#answered' + aqId).val() == 1) {
                        $(this).hide();
                    }
                });
                showHideRightBox();

            } else {
                $('.questionBox').show();
                $('.rightBox').parent().show();
            }
        });

        function showHideRightBox()
        {
            $('.rightBox').parent().show();

            $('.rightBox').each(function() {
                var parentId = $(this).attr('rel');

                var isChecked = true;
                var locIsChecked = false;
                $('#question' + parentId).find('input[type="radio"]').each(function() {
                   if ($(this).is(':checked')) {
                       locIsChecked = true;
                       return;
                   }
                });
                isChecked = locIsChecked;
                if (isChecked) {
                    $('#childrenQuestions' + parentId).find('.questionBox').each(function() {
                        var locIsChecked = false;
                        $(this).find('input[type="radio"]').each(function() {
                            if ($(this).is(':checked')) {
                                locIsChecked = true;
                                return;
                            }
                        });
                        if (!isChecked) {
                            isChecked = locIsChecked;
                            return;
                        }
                    });
                }
                if (isChecked) {
                    $(this).parent().hide();
                }

                //$('#childrenQuestions' + aqId).
                //alert(parentId)
            });
        }

        $('input[type="radio"]').click(function() {
            resetActivity();
        });

        <?php if ($_SERVER['SERVER_NAME'] == 'hipaa'): ?>
        // TESTING !!!
        $('input[type="radio"]').each(function() {
            if (($(this).attr('rel') == 'No') && ($(this).hasClass('parentInput'))) {
                $(this).attr('CHECKED', 'CHECKED');
            }
        });
        ////
        <?php endif; ?>

    });

    function resetActivity()
    {
        $.getJSON("/assessment/resetactivity", {  }, function(data) {
        });
    }

    function renumeringQuestions()
    {
        var counter = 1;
        $('.questionBox').each(function() {
            if ($(this).is(':visible')) {
                $(this).find('.questionNum').html(counter);
                counter++;
            }
        });

        $('.questionBox').find('.maxNum').html(counter - 1);
    }



</script>


