
<div class="page-title">
    <h1 class="fleft"><?php if ($this->aObj->a_type == 1): ?>Security<?php else: ?>Privacy<?php endif; ?> Risk Assessment Details<br />for <?php echo stripslashes($this->aObj->_client_name); ?></h1>
    <div class="cboth"></div>
</div>

<p></p>
<?php if ($this->aObj->a_type == 1): ?>
<div class="tab_nav">
    <ul class="ul_tabs">
    <?php foreach ($this->addresses->buffer() as $key => $address): ?>
    <?php if ($location == 0) { $location = $address->adr_id; } ?>
        <li <?php echo $location == $address->adr_id ? 'class="active_tab"' : ''; ?> >
        <a href="/assessment/editlist/<?php echo $this->aObj->a_id; ?><?php echo '/location/' . $address->adr_id; ?>" data-key="<?php echo $key; ?>" class="panel-tabs"><?php echo $this->aObj->_client_name . ' - ' . $address->adr_name ?></a>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
<div class="tab-panels">
<?php foreach ($this->addresses->buffer() as $key => $address): ?>
<?php if ($location != $address->adr_id) continue; ?>
<table cellpadding="0" cellspacing="0" style="width: 450px; margin: 0 auto;">
    <thead>
    
        <tr>
            <th width="60">&nbsp;</th>
            <th>Step 1</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <?php
            $stepClass = $this->checkSteps[1] ? 'fa-check' : 'fa-times';
            $color = $this->checkSteps[1] ? '' : 'color: #aaa';
            ?>
            <td class="acenter"><i style="<?php echo $color ?>" class="fa <?php echo $stepClass ?>"></i></td>
            <td><a href="/assessment/edit/<?php echo $this->aObj->a_id; ?>/step/1/location/<?php echo $location; ?>"><?php echo $address->adr_name; ?> contact information</a></td>
        </tr>

        <tr>
            <th>&nbsp;</th>
            <th>Step 2</th>
        </tr>

        <?php //foreach ($this->addresses->buffer() as $address): ?>
            <tr>
                <?php
                $stepClass = $this->checkSteps[2][$address->adr_id] ? 'fa-check' : 'fa-times';
                $color = $this->checkSteps[2][$address->adr_id] ? '' : 'color: #aaa';
                ?>
                <td class="acenter"><i style="<?php echo $color ?>" class="fa <?php echo $stepClass ?>"></i></td>
                <td><a href="/assessment/edit/<?php echo $this->aObj->a_id; ?>/step/2/location/<?php echo $address->adr_id ?>">Assign <?php echo $address->adr_name ?> Roles</a></td>
            </tr>
        <?php //endforeach; ?>

    <tr>
        <th>&nbsp;</th>
        <th>Step 3</th>
    </tr>

    <?php //foreach ($this->addresses->buffer() as $address): ?>
        <tr>
            <td class="acenter">&nbsp;</td>
            <td><em><?php echo $address->adr_name ?></em></td>
        </tr>

        <?php foreach ($this->assessmentsRoles->buffer() as $ar): ?>
            <tr>
                <?php
                $stepClass = $this->checkSteps[5][$address->adr_id][$ar->ar_id] ? 'fa-check' : 'fa-times';
                $color = $this->checkSteps[5][$address->adr_id][$ar->ar_id] ? '' : 'color: #aaa';
                ?>
                <td class="acenter"><i class="fa <?php echo $stepClass ?>" style="color: #777;"></i></td>
                <td><a href="/assessment/edit/<?php echo $this->aObj->a_id; ?>/step/3/locationRole/<?php echo $address->adr_id ?>_<?php echo $ar['ar_id'] ?>"><?php echo $ar->ar_name ?></a></td>
            </tr>
        <?php endforeach; ?>

    <?php //endforeach; ?>


    </tbody>
</table>
<?php endforeach; ?>
<?php else: ?>
<table cellpadding="0" cellspacing="0" style="width: 450px; margin: 0 auto;">
    <thead>

    <tr>
        <th>&nbsp;</th>
        <th>Assessment Interview</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->addresses->buffer() as $address): ?>
        <tr>
            <td class="acenter">&nbsp;</td>
            <td><em><?php echo $address->adr_name ?></em></td>
        </tr>

        <?php foreach ($this->assessmentsRoles->buffer() as $ar): ?>
            <tr>
                <?php
                $stepClass = $this->checkSteps[5][$address->adr_id][$ar->ar_id] ? 'fa-check' : 'fa-times';
                $color = $this->checkSteps[5][$address->adr_id][$ar->ar_id] ? '' : 'color: #aaa';
                ?>
                <td class="acenter"><i class="fa <?php echo $stepClass ?>" style="color: #777;"></i></td>
                <td><a href="/assessment/edit/<?php echo $this->aObj->a_id; ?>/step/3/locationRole/<?php echo $address->adr_id ?>_<?php echo $ar['ar_id'] ?>"><?php echo $ar->ar_name ?></a></td>
            </tr>
        <?php endforeach; ?>

    <?php endforeach; ?>


    </tbody>
</table>
<?php endif; ?>
</div>
<div class="cboth"><br /></div>