
<div class="page-title">
    <h1 class="fleft"><?php if ($this->aObj->a_type == 1): ?>Security<?php else: ?>Privacy<?php endif; ?> Risk Assessment Details<br />for <?php echo stripslashes($this->aObj->_client_name); ?></h1>
    <div class="cboth"></div>
</div>

<p></p>

<table cellpadding="0" cellspacing="0" style="width: 450px; margin: 0 auto;">
    <thead>
    <?php if ($this->aObj->a_type == 1): ?>
        <tr>
            <th width="60">&nbsp;</th>
            <th>Step 1</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <?php
            $stepClass = $this->checkSteps[1] ? 'fa-check' : 'fa-times';
            $color = $this->checkSteps[1] ? '' : 'color: #aaa';
            ?>
            <td class="acenter"><i style="<?php echo $color ?>" class="fa <?php echo $stepClass ?>"></i></td>
            <td><a href="/assessment/edit/<?php echo $this->aObj->a_id; ?>/step/1">Enter Locations</a></td>
        </tr>

        <tr>
            <th>&nbsp;</th>
            <th>Step 2</th>
        </tr>

        <?php foreach ($this->addresses->buffer() as $address): ?>
            <tr>
                <?php
                $stepClass = $this->checkSteps[2][$address->adr_id] ? 'fa-check' : 'fa-times';
                $color = $this->checkSteps[2][$address->adr_id] ? '' : 'color: #aaa';
                ?>
                <td class="acenter"><i style="<?php echo $color ?>" class="fa <?php echo $stepClass ?>"></i></td>
                <td><a href="/assessment/edit/<?php echo $this->aObj->a_id; ?>/step/2/location/<?php echo $address->adr_id ?>">Assign <?php echo $address->adr_name ?> Roles</a></td>
            </tr>
        <?php endforeach; ?>

        <tr>
            <th>&nbsp;</th>
            <th>Step 3</th>
        </tr>

        <?php foreach ($this->addresses->buffer() as $address): ?>
            <tr>
                <?php
                $stepClass = $this->checkSteps[3][$address->adr_id] ? 'fa-check' : 'fa-times';
                $color = $this->checkSteps[3][$address->adr_id] ? '' : 'color: #aaa';
                ?>

                <td class="acenter"><i style="<?php echo $color ?>" class="fa <?php echo $stepClass ?>"></i></td>
                <td><a href="/assessment/edit/<?php echo $this->aObj->a_id; ?>/step/3/location/<?php echo $address->adr_id ?>">Inventory <?php echo $address->adr_name ?> Assets</a></td>
            </tr>
        <?php endforeach; ?>

        <tr>
            <th>&nbsp;</th>
            <th>Step 4</th>
        </tr>

        <?php foreach ($this->addresses->buffer() as $address): ?>
            <tr>
                <?php
                $stepClass = $this->checkSteps[4][$address->adr_id] ? 'fa-check' : 'fa-times';
                $color = $this->checkSteps[4][$address->adr_id] ? '' : 'color: #aaa';
                ?>
                <td class="acenter"><i style="<?php echo $color ?>" class="fa <?php echo $stepClass ?>"></i></td>
                <td><a href="/assessment/edit/<?php echo $this->aObj->a_id; ?>/step/4/location/<?php echo $address->adr_id ?>">Business Associates for <?php echo $address->adr_name ?></a></td>
            </tr>
        <?php endforeach; ?>
    <?php endif; ?>

    <tr>
        <th>&nbsp;</th>
        <th><?php if ($this->aObj->a_type == 1): ?>Step 5<?php else: ?>Assessment Interview<?php endif; ?></th>
    </tr>

    <?php foreach ($this->addresses->buffer() as $address): ?>
        <tr>
            <td class="acenter">&nbsp;</td>
            <td><em><?php echo $address->adr_name ?></em></td>
        </tr>

        <?php foreach ($this->assessmentsRoles->buffer() as $ar): ?>
            <tr>
                <?php
                $stepClass = $this->checkSteps[5][$address->adr_id][$ar->ar_id] ? 'fa-check' : 'fa-times';
                $color = $this->checkSteps[5][$address->adr_id][$ar->ar_id] ? '' : 'color: #aaa';
                ?>
                <td class="acenter"><i class="fa <?php echo $stepClass ?>" style="color: #777;"></i></td>
                <td><a href="/assessment/edit/<?php echo $this->aObj->a_id; ?>/step/5/locationRole/<?php echo $address->adr_id ?>_<?php echo $ar['ar_id'] ?>"><?php echo $ar->ar_name ?></a></td>
            </tr>
        <?php endforeach; ?>

    <?php endforeach; ?>


    </tbody>
</table>

<div class="cboth"><br /></div>

