
        <div class="col-md-3 center"><!-- Jeżeli nikt nie jest zalogowany -->
          <div class="affix-button-container affix" data-offset-top="0" data-spy="affix">
          <a href="/contest/activelist" class="btn btn-primary btn-lg center affixed">
            Zobacz wszystkie <br> konkursy
          </a>
          </div>
          <br><br><br><br><br>
          <div class="affix-button-container affix" data-offset-top="0" data-spy="affix">
          <a href="/practice/activelist" class="btn btn-primary btn-lg center affixed">
            Zobacz wszystkie <br> dobre prakyki
          </a>
          </div>
        </div>
        
        <div class="col-md-9"><!-- Tu się zmienia klasa  -->
        <!-- ################################# Konkurs #################################  -->
          <div class="panel panel-default">
            <div class="panel-heading"><h1>Informacje o bazie</h1></div>
            <div class="panel-body justify">
                <p>Baza Dobrych Praktyk stworzona przez Fundację Instytut Rozwoju Regionalnego ma na celu zapewnienie pełnej informacji o działaniach jednostek administracji publicznej na rzecz zatrudnienia osób niepełnosprawnych oraz ich aktywizacji zawodowej i społecznej.</p>
                <br>
                <p>Baza pełni funkcje edukacyjne i promocyjne, w celu  wywołania pozytywnej zmiany w polityce na rzecz osób niepełnosprawnych. Zebrane informacje w sposób bezpośredni od instytucji, zostają podane do wiedzy wszystkich zainteresowanych obywateli. Taki ogólnodostępny przegląd projektów na rzecz osób niepełnosprawnych  zmobilizuje samorządy do podejmowania nowych i lepszych inicjatyw na rzecz osób niepełnosprawnych. To oznacza w konsekwencji bogatszą ofertę kierowaną lokalnie do tej grupy osób &ndash; usprawnienie usług samorządowych (edukacja, transport, informacja, dostęp do obiektów użyteczności publicznej itd.), które dotyczą osób niepełnosprawnych.</p>
                <br>
                <p>Baza jest również uzupełniona o dane dotyczące wielkości samorządów, gdzie działają dane jednostki administracji publicznej, liczby niepełnosprawnych mieszkańców i innych kwestii, mających bezpośrednie odniesienie do poziomu i jakości realizowanych działań. Informacje pozyskane w ten sposób umożliwiają analizę jakościową działań tych jednostek oraz poddanie ich ocenie obywateli - wszystkich użytkowników Internetu zainteresowanych tą problematyką. </p>
                <br>
                <p>Baza Dobrych Praktyk jest współfinansowana ze środków Unii Europejskiej w ramach Europejskiego Funduszu Społecznego</p>

            </div>
          </div>
        <!-- END Konkurs -->
        </div>