

        <div class="col-md-3 center"><!-- Jeżeli nikt nie jest zalogowany -->
          <div class="affix-button-container affix" data-offset-top="0" data-spy="affix">
          <a href="/contest/activelist" class="btn btn-primary btn-lg center affixed">
            Zobacz wszystkie <br> konkursy
          </a>
          </div>
          <br><br><br><br><br>
          <div class="affix-button-container affix" data-offset-top="0" data-spy="affix">
          <a href="/practice/activelist" class="btn btn-primary btn-lg center affixed">
            Zobacz wszystkie <br> dobre prakyki
          </a>
          </div>
        </div>
        
        <div class="col-md-9"><!-- Tu się zmienia klasa  -->
        <!-- ################################# Konkurs #################################  -->
          <div class="panel panel-default">
            <div class="panel-heading"><h1>Kontakt</h1></div>
            <div class="panel-body justify">
              <div class="row">
                <div class="col-md-6">
                <address class="center">
                <h2>Fundacja Instytut Rozwoju Regionalnego</h2>
                ul. Wybickiego 3A<br>
                31-261 Kraków<br>
                Tel.: 12 629 85 14<br>
                Faks: 12 629 85 15<br>
                Mail: biuro@firr.org.pl <br>
                             
              </address></div>
              <div class="col-md-6">
                <address class="center">
                <h2>Kontakt dla dziennikarzy</h2>
                <strong>Piotr Pawłowski</strong><br>
                Specjalista ds. PR<br>
                Tel.: 663 000 033<br>
                Mail: piotr.pawlowski@firr.org.pl<br>
                </address>
                </div>
              </div>
              <br><br><br><br><br><br>

            </div>
          </div>
        <!-- END Konkurs -->
        </div>
