
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-12">
                <h1><?php echo $this->translate('Konkursy na najlepszą dobrą praktykę') ?></h1>
            </div>
            <div class="col-md-7">
                <img src="http://i.istockimg.com/file_thumbview_approve/20904302/2/stock-photo-20904302-student-sitting-on-a-wheelchair-in-library-studying-with-schoolmate.jpg" width="100%">
            </div>
            <div class="col-md-5">
                <p class="justify">malt microbrewery units of bitterness mouthfeel ipa gravity caramel malt aau trappist hard cider bock anaerobic. alcohol hand pump saccharification hefe craft beer. berliner weisse pub pitch length lauter tun. beer alpha acid amber, wheat beer glass. goblet saccharification hop back imperial.</p>
                <a class="btn pull-right btn-primary"><?php echo $this->translate('Lista konkursów') ?></a>
            </div>
        </div>

        <h1><?php echo $this->translate('Baza dobrych praktyk') ?>&nbsp;</h1>
        <div class="row">
            <div class="col-md-7">
                <img src="http://i.istockimg.com/file_thumbview_approve/15439489/2/stock-photo-15439489-rollin.jpg" width="100%">
            </div>
            <div class="col-md-5">
                <p class="justify">malt microbrewery units of bitterness mouthfeel ipa gravity caramel malt aau trappist hard cider bock anaerobic. alcohol hand pump saccharification hefe craft beer. berliner weisse pub pitch length lauter tun. beer alpha acid amber, wheat beer glass. goblet saccharification hop back imperial.</p>
                <a class="btn pull-right btn-primary">Baza dobrych praktyk</a>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="row superwell">
            <div class="col-md-6">
                <a href="/practice/list" class="btn btn-block btn-xl btn-primary"><?php echo $this->translate('Dobre praktyki') ?></a>
            </div>
            <div class="col-md-6 first-page-buttons-row ">
                <a class="btn btn-block btn-xl btn-primary"><?php echo $this->translate('Konkursy') ?></a>
            </div>
        </div>
    </div>
    <hr>
    <div class="col-md-6 well-white">
        <table class="table table-hover table-striped last_bdp">
            <thead>
            <tr>
                <th><?php echo $this->translate('Ostatnio dodane dobre praktyki') ?></th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    <a>Konkurs na podjazd w&oacute;zk&oacute;w do urzędu gminy</a>
                    <div>
                        <img src="http://i.istockimg.com/file_thumbview_approve/20904302/2/stock-photo-20904302-student-sitting-on-a-wheelchair-in-library-studying-with-schoolmate.jpg" class="img-thumbnail pull-left" width="150" height="150">
                        <p><b>Instytucja realizująca: </b>Urząd gminy Nawojowa</p>
                        <p><b>Projekt dotyczy: </b>Os&oacute;w z niepełnosprawnością</p>
                        <p><b>Zasięg projektu: </b>Lokalny</p>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <a>Konkurs na podjazd w&oacute;zk&oacute;w do urzędu gminy</a>
                    <div>
                        <img src="http://i.istockimg.com/file_thumbview_approve/20904302/2/stock-photo-20904302-student-sitting-on-a-wheelchair-in-library-studying-with-schoolmate.jpg" class="img-thumbnail pull-left" width="150" height="150">
                        <p><b>Instytucja realizująca: </b>Urząd gminy Nawojowa</p>
                        <p><b>Projekt dotyczy: </b>Os&oacute;w z niepełnosprawnością</p>
                        <p><b>Zasięg projektu: </b>Lokalny</p>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <a>Konkurs na podjazd w&oacute;zk&oacute;w do urzędu gminy</a>
                    <div>
                        <img src="http://i.istockimg.com/file_thumbview_approve/20904302/2/stock-photo-20904302-student-sitting-on-a-wheelchair-in-library-studying-with-schoolmate.jpg" class="img-thumbnail pull-left" width="150" height="150">
                        <p><b>Instytucja realizująca: </b>Urząd gminy Nawojowa</p>
                        <p><b>Projekt dotyczy: </b>Os&oacute;w z niepełnosprawnością</p>
                        <p><b>Zasięg projektu: </b>Lokalny</p>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <a>Konkurs na podjazd w&oacute;zk&oacute;w do urzędu gminy</a>
                    <div>
                        <img src="http://i.istockimg.com/file_thumbview_approve/20904302/2/stock-photo-20904302-student-sitting-on-a-wheelchair-in-library-studying-with-schoolmate.jpg" class="img-thumbnail pull-left" width="150" height="150">
                        <p><b>Instytucja realizująca: </b>Urząd gminy Nawojowa</p>
                        <p><b>Projekt dotyczy: </b>Os&oacute;w z niepełnosprawnością</p>
                        <p><b>Zasięg projektu: </b>Lokalny</p>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <a>Konkurs na podjazd w&oacute;zk&oacute;w do urzędu gminy</a>
                    <div>
                        <img src="http://i.istockimg.com/file_thumbview_approve/20904302/2/stock-photo-20904302-student-sitting-on-a-wheelchair-in-library-studying-with-schoolmate.jpg" class="img-thumbnail pull-left" width="150" height="150">
                        <p><b>Instytucja realizująca: </b>Urząd gminy Nawojowa</p>
                        <p><b>Projekt dotyczy: </b>Os&oacute;w z niepełnosprawnością</p>
                        <p><b>Zasięg projektu: </b>Lokalny</p>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
