<?php
$urlOrder = $order == 'ASC' ? 'DESC' : 'ASC';
$authService = new \Zend\Authentication\AuthenticationService();
$authService->setStorage(new \SanAuth\Model\MyAuthStorage('hipaa'));
$identity = $authService->getIdentity();
?>


<script src="https://kit.fontawesome.com/e1b4bd3382.js" crossorigin="anonymous"></script>

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>

<div class="page-title">
    <div class="tooltip">
        <i class="fas fa-info-circle"></i><span class="tooltiptext" style="top: 100%; height: 80px;">A person or organization that performs a function or activity on behalf of a covered entity (with access to the covered entity’s PHI) but is not part of the covered entity’s workforce. A Business Associate can also be a covered entity in its own right. Also see Part II, 45 CFR 160.103.</span>
    </div>
    <h1 class="fleft">Business Associates</h1>
    <a href="/businessassociate/edit" class="button"><i class="fa fa-plus-circle"></i> Add New Business Associate</a>
    <div class="cboth"></div>
</div>

<p></p>

<table id="business-list" cellpadding="0" cellspacing="0">
    <thead>
        <tr>
            <?php $classSort = ($order_by == 'id') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>ID</th>

            <?php $classSort = ($order_by == 'name') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>Name</th>

            <?php $classSort = ($order_by == 'uid') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>Contact Name</th>

            <?php $classSort = ($order_by == 'client') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>Client Name</th>

            <?php $classSort = ($order_by == 'agreement') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>Agreement</th>


            <?php $classSort = ($order_by == 'email') ? ($order == 'DESC') ? ' fa-sort-asc' : 'fa-sort-desc' : 'fa-unsorted'; ?>
            <th>Email</th>

            <th>Phone</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->paginator as $ba): ?>
            <tr>
                <td><?php echo $ba->ba_id ?></td>
                <td><a href="/businessassociate/edit/<?php echo $ba->ba_id ?>"><?php echo $ba->ba_name ?></a></td>
                <td><?php echo $ba->_contact_name ?></td>
                <td><?php echo $ba->_client_name ?></td>
                <td>
                    <?php if (!is_numeric($ba->ba_agreement_status)): ?>
                        Not Assessed
                    <?php else: ?>
                        <?php echo $ba->ba_agreement_status ? 'Required' : 'Not Required' ?>
                    <?php endif; ?>
                </td>
                <td><a href="mailto:<?php echo $ba->ba_email ?>"><?php echo $ba->ba_email ?></a></td>
                <td style="white-space: nowrap;"><?php echo $ba->ba_office_phone ?></td>
                <td style="white-space: nowrap;" class="aright">
                    <a href="/businessassociate/edit/<?php echo $ba->ba_id ?>" title="Edit"><i class="fa fa-pencil"></i></a> &nbsp;
                    <?php if ($ba->ba_active): ?>
                        <?php $deleteUrl = '/businessassociate/delete/' . $ba->ba_id; ?>
                        <a href="#confirmation-box-modal" onclick="$('#deleteYes').attr('href', '<?php echo $deleteUrl ?>')" class="confirmation-modal i-delete"><i class="fa fa-trash-o"></i></a>
                    <?php elseif ($identity['u_role_id'] == \Admin\Model\User::ROLE_ADMIN): ?>
                        <a href="/businessassociate/unarchive/<?php echo $ba->ba_id ?>" class="">Unarchive</a>
                    <?php endif; ?>
                </td>
            </tr>

        <?php endforeach; ?>
    </tbody>
</table>
<script>
	$(document).ready( function () {
		$('#business-list').DataTable({
			"order": [[ 2, "asc" ]],
			"columnDefs": [
				{"type": "num", "targets": 0},
				{ "orderable": false, "targets": 7 }
			]
		});
	});
	$('.dataTables_filter input[type="search"]').
		css({'width':'95%','display':'inline-block'});
</script>

<div class="cboth"><br /></div>