CREATE TABLE `business_associates` (                                                                                                                            
          `ba_id` int(11) NOT NULL AUTO_INCREMENT,
	  `ba_contact_u_id` int(11) DEFAULT NULL,
	  `ba_consultant_u_id` int(11) DEFAULT NULL,                                                                                                         
          `ba_name` varchar(100) DEFAULT NULL,                                                                                                                                                                                                                       
          `ba_office_phone` varchar(50) DEFAULT NULL,                                                                                                      
          `ba_office_phone_inner` varchar(50) DEFAULT NULL,                                                                                                
          `ba_direct_phone` varchar(50) DEFAULT NULL,                                                                                                      
          `ba_direct_phone_inner` varchar(50) DEFAULT NULL,                                                                                                
          `ba_other_phone` varchar(50) DEFAULT NULL,                                                                                                       
          `ba_other_phone_inner` varchar(50) DEFAULT NULL,                                                                                                 
          `ba_fax` varchar(50) DEFAULT NULL,                                                                                                               
          `ba_email` varchar(100) DEFAULT NULL,                                                                                                            
	  `ba_website` varchar(100) DEFAULT NULL,                                                                                                            	
          `ba_address1` varchar(255) DEFAULT NULL,                                                                                                         
          `ba_address2` varchar(255) DEFAULT NULL,                                                                                                         
          `ba_state_id` int(11) DEFAULT NULL,                                                                                                              
          `ba_city` varchar(255) DEFAULT NULL,                                                                                                             
          `ba_zip` varchar(255) DEFAULT NULL,
	  `ba_phone_call_status` tinyint(1) DEFAULT 0,                                                                 
	  `ba_agreement_status` tinyint(1) DEFAULT 0,                                                                 
	  `ba_assessment_status` tinyint(1) DEFAULT 0,                                                                 
	  `ba_hipaa_compliant_status` tinyint(1) DEFAULT 0,                                                                 
          `ba_active` tinyint(1) DEFAULT '1',                                                                                                              
          `ba_status` tinyint(1) DEFAULT '0',                                                                                                              
          `ba_create_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,                                                                                       
          `ba_update_date` timestamp NULL DEFAULT NULL,                                                                                                    
          PRIMARY KEY (`ba_id`),                                                                                                                           
          KEY `fk_ba_states` (`ba_state_id`)                                                                                                           
        ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;